// Generated by Node.js script

export type IObject = Record<string, any>

export interface ResultObject {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: IObject
  /**
   *
   */
  msg: string
}

export interface CouponForm {
  /**
   * 主键
   */
  id: number
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 发放数量
   */
  number: number
  /**
   * 使用门槛(0无 其他数值为门槛金额)
   */
  useThreshold: number
  /**
   * 使用范围(1通用 2指定课程可用 3指定课程不可用)
   */
  useScope: number
  /**
   * 使用范围不为通用详情
   */
  userScopeDetail: string
  /**
   * 领取方式(1人工发放 2系统赠送)
   */
  receiveType: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 使用时间(1固定时间 2当日起几天 3次日起几天)
   */
  useRestrictedType: number
  /**
   * 使用时间天数
   */
  useRestrictedNum: number
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 修改人ID
   */
  updateBy: number
  /**
   *
   */
  deptId: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
  /**
   *
   */
  idPathList: string[]
}

export interface Result {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: IObject
  /**
   *
   */
  msg: string
}

export interface UserForm {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 昵称
   */
  nickname: string
  /**
   * 手机号码
   */
  mobile: string
  /**
   * 性别
   */
  gender: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 邮箱
   */
  email: string
  /**
   * 用户状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 角色ID集合
   */
  roleIds: number[]
}

export interface UserChangePasswordForm {
  /**
   * 旧密码
   */
  srcPassword: string
  /**
   * 新密码
   */
  newPassword: string
  /**
   * 手机号
   */
  mobile: string
  /**
   * 邮箱
   */
  email: string
}

export interface UserOrderCourseForm {
  /**
   * 主键
   */
  id: string
  /**
   * 产品id
   */
  productId: number
  /**
   * 课程数量
   */
  productCount: number
  /**
   * 订单表id
   */
  orderId: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课时数量
   */
  courseCount: number
  /**
   * 已上数量
   */
  attendedCount: number
  /**
   * 已预约数量
   */
  appointmentCount: number
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 课程单价
   */
  productPrice: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 下单时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 下单人姓名
   */
  userName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
}

export interface ShoppingCartsForm {
  /**
   * 主键
   */
  id: string
  /**
   * 产品id
   */
  productId: number
  /**
   * 产品数量
   */
  productCount: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 产品名称
   */
  productName: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 组织id
   */
  deptId: number
  /**
   * 组织名称
   */
  deptName: string
  /**
   * 产品价格
   */
  price: string
}

export interface RotationChartForm {
  /**
   * 主键
   */
  id: string
  /**
   * 活动名称
   */
  name: string
  /**
   * 轮播图
   */
  bannerPicture: string
  /**
   * 跳转地址
   */
  jumpUrl: string
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 状态(1:启用;0:停用)
   */
  status: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 类型编码
   */
  typeCode: string
  /**
   * 类型名称
   */
  typeName: string
}

export interface RoleForm {
  /**
   * 角色ID
   */
  id: number
  /**
   * 角色名称
   */
  name: string
  /**
   * 角色编码
   */
  code: string
  /**
   * 排序
   */
  sort: number
  /**
   * 角色状态(1-正常；0-停用)
   */
  status: number
  /**
   * 数据权限
   */
  dataScope: number
}

export interface KeyValue {
  /**
   * 选项的值
   */
  key: string
  /**
   * 选项的标签
   */
  value: string
}

export interface MenuForm {
  /**
   * 菜单ID
   */
  id: number
  /**
   * 父菜单ID
   */
  parentId: number
  /**
   * 菜单名称
   */
  name: string
  /**
   * 菜单类型(1-菜单；2-目录；3-外链；4-按钮权限)
   */
  type: string
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径(vue页面完整路径，省略.vue后缀)
   */
  component: string
  /**
   * 权限标识
   */
  perm: string
  /**
   * 显示状态(1:显示;0:隐藏)
   */
  visible: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 菜单图标
   */
  icon: string
  /**
   * 跳转路径
   */
  redirect: string
  /**
   * 【菜单】是否开启页面缓存
   */
  keepAlive: number
  /**
   * 【目录】只有一个子路由是否始终显示
   */
  alwaysShow: number
  /**
   * 路由参数
   */
  params: KeyValue[]
}

export interface InstitutionForm {
  /**
   * 机构ID
   */
  id: number
  /**
   * 机构名称
   */
  name: string
  /**
   * 机构代号
   */
  institutionCode: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 机构负责人姓名
   */
  adminName: string
  /**
   * 机构负责人电话
   */
  adminMobile: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 类别，列表，上传字典institutionType的值
   */
  types: string[]
  /**
   * 简介
   */
  introduction: string
  /**
   * 图文详情
   */
  detail: string
  /**
   * 收款账户名
   */
  beneficiaryName: string
  /**
   * 收款账号
   */
  accountNumber: string
  /**
   * 收款银行
   */
  bankName: string
  /**
   * 收款二维码base64
   */
  paymentQrCode: string
  /**
   * 支付宝收款二维码base64
   */
  aliPaymentQrCode: string
  /**
   * 收款方式，具体枚举查看字典paymentType，wechat-微信收款码，alipay-支付宝收款码，bank-银行转账
   */
  paymentType: string
}

export interface HotWordRecordForm {
  /**
   * 主键
   */
  id: string
  /**
   * 热词
   */
  name: string
  /**
   * 显示顺序
   */
  count: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
}

export interface DictForm {
  /**
   * 字典ID
   */
  id: number
  /**
   * 类型编码
   */
  typeCode: string
  /**
   * 字典名称
   */
  name: string
  /**
   * 字典值
   */
  value: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序
   */
  sort: number
  /**
   * 字典备注
   */
  remark: string
}

export interface DictTypeForm {
  /**
   * 字典类型ID
   */
  id: number
  /**
   * 类型名称
   */
  name: string
  /**
   * 类型编码
   */
  code: string
  /**
   * 类型状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 备注
   */
  remark: string
}

export interface DeptForm {
  /**
   * 部门ID
   */
  id: number
  /**
   * 部门名称
   */
  name: string
  /**
   * 父部门ID
   */
  parentId: number
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
}

export interface CourseProductDetail {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: number
  /**
   *
   */
  productId: string
  /**
   *
   */
  courseId: string
  /**
   *
   */
  courseName: string
  /**
   *
   */
  mainPicture: string
  /**
   *
   */
  publicityPicture: string
  /**
   *
   */
  courseClassificationName: string
  /**
   *
   */
  courseClassificationId: string
  /**
   *
   */
  idPath: string
  /**
   *
   */
  courseHoursCount: number
  /**
   *
   */
  price: number
}

export interface CourseProductForm {
  /**
   * 主键
   */
  id: string
  /**
   * 课程产品名称
   */
  name: string
  /**
   * 组织id
   */
  deptId: number
  /**
   * 父节点id路径
   */
  treePath: string
  /**
   * 产品类型  1 单个产品  2组合产品
   */
  productType: number
  /**
   * 状态(1:上架;0:下架)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: number
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 修改人ID
   */
  updateUser: number
  /**
   * 创建人名称
   */
  updateUserName: string
  /**
   * 产品价格
   */
  price: string
  /**
   *
   */
  courseProductDetails: CourseProductDetail[]
  /**
   *
   */
  mainPicture: string
  /**
   * 会员ID
   */
  userId: string
  /**
   * 会员名称
   */
  userName: string
}

export interface CourseEvaluationForm {
  /**
   * 主键
   */
  id: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 用户头像
   */
  avatar: string
}

export interface CourseClassification {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: string
  /**
   *
   */
  name: string
  /**
   *
   */
  level: number
  /**
   *
   */
  parentId: string
  /**
   *
   */
  idPath: string
  /**
   *
   */
  status: number
  /**
   *
   */
  createUser: number
  /**
   *
   */
  updateUser: number
  /**
   * 组织id
   */
  deptId: number
  /**
   * 组织全量
   */
  deptFullId: string
  /**
   * 是否标签 0 否 1 是
   */
  labelIdentification: number
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 排序号
   */
  sort: number
}

export interface CountryAreaForm {
  /**
   *
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   *
   */
  createTime: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
}

export interface ArticleManagementForm {
  /**
   * 主键
   */
  id: string
  /**
   * 文章名称
   */
  title: string
  /**
   * 文章内容
   */
  articleDesc: string
  /**
   * 链接地址
   */
  linkUrl: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 文章分类
   */
  articleType: string
}

export interface OrderDetail {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: string
  /**
   *
   */
  productId: number
  /**
   *
   */
  productCount: number
  /**
   *
   */
  courseId: string
  /**
   *
   */
  orderId: string
  /**
   *
   */
  productPrice: number
  /**
   *
   */
  productAmount: number
  /**
   *
   */
  courseName: string
  /**
   *
   */
  courseHoursCount: number
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
  /**
   * 主图
   */
  mainPicture: string
  /**
   *
   */
  productName: string
}

export interface OrderForm {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已支付；已完成)
   */
  status: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  orderDetails: OrderDetail[]
  /**
   *
   */
  coupons: UserCoupon[]
  /**
   *
   */
  refundAmount: number
  /**
   *
   */
  orderNumber: string
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 首次支付时间
   */
  firstPayTime: string
}

export interface UserCoupon {
  /**
   *
   */
  id: number
  /**
   *
   */
  userId: string
  /**
   *
   */
  userName: string
  /**
   *
   */
  couponId: number
  /**
   *
   */
  couponName: string
  /**
   *
   */
  couponPic: string
  /**
   *
   */
  couponThumbnail: string
  /**
   *
   */
  status: number
  /**
   *
   */
  useStatus: number
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  delFlag: number
  /**
   * 订单id
   */
  orderId: string
}

export interface OrderAmountDto {
  /**
   *
   */
  id: string
  /**
   *
   */
  payAmount: number
}

export interface CourseForm {
  /**
   *
   */
  id: string
  /**
   *
   */
  trialLessonId: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 开课人数
   */
  classCount: number
  /**
   * 课班数量
   */
  minClassCount: number
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 课程售价
   */
  price: number
  /**
   * 审核原因
   */
  auditReason: string
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 部门Fullid
   */
  treePath: string
  /**
   * 审核状态((1:已审核;0:待审核))
   */
  status: number
  /**
   * 逻辑删除标识(0:未删除;1:已删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   *
   */
  mainPicture: string
  /**
   *
   */
  publicityPictureUrls: string[]
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 城市名称
   */
  cityName: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 区县名称
   */
  countyName: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 区县名称
   */
  provinceName: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  /**
   *
   */
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  commissionRate: number
  /**
   * 新单佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  newCommissionRate: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 经度
   */
  longitude: string
  /**
   * 纬度
   */
  latitude: string
}

export interface RichTextForm {
  /**
   * 主键
   */
  id: number
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 图片url
   */
  mainPicture: string
  /**
   * 是否展示
   */
  isDisplay: number
}

export interface CourseVO {
  /**
   *
   */
  id: string
  /**
   *
   */
  name: string
}

export interface KsCustForm {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 用户账户
   */
  username: string
  /**
   * 用户密码
   */
  password: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 用户ID
   */
  userId: number
  /**
   *
   */
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  /**
   *
   */
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 性别 1 男  2 女
   */
  sex: boolean
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   * 积分
   */
  points: number
  /**
   *
   */
  courseId: string
  /**
   *
   */
  courseList: CourseVO[]
  /**
   *
   */
  addresList: string[]
  /**
   *
   */
  childNum: number
  /**
   * 邀请他人的邀请码
   */
  invitationCustCode: string
  /**
   *
   */
  invitationCust: string
  /**
   *
   */
  custId: string
  /**
   * 自身邀请码
   */
  invitationCode: string
  /**
   * 邀请时间
   */
  invitationTime: string
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
}

export interface KsCustQueryDto {
  /**
   *
   */
  parentId: string
}

export interface KsCustVO {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 用户账户
   */
  username: string
  /**
   * 用户密码
   */
  password: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 用户ID
   */
  userId: number
  /**
   *
   */
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  /**
   *
   */
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 性别 1 男  2 女
   */
  sex: boolean
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   *
   */
  courseId: string
  /**
   *
   */
  childNum: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createUserName: string
}

export interface ResultListKsCustVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: KsCustVO[]
  /**
   *
   */
  msg: string
}

export interface OpenIdQueryDto {
  /**
   *
   */
  code: string
  /**
   *
   */
  openId: string
  /**
   *
   */
  invitationCode: string
}

export interface CouponListQuery {
  /**
   *
   */
  userId: string
  /**
   *
   */
  courseId: string
  /**
   *
   */
  courseClassId: string
  /**
   *
   */
  orderAmount: number
  /**
   *
   */
  date: string
}

export interface WxPayReqParam {
  /**
   *
   */
  totalPrice: string
  /**
   *
   */
  goodsName: string
  /**
   *
   */
  orderNumber: string
  /**
   *
   */
  orderId: string
}

export interface WxPayRefundReqParam {
  /**
   *
   */
  transactionId: string
  /**
   *
   */
  refundMoney: string
  /**
   *
   */
  totalMoney: string
}

export interface AccountReqParam {
  /**
   * 订单ID
   */
  orderId: string
}

export interface InstitutionPaymentInfoVO {
  /**
   * 收款账户名
   */
  beneficiaryName: string
  /**
   * 收款账号
   */
  accountNumber: string
  /**
   * 收款银行
   */
  bankName: string
  /**
   * 收款二维码base64
   */
  paymentQrCode: string
  /**
   * 支付宝收款二维码base64
   */
  aliPaymentQrCode: string
  /**
   * 收款方式，具体枚举查看字典paymentType，wechat-微信收款码，alipay-支付宝收款码，bank-银行转账
   */
  paymentType: string
}

export interface ResultInstitutionPaymentInfoVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: InstitutionPaymentInfoVO
  /**
   *
   */
  msg: string
}

export interface UserPointsDetailQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 用户id
   */
  userId: string
  /**
   *
   */
  year: string
}

export interface ResultWechatUserPointDto {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: WechatUserPointDto
  /**
   *
   */
  msg: string
}

export interface UserPointsDetail {
  /**
   *
   */
  id: number
  /**
   *
   */
  userId: string
  /**
   *
   */
  userName: string
  /**
   *
   */
  type: number
  /**
   *
   */
  points: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  delFlag: number
  /**
   *
   */
  amount: number
  /**
   *
   */
  pointDesc: string
}

export interface WechatUserPointDto {
  /**
   *
   */
  points: number
  /**
   *
   */
  consumeRatio: number
  /**
   *
   */
  detailList: UserPointsDetail[]
}

export interface DataUserPointsDetailVO {
  /**
   *
   */
  list: UserPointsDetailVO[]
  /**
   *
   */
  total: number
}

export interface PageResultUserPointsDetailVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataUserPointsDetailVO
  /**
   *
   */
  msg: string
}

export interface UserPointsDetailVO {
  /**
   * 用户积分明细ID
   */
  id: number
  /**
   * 用户id
   */
  userId: number
  /**
   * 用户姓名
   */
  userName: string
  /**
   * 增加/兑换（1增加 2兑换）
   */
  type: number
  /**
   * 操作积分数
   */
  points: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
}

export interface BasePageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
}

export interface DataTeacherInfo {
  /**
   *
   */
  list: TeacherInfo[]
  /**
   *
   */
  total: number
}

export interface PageResultTeacherInfo {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataTeacherInfo
  /**
   *
   */
  msg: string
}

export interface TeacherInfo {
  /**
   *
   */
  id: string
  /**
   *
   */
  userId: string
  /**
   *
   */
  name: string
  /**
   *
   */
  displayName: string
  /**
   *
   */
  englishName: string
  /**
   *
   */
  nationality: string
  /**
   *
   */
  location: string
  /**
   *
   */
  avatarUrl: string
  /**
   *
   */
  gender: string
  /**
   *
   */
  age: number
  /**
   *
   */
  teachingExperience: number
  /**
   *
   */
  birthday: string
  /**
   *
   */
  institutionId: number
  /**
   *
   */
  graduationSchool: string
  /**
   *
   */
  highestDegree: string
  /**
   *
   */
  major: string
  /**
   *
   */
  slogan: string
  /**
   *
   */
  experience: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  delFlag: number
  /**
   *
   */
  sortNumber: number
  /**
   *
   */
  trialLessonId: string
  /**
   *
   */
  isShowExcellent: number
  /**
   *
   */
  tag: string
  /**
   *
   */
  evaluation: number
  /**
   *
   */
  mark: string
}

export interface ProofMaterialsForm {
  /**
   * 身份证正反面列表
   */
  idCards: string[]
  /**
   * 社会保障卡，驾照或护照列表
   */
  socialProofMaterials: string[]
  /**
   * 学历证明列表
   */
  degreeCertificates: string[]
}

export interface TeacherEducationBackgroundForm {
  /**
   * 学校名称
   */
  schoolName: string
  /**
   * 所在国家
   */
  country: string
  /**
   * 专业名称
   */
  major: string
  /**
   * 学历
   */
  degree: string
  /**
   * 学习开始时间
   */
  studyStartDate: string
  /**
   * 学习结束时间
   */
  studyEndDate: string
}

export interface TeacherExperienceForm {
  /**
   * 职务名称
   */
  jobTitle: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 在职开始日期
   */
  startDay: string
  /**
   * 在职结束日期
   */
  endDay: string
  /**
   * 教学内容
   */
  teachingContent: string
  /**
   * 获得成就奖项
   */
  achievements: string
}

export interface TeacherInfoForm {
  /**
   *
   */
  id: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 宣传语
   */
  slogan: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 备注信息
   */
  mark: string
  /**
   * 讲师标签
   */
  tag: string
  /**
   *
   */
  proofMaterials: ProofMaterialsForm
  /**
   *
   */
  introduction: TeacherIntroductionForm
  /**
   * 教育履历
   */
  experience: string
  /**
   * 教育履历
   */
  experienceList: TeacherExperienceForm[]
  /**
   * 教育背景列表
   */
  educationBackgroundList: TeacherEducationBackgroundForm[]
}

export interface TeacherIntroductionForm {
  /**
   * 详细介绍
   */
  detailedIntroduction: string
  /**
   * 视频介绍地址
   */
  videoIntroductionUrl: string
}

export interface TeacherSortNumberForm {
  /**
   * 要更新的讲师id
   */
  id: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
}

export interface PointRuleForm {
  /**
   * 积分规则ID
   */
  id: number
  /**
   * 规则名称
   */
  ruleName: string
  /**
   * 积分增加比例
   */
  pointAddRatio: number
  /**
   * 积分兑换比例
   */
  pointRedemptionRatio: number
  /**
   * 积分有效时长(分钟)
   */
  ruleValidit: number
  /**
   * 是否启用(0否 1是)
   */
  ruleStatus: number
}

export interface ConfirmPaymentReqParam {
  /**
   * 订单ID
   */
  orderId: string
}

export interface LevelRuleForm {
  /**
   * 会员等级规则ID
   */
  id: number
  /**
   * 等级
   */
  level: number
  /**
   * 等级名称
   */
  levelName: string
  /**
   * 等级积分
   */
  levelRule: number
  /**
   * 邀请加分比例
   */
  invitedRatio: number
  /**
   * 消费加分比例
   */
  consumeRatio: number
  /**
   * 积分兑换比例
   */
  exchangeRatio: number
  /**
   * 积分有效时长(天)
   */
  duration: number
  /**
   * 会员折扣
   */
  discount: number
}

export interface FeedbackForm {
  /**
   * 主键
   */
  id: number
  /**
   * 意见反馈
   */
  feedbackContent: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeName: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeCode: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人ID
   */
  createUserName: string
}

export interface UserCouponDto {
  /**
   *
   */
  userId: string
  /**
   *
   */
  idList: number[]
}

export interface TeacherCollection {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: number
  /**
   *
   */
  userId: string
  /**
   *
   */
  teacherId: string
}

export interface StudentCourseOperationForm {
  /**
   * 学生id
   */
  studentId: string
  /**
   * 约课明细ID
   */
  detailId: string
}

export interface CourseBookingForm {
  /**
   * 学生id
   */
  studentId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课时id列表
   */
  scheduleId: number
}

export interface OrderCourseBindForm {
  /**
   * 学生id
   */
  studentId: string
  /**
   * 主键
   */
  id: string
}

export interface CalculatePricedDto {
  /**
   *
   */
  courseId: string
  /**
   *
   */
  courseCount: number
  /**
   *
   */
  price: number
  /**
   * 如果多个优惠券用,隔开
   */
  couponId: string
}

export interface OrderDetailBO {
  /**
   *
   */
  id: string
  /**
   *
   */
  productId: number
  /**
   *
   */
  productCount: number
  /**
   *
   */
  courseHoursCount: number
  /**
   *
   */
  courseId: string
  /**
   *
   */
  orderId: string
  /**
   *
   */
  productPrice: number
  /**
   *
   */
  productAmount: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
  /**
   *
   */
  courseNames: string
  /**
   *
   */
  productName: string
  /**
   * 主图
   */
  mainPicture: string
}

export interface WechatOrderForm {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已支付；已完成)
   */
  status: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  orderDetails: OrderDetailBO[]
  /**
   *
   */
  coupons: UserCoupon[]
  /**
   *
   */
  refundAmount: number
}

export interface ConsumptionRecordsDetailDto {
  /**
   *
   */
  courseName: string
  /**
   *
   */
  courseCount: number
}

export interface ConsumptionRecordsDto {
  /**
   *
   */
  payAmount: number
  /**
   *
   */
  orderTime: string
  /**
   *
   */
  id: string
  /**
   *
   */
  list: ConsumptionRecordsDetailDto[]
}

export interface DataConsumptionRecordsDto {
  /**
   *
   */
  list: ConsumptionRecordsDto[]
  /**
   *
   */
  total: number
}

export interface PageResultConsumptionRecordsDto {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataConsumptionRecordsDto
  /**
   *
   */
  msg: string
}

export interface TeacherInfoQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 关键词，支持姓名和简介
   */
  keys: string
  /**
   * 讲师标签
   */
  tags: string[]
}

export interface ExcellentTeacherQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 备注信息
   */
  addressLike: string
}

export interface ResultSysAttachment {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: SysAttachment
  /**
   *
   */
  msg: string
}

export interface SysAttachment {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: string
  /**
   *
   */
  fileName: string
  /**
   *
   */
  fileSuffix: string
  /**
   *
   */
  absolutePath: string
  /**
   *
   */
  fileSize: string
  /**
   *
   */
  webPath: string
  /**
   *
   */
  businessId: string
  /**
   *
   */
  createBy: number
  /**
   *
   */
  updateBy: number
  /**
   *
   */
  businessColumn: string
}

export interface ShelvesProductDto {
  /**
   *
   */
  id: string
  /**
   *
   */
  status: number
}

export interface CourseCollection {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: number
  /**
   *
   */
  userId: string
  /**
   *
   */
  courseId: string
}

export interface CourseClassificationForm {
  /**
   *
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 状态 1启用 0停用
   */
  status: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  createUser: number
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  updateUser: number
  /**
   * 组织id
   */
  deptId: number
  /**
   * 是否标签 0 否 1 是
   */
  labelIdentification: number
  /**
   * 组织全量
   */
  deptFullId: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 排序号
   */
  sort: number
}

export interface CourseClassificationPageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 分类名称
   */
  name: string
  /**
   * 分类名称
   */
  keywords: string
  /**
   * 状态 1启用 0停用
   */
  status: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * 多个名称用，隔开
   */
  parentName: string
  /**
   * 多个名称用，隔开
   */
  names: string
  queryParent:number
  /**
   * 是否需要全部  0 不需要 1需要 默认不需要
   */
  needAll: string
  /**
   *
   */
  nameList: string[]
}

export interface CourseClassificationVO {
  /**
   *
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 子部门
   */
  children: CourseClassificationVO[]
  /**
   * 状态 1启用 0停用
   */
  status: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  createUser: number
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  updateUser: number
  /**
   * 组织id
   */
  deptId: number
  /**
   * 是否标签 0 否 1 是
   */
  labelIdentification: number
  /**
   * 组织全量
   */
  deptFullId: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 排序号
   */
  sort: number
}

export interface ResultListCourseClassificationVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseClassificationVO[]
  /**
   *
   */
  msg: string
}

export interface CountryAreaPageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 分类名称
   */
  name: string
  /**
   * 分类名称
   */
  keywords: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 多个名称用，隔开
   */
  parentName: string
  /**
   * 多个名称用，隔开
   */
  names: string
}

export interface CountryAreaVO {
  /**
   * id
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 编辑人姓名
   */
  updateUserName: string
  /**
   * 子部门
   */
  children: CountryAreaVO[]
}

export interface ResultListCountryAreaVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CountryAreaVO[]
  /**
   *
   */
  msg: string
}

export interface BaseQueryDto {
  /**
   *
   */
  ids: string[]
}

export interface CityEntity {
  /**
   *
   */
  id: string
  /**
   *
   */
  cityName: string
  /**
   *
   */
  cityShortName: string
  /**
   *
   */
  cityMergeName: string
  /**
   *
   */
  cityPinyin: string
  /**
   *
   */
  cityLng: number
  /**
   *
   */
  cityLat: number
  /**
   *
   */
  cityLevel: number
  /**
   *
   */
  parentId: string
  /**
   *
   */
  treePath: string
  /**
   *
   */
  cityState: number
  /**
   *
   */
  cityCode: string
}

export interface LoginResult {
  /**
   * 访问token
   */
  accessToken: string
  /**
   * token 类型
   */
  tokenType: string
  /**
   * 刷新token
   */
  refreshToken: string
  /**
   * 过期时间(单位：毫秒)
   */
  expires: number
}

export interface ResultLoginResult {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: LoginResult
  /**
   *
   */
  msg: string
}

export interface CourseSortNumberForm {
  /**
   * 要更新的讲师id
   */
  id: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
}

export interface CourseAuditRecord {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: number
  /**
   *
   */
  courseId: string
  /**
   *
   */
  auditReason: string
  /**
   *
   */
  auditStatus: number
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createUserName: string
}

export interface ResultBoolean {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: boolean
  /**
   *
   */
  msg: string
}

export interface CourseScheduleAddForm {
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 课程排班信息列表
   */
  schedules: CourseScheduleForm[]
}

export interface CourseScheduleForm {
  /**
   * 课程授课类型，oneByOne 一对一，bigCourse 大课
   */
  type: string
  /**
   * 课时id
   */
  scheduleId: number
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 预约状态
   */
  bookingStatus: string
  /**
   * 授课状态
   */
  teachingStatus: string
  /**
   * 课程主表id，如果学生约课就有该记录
   */
  courseId: string
  /**
   * 课程名称，如果学生约课就有该记录
   */
  courseName: string
  /**
   * 课程约课学生信息
   */
  students: CourseScheduleStudentForm[]
}

export interface CourseScheduleStudentForm {
  /**
   * 学生id，如果学生约课就有该记录
   */
  studentId: string
  /**
   * 课程名称，如果学生约课就有该记录
   */
  studentName: string
  /**
   *
   */
  bookingStatus: string
}

export interface StudentBookingForm {
  /**
   * 主键
   */
  id: number
  /**
   * 学生id
   */
  studentId: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师id对应的姓名
   */
  selectedTeacherName: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 机构id
   */
  institutionId: string
  /**
   * 机构id对应的机构名称
   */
  selectedInstitutionName: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id对应的课程名称
   */
  selectedCourseName: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 背景颜色
   */
  background: string
  /**
   * 上课地点
   */
  location: string
  /**
   * 备注
   */
  remark: string
}

export interface ServedCustomerForm {
  /**
   * id
   */
  id: number
  /**
   * 服务过的客户中文名
   */
  chineseName: string
  /**
   * 服务过的客户英文名
   */
  englishName: string
  /**
   * logo地址
   */
  logoUrl: string
}

export interface SchoolForm {
  /**
   * id
   */
  id: number
  /**
   * 学校中文名
   */
  chineseName: string
  /**
   * 学校英文名
   */
  englishName: string
  /**
   * logo地址
   */
  logoUrl: string
}

export interface CustGoldDto {
  /**
   *
   */
  id: string
  /**
   *
   */
  addGold: number
}

export interface CustCouponQueryDto {
  /**
   *
   */
  couponIds: string[]
  /**
   *
   */
  id: string
}

export interface KsCustDistributionQuery {
  /**
   * 待分配的用户
   */
  id: string
  /**
   * 待分配的用户的父级id
   */
  parentId: string
  /**
   * 分配的后台管理人员
   */
  userIds: string
}

export interface KsCustChannelChangeDto {
  /**
   * 会员账号id
   */
  id: string
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
}

export interface KsCustAttachDto {
  /**
   * 目标父账号id
   */
  targetId: string
  /**
   * 待挂靠的会员id，挂靠后成为子账号
   */
  toAttachId: string
}

export interface ResultKsCustForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: KsCustForm
  /**
   *
   */
  msg: string
}

export interface KsCust {
  /**
   *
   */
  id: string
  /**
   *
   */
  avatar: string
  /**
   *
   */
  nickname: string
  /**
   *
   */
  username: string
  /**
   *
   */
  password: string
  /**
   *
   */
  realName: string
  /**
   *
   */
  gender: string
  /**
   *
   */
  mark: string
  /**
   *
   */
  parentId: string
  /**
   *
   */
  userId: number
  /**
   *
   */
  registerFrom: string
  /**
   *
   */
  phone: string
  /**
   *
   */
  balance: number
  /**
   *
   */
  goldBalance: number
  /**
   *
   */
  integralBalance: number
  /**
   *
   */
  status: boolean
  /**
   *
   */
  preferenceColor: string
  /**
   *
   */
  familyMemberCount: number
  /**
   *
   */
  addres: string
  /**
   *
   */
  wxProfile: string
  /**
   *
   */
  deleted: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  birthday: string
  /**
   *
   */
  level: number
  /**
   *
   */
  points: number
  /**
   *
   */
  effectivePoints: number
  /**
   *
   */
  availablePoints: number
  /**
   *
   */
  expiredPoints: number
  /**
   *
   */
  usedPoints: number
  /**
   *
   */
  openId: string
  /**
   *
   */
  sex: boolean
  /**
   *
   */
  hobbies: string
  /**
   *
   */
  courses: string
  /**
   *
   */
  courseId: string
  /**
   *
   */
  childNum: number
  /**
   *
   */
  invitationCode: string
  /**
   *
   */
  invitationCust: string
  /**
   *
   */
  custId: string
  /**
   * 邀请时间
   */
  invitationTime: string
  /**
   *
   */
  channel: string
  /**
   *
   */
  managerPerson: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createUserName: string
}

export interface ResultListKsCust {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: KsCust[]
  /**
   *
   */
  msg: string
}

export interface ResultCouponForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CouponForm
  /**
   *
   */
  msg: string
}

export interface DataWechatUserCouponDTO {
  /**
   *
   */
  list: WechatUserCouponDTO[]
  /**
   *
   */
  total: number
}

export interface PageResultWechatUserCouponDTO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataWechatUserCouponDTO
  /**
   *
   */
  msg: string
}

export interface WechatUserCouponDTO {
  /**
   *
   */
  id: number
  /**
   *
   */
  userId: string
  /**
   *
   */
  userName: string
  /**
   *
   */
  couponId: number
  /**
   *
   */
  couponName: string
  /**
   *
   */
  couponPic: string
  /**
   *
   */
  couponThumbnail: string
  /**
   *
   */
  status: number
  /**
   *
   */
  useStatus: number
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  delFlag: number
  /**
   * 订单id
   */
  orderId: string
  /**
   *
   */
  limitUsageEndTime: string
  /**
   *
   */
  limitUsageStartTime: string
  /**
   *
   */
  useScope: number
  /**
   *
   */
  receiveType: number
  /**
   *
   */
  deductionAmount: number
  /**
   *
   */
  businessNames: string
  /**
   *
   */
  type: number
  /**
   *
   */
  remark: string
}

export interface CouponPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 使用限制类型(1:限制使用时间;0:限制使用天数)
   */
  useRestrictedType: number
  /**
   * 满足优惠金额
   */
  amountMet: number
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  /**
   * 可用课程
   */
  courseId: string
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 修改人ID
   */
  updateBy: number
  /**
   *
   */
  deptId: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
}

export interface DataCouponPageVO {
  /**
   *
   */
  list: CouponPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCouponPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCouponPageVO
  /**
   *
   */
  msg: string
}

export interface ResultTeacherInfoForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: TeacherInfoForm
  /**
   *
   */
  msg: string
}

export interface ResultListTeacherInfo {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: TeacherInfo[]
  /**
   *
   */
  msg: string
}

export interface DataTeacherOptionsItemVO {
  /**
   *
   */
  list: TeacherOptionsItemVO[]
  /**
   *
   */
  total: number
}

export interface PageResultTeacherOptionsItemVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataTeacherOptionsItemVO
  /**
   *
   */
  msg: string
}

export interface TeacherOptionsItemVO {
  /**
   * 讲师id
   */
  id: string
  /**
   * 讲师的用户id，可用于登陆后台系统
   */
  userId: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
}

export interface DataTeacherInfoVO {
  /**
   *
   */
  list: TeacherInfoVO[]
  /**
   *
   */
  total: number
}

export interface PageResultTeacherInfoVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataTeacherInfoVO
  /**
   *
   */
  msg: string
}

export interface TeacherInfoVO {
  /**
   * 讲师id
   */
  id: string
  /**
   * 讲师的用户id，可用于登陆后台系统
   */
  userId: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 年龄
   */
  age: number
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人
   */
  createUserName: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新人
   */
  updateUser: string
  /**
   * 更新人
   */
  updateUserName: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 讲师标签
   */
  tag: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 备注信息
   */
  mark: string
}

export interface ResultListServedCustomerForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: ServedCustomerForm[]
  /**
   *
   */
  msg: string
}

export interface DataSchoolForm {
  /**
   *
   */
  list: SchoolForm[]
  /**
   *
   */
  total: number
}

export interface PageResultSchoolForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataSchoolForm
  /**
   *
   */
  msg: string
}

export interface ResultRichTextForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: RichTextForm
  /**
   *
   */
  msg: string
}

export interface DataRichTextSimplePageVO {
  /**
   *
   */
  list: RichTextSimplePageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultRichTextSimplePageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataRichTextSimplePageVO
  /**
   *
   */
  msg: string
}

export interface RichTextSimplePageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 图片url
   */
  mainPicture: string
}

export interface DataPointsRulesVO {
  /**
   *
   */
  list: PointsRulesVO[]
  /**
   *
   */
  total: number
}

export interface PageResultPointsRulesVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataPointsRulesVO
  /**
   *
   */
  msg: string
}

export interface PointsRulesVO {
  /**
   * 积分规则ID
   */
  id: number
  /**
   * 积分规则名称
   */
  ruleName: string
  /**
   * 积分增加比例
   */
  pointAddRatio: number
  /**
   * 积分兑换比例
   */
  pointRedemptionRatio: number
  /**
   * 积分有效时长(分钟)
   */
  ruleValidit: number
  /**
   * 是否启用(0否 1是)
   */
  ruleStatus: number
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
}

export interface DataMemberRuleVO {
  /**
   *
   */
  list: MemberRuleVO[]
  /**
   *
   */
  total: number
}

export interface MemberRuleVO {
  /**
   * 会员等级规则ID
   */
  id: number
  /**
   * 会员等级规则ID
   */
  level: number
  /**
   * 会员等级名称
   */
  levelName: string
  /**
   * 会员等级规则ID
   */
  levelRule: number
  /**
   * 邀请加分比例
   */
  invitedRatio: number
  /**
   * 消费加分比例
   */
  consumeRatio: number
  /**
   * 积分兑换比例
   */
  exchangeRatio: number
  /**
   * 积分有效时长(天)
   */
  duration: number
  /**
   * 会员折扣
   */
  discount: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
}

export interface PageResultMemberRuleVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataMemberRuleVO
  /**
   *
   */
  msg: string
}

export interface ResultCourseEvaluationForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseEvaluationForm
  /**
   *
   */
  msg: string
}

export interface CourseEvaluationPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 用户头像
   */
  avatar: string
}

export interface DataCourseEvaluationPageVO {
  /**
   *
   */
  list: CourseEvaluationPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCourseEvaluationPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCourseEvaluationPageVO
  /**
   *
   */
  msg: string
}

export interface ResultUserForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: UserForm
  /**
   *
   */
  msg: string
}

export interface DataUserPageVO {
  /**
   *
   */
  list: UserPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultUserPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataUserPageVO
  /**
   *
   */
  msg: string
}

export interface UserPageVO {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 手机号
   */
  mobile: string
  /**
   * 性别
   */
  genderLabel: string
  /**
   * 用户头像地址
   */
  avatar: string
  /**
   * 用户邮箱
   */
  email: string
  /**
   * 用户状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 部门名称
   */
  deptName: string
  /**
   * 角色名称，多个使用英文逗号(,)分割
   */
  roleNames: string
  /**
   * 创建时间
   */
  createTime: string
}

export interface ResultUserInfoVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: UserInfoVO
  /**
   *
   */
  msg: string
}

export interface UserDeptVO {
  /**
   * 部门或机构id，根据isInstitution而定
   */
  id: number
  /**
   * 部门或机构名称，根据isInstitution而定
   */
  name: string
  /**
   * 是否机构
   */
  isInstitution: boolean
}

export interface UserInfoVO {
  /**
   * 用户ID
   */
  userId: string
  /**
   * 用户名
   */
  username: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 头像地址
   */
  avatar: string
  /**
   * 用户角色编码集合
   */
  roles: string[]
  /**
   * 用户权限标识集合
   */
  perms: string[]
  /**
   *
   */
  dept: UserDeptVO
}

export interface ResultUserOrderCourseForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: UserOrderCourseForm
  /**
   *
   */
  msg: string
}

export interface DataUserOrderCoursePageVO {
  /**
   *
   */
  list: UserOrderCoursePageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultUserOrderCoursePageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataUserOrderCoursePageVO
  /**
   *
   */
  msg: string
}

export interface UserOrderCoursePageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 产品id
   */
  productId: number
  /**
   * 课程数量
   */
  productCount: number
  /**
   * 订单表id
   */
  orderId: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课时数量
   */
  courseCount: number
  /**
   * 已上数量
   */
  attendedCount: number
  /**
   * 已预约数量
   */
  appointmentCount: number
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 课程单价
   */
  productPrice: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 下单时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 下单人姓名
   */
  userName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
}

export interface ResultListStudentBookingForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: StudentBookingForm[]
  /**
   *
   */
  msg: string
}

export interface ResultListStudentScheduleMouthCountVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: StudentScheduleMouthCountVO[]
  /**
   *
   */
  msg: string
}

export interface StudentScheduleMouthCountVO {
  /**
   * 日期（格式：YYYY-MM-DD）
   */
  date: string
  /**
   * 对应日期的次数
   */
  count: number
}

export interface DataStudentOrderCoursePageVO {
  /**
   *
   */
  list: StudentOrderCoursePageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultStudentOrderCoursePageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataStudentOrderCoursePageVO
  /**
   *
   */
  msg: string
}

export interface StudentCourseDetailSlotVO {
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
}

export interface StudentOrderCoursePageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 产品id
   */
  productId: number
  /**
   * 课程数量
   */
  productCount: number
  /**
   * 订单表id
   */
  orderId: string
  /**
   * 用户id
   */
  userId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 课程封面
   */
  coursePicture: string
  /**
   * 课时数量
   */
  courseCount: number
  /**
   * 已上数量
   */
  attendedCount: number
  /**
   * 已预约数量
   */
  appointmentCount: number
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 下单时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 讲师id
   */
  studentId: string
  /**
   * 讲师姓名
   */
  studentName: string
  /**
   * 学习状态
   */
  learnStatus: string
  /**
   *
   */
  lastCourse: StudentCourseDetailSlotVO
}

export interface CourseAvailVO {
  /**
   * 约课明细编号
   */
  scheduleId: number
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 预约状态，INIT-未预约，BOOKED-已预约
   */
  bookingStatus: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
}

export interface ResultListCourseAvailVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseAvailVO[]
  /**
   *
   */
  msg: string
}

export interface ResultListStudentCourseDetailVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: StudentCourseDetailVO[]
  /**
   *
   */
  msg: string
}

export interface StudentCourseDetailVO {
  /**
   * 课时id
   */
  scheduleId: string
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 约课状态，参考字典courseBookingStatus
   */
  bookingStatus: string
  /**
   * 教师授课状态，参考字典teachingStatus
   */
  teachingStatus: string
  /**
   *
   */
  evaluationId: string
}

export interface ResultShoppingCartsForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: ShoppingCartsForm
  /**
   *
   */
  msg: string
}

export interface DataShoppingCartsPageVO {
  /**
   *
   */
  list: ShoppingCartsPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultShoppingCartsPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataShoppingCartsPageVO
  /**
   *
   */
  msg: string
}

export interface ShoppingCartsPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 产品id
   */
  productId: number
  /**
   * 产品数量
   */
  productCount: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 产品名称
   */
  productName: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 组织id
   */
  deptId: number
  /**
   * 组织名称
   */
  deptName: string
  /**
   * 产品价格
   */
  price: string
}

export interface ResultRotationChartForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: RotationChartForm
  /**
   *
   */
  msg: string
}

export interface DataRotationChartPageVO {
  /**
   *
   */
  list: RotationChartPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultRotationChartPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataRotationChartPageVO
  /**
   *
   */
  msg: string
}

export interface RotationChartPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 活动名称
   */
  name: string
  /**
   * 轮播图
   */
  bannerPicture: string
  /**
   * 跳转地址
   */
  jumpUrl: string
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 状态(1:启用;0:停用)
   */
  status: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 类型编码
   */
  typeCode: string
  /**
   * 类型名称
   */
  typeName: string
}

export interface ResultListRotationChart {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: RotationChart[]
  /**
   *
   */
  msg: string
}

export interface RotationChart {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: string
  /**
   *
   */
  name: string
  /**
   *
   */
  bannerPicture: string
  /**
   *
   */
  jumpUrl: string
  /**
   *
   */
  sort: number
  /**
   *
   */
  status: number
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateUser: string
  /**
   * 类型编码
   */
  typeCode: string
  /**
   * 类型名称
   */
  typeName: string
}

export interface ResultListLong {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: number[]
  /**
   *
   */
  msg: string
}

export interface ResultRoleForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: RoleForm
  /**
   *
   */
  msg: string
}

export interface DataRolePageVO {
  /**
   *
   */
  list: RolePageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultRolePageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataRolePageVO
  /**
   *
   */
  msg: string
}

export interface RolePageVO {
  /**
   * 角色ID
   */
  id: number
  /**
   * 角色名称
   */
  name: string
  /**
   * 角色编码
   */
  code: string
  /**
   * 角色状态
   */
  status: number
  /**
   * 排序
   */
  sort: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
}

export interface Option {
  /**
   * 选项的值
   */
  value: IObject
  /**
   * 选项的标签
   */
  label: string
}

export interface OptionObject {
  /**
   * 选项的值
   */
  value: IObject
  /**
   * 选项的标签
   */
  label: string
  /**
   * 子选项列表
   */
  children: Option[]
}

export interface ResultListOptionObject {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: OptionObject[]
  /**
   *
   */
  msg: string
}

export interface ResultOrderForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: OrderForm
  /**
   *
   */
  msg: string
}

export interface DataWechatOrderDto {
  /**
   *
   */
  list: WechatOrderDto[]
  /**
   *
   */
  total: number
}

export interface PageResultWechatOrderDto {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataWechatOrderDto
  /**
   *
   */
  msg: string
}

export interface WechatOrderDto {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已完成；3.待退款 4已取消)
   */
  status: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   *
   */
  refundAmount: number
  /**
   *
   */
  orderNumber: string
  /**
   *
   */
  orderDetails: OrderDetail[]
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
}

export interface MenuVO {
  /**
   * 菜单ID
   */
  id: number
  /**
   * 父菜单ID
   */
  parentId: number
  /**
   * 菜单名称
   */
  name: string
  /**
   * 菜单类型
   */
  type: string
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径
   */
  component: string
  /**
   * 菜单排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 菜单是否可见(1:显示;0:隐藏)
   */
  visible: number
  /**
   * ICON
   */
  icon: string
  /**
   * 跳转路径
   */
  redirect: string
  /**
   * 按钮权限标识
   */
  perm: string
  /**
   * 子菜单
   */
  children: MenuVO[]
}

export interface ResultListMenuVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: MenuVO[]
  /**
   *
   */
  msg: string
}

export interface ResultMenuForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: MenuForm
  /**
   *
   */
  msg: string
}

export interface Meta {
  /**
   * 路由title
   */
  title: string
  /**
   * ICON
   */
  icon: string
  /**
   * 是否隐藏(true-是 false-否)
   */
  hidden: boolean
  /**
   * 拥有路由权限的角色编码
   */
  roles: string[]
  /**
   * 【菜单】是否开启页面缓存
   */
  keepAlive: boolean
  /**
   * 【目录】只有一个子路由是否始终显示
   */
  alwaysShow: boolean
  /**
   * 路由参数
   */
  params: IObject
}

export interface ResultListRouteVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: RouteVO[]
  /**
   *
   */
  msg: string
}

export interface RouteVO {
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径
   */
  component: string
  /**
   * 跳转链接
   */
  redirect: string
  /**
   * 路由名称
   */
  name: string
  /**
   *
   */
  meta: Meta
  /**
   * 子路由列表
   */
  children: RouteVO[]
}

export interface ResultTeacherInfoDto {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: TeacherInfoDto
  /**
   *
   */
  msg: string
}

export interface TeacherInfoDto {
  /**
   *
   */
  id: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 宣传语
   */
  slogan: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 备注信息
   */
  mark: string
  /**
   * 讲师标签
   */
  tag: string
  /**
   *
   */
  proofMaterials: ProofMaterialsForm
  /**
   *
   */
  introduction: TeacherIntroductionForm
  /**
   * 教育履历
   */
  experience: string
  /**
   * 教育履历
   */
  experienceList: TeacherExperienceForm[]
  /**
   * 教育背景列表
   */
  educationBackgroundList: TeacherEducationBackgroundForm[]
  /**
   *
   */
  evaluation: number
}

export interface DataTeacherCourseVO {
  /**
   *
   */
  list: TeacherCourseVO[]
  /**
   *
   */
  total: number
}

export interface PageResultTeacherCourseVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataTeacherCourseVO
  /**
   *
   */
  msg: string
}

export interface TeacherCourseVO {
  /**
   * 主键id
   */
  id: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 课程图片url
   */
  mainPicture: string
}

export interface InstitutionVO {
  /**
   * 机构ID
   */
  id: number
  /**
   * 机构名称
   */
  name: string
  /**
   * 机构代号
   */
  institutionCode: string
  /**
   * 排序
   */
  sort: number
  /**
   * 管理者id，可用于登陆
   */
  adminId: string
  /**
   * 状态(1:启用；0:禁用)
   */
  status: number
  /**
   * 详细地址
   */
  address: string
  /**
   * 类别，列表，上传字典institutionType的值
   */
  types: string[]
  /**
   * 简介
   */
  introduction: string
  /**
   * 图文详情
   */
  detail: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 修改时间
   */
  updateTime: string
}

export interface ResultListInstitutionVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: InstitutionVO[]
  /**
   *
   */
  msg: string
}

export interface ResultInstitutionForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: InstitutionForm
  /**
   *
   */
  msg: string
}

export interface ResultHotWordRecordForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: HotWordRecordForm
  /**
   *
   */
  msg: string
}

export interface DataHotWordRecordPageVO {
  /**
   *
   */
  list: HotWordRecordPageVO[]
  /**
   *
   */
  total: number
}

export interface HotWordRecordPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 热词
   */
  name: string
  /**
   * 显示顺序
   */
  count: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
}

export interface PageResultHotWordRecordPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataHotWordRecordPageVO
  /**
   *
   */
  msg: string
}

export interface ResultDictForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DictForm
  /**
   *
   */
  msg: string
}

export interface ResultDictTypeForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DictTypeForm
  /**
   *
   */
  msg: string
}

export interface DataDictTypePageVO {
  /**
   *
   */
  list: DictTypePageVO[]
  /**
   *
   */
  total: number
}

export interface DictTypePageVO {
  /**
   * 字典类型ID
   */
  id: number
  /**
   * 类型名称
   */
  name: string
  /**
   * 类型编码
   */
  code: string
  /**
   * 状态：1:启用;0:禁用
   */
  status: number
}

export interface PageResultDictTypePageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataDictTypePageVO
  /**
   *
   */
  msg: string
}

export interface DataDictPageVO {
  /**
   *
   */
  list: DictPageVO[]
  /**
   *
   */
  total: number
}

export interface DictPageVO {
  /**
   * 字典ID
   */
  id: number
  /**
   * 字典名称
   */
  name: string
  /**
   * 字典值
   */
  value: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
}

export interface PageResultDictPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataDictPageVO
  /**
   *
   */
  msg: string
}

export interface DeptVO {
  /**
   * 部门ID
   */
  id: number
  /**
   * 父部门ID
   */
  parentId: number
  /**
   * 部门名称
   */
  name: string
  /**
   * 排序
   */
  sort: number
  /**
   * 状态(1:启用；0:禁用)
   */
  status: number
  /**
   * 子部门
   */
  children: DeptVO[]
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 修改时间
   */
  updateTime: string
}

export interface ResultListDeptVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DeptVO[]
  /**
   *
   */
  msg: string
}

export interface ResultDeptForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DeptForm
  /**
   *
   */
  msg: string
}

export interface ResultCourseForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseForm
  /**
   *
   */
  msg: string
}

export interface Course {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: string
  /**
   *
   */
  name: string
  /**
   *
   */
  ageRangeCode: string
  /**
   *
   */
  suitAgeStart: number
  /**
   *
   */
  suitAgeEnd: number
  /**
   *
   */
  teacherId: string
  /**
   *
   */
  teacherName: string
  /**
   *
   */
  classHourseNumber: number
  /**
   *
   */
  teachLanguageCode: string
  /**
   *
   */
  teachWayCode: string
  /**
   *
   */
  classCount: number
  /**
   *
   */
  minClassCount: number
  /**
   *
   */
  otherInstructions: string
  /**
   *
   */
  specialLabel: string
  /**
   *
   */
  teachingCharacteristics: string
  /**
   *
   */
  courseFeatures: string
  /**
   *
   */
  courseDescription: string
  /**
   *
   */
  startTime: string
  /**
   *
   */
  courseClassificationId: string
  /**
   *
   */
  goldContent: number
  /**
   *
   */
  comprehensiveEvaluation: number
  /**
   *
   */
  price: number
  /**
   *
   */
  commissionRate: number
  /**
   *
   */
  newCommissionRate: number
  /**
   *
   */
  institutionId: number
  /**
   *
   */
  deptId: number
  /**
   *
   */
  treePath: string
  /**
   *
   */
  status: number
  /**
   *
   */
  deleted: number
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   *
   */
  publicityPicture: string
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   *
   */
  studentsNumber: number
  /**
   *
   */
  sortNumber: number
  /**
   *
   */
  trialLessonId: string
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   *
   */
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   *
   */
  longitude: string
  /**
   *
   */
  latitude: string
  /**
   *
   */
  mark: string
}

export interface DataCourse {
  /**
   *
   */
  list: Course[]
  /**
   *
   */
  total: number
}

export interface PageResultCourse {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCourse
  /**
   *
   */
  msg: string
}

export interface ResultCourseProductForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseProductForm
  /**
   *
   */
  msg: string
}

export interface CourseProductPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 课程产品名称
   */
  name: string
  /**
   * 组织id
   */
  deptId: number
  /**
   * 父节点id路径
   */
  treePath: string
  /**
   * 产品类型  1 单个产品  2组合产品
   */
  productType: number
  /**
   * 状态(1:上架;0:下架)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: number
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 修改人ID
   */
  updateUser: number
  /**
   * 创建人名称
   */
  updateUserName: string
  /**
   * 产品价格
   */
  price: string
  /**
   *
   */
  courseClassificationNames: string
  /**
   *
   */
  mainPicture: string
  /**
   * 会员ID
   */
  userId: string
  /**
   * 会员名称
   */
  userName: string
}

export interface DataCourseProductPageVO {
  /**
   *
   */
  list: CourseProductPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCourseProductPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCourseProductPageVO
  /**
   *
   */
  msg: string
}

export interface ResultCourseClassification {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseClassification
  /**
   *
   */
  msg: string
}

export interface CourseClassificationPageVO {
  /**
   *
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 状态 1启用 0停用
   */
  status: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  createUser: number
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  updateUser: number
  /**
   * 组织id
   */
  deptId: number
  /**
   * 是否标签 0 否 1 是
   */
  labelIdentification: number
  /**
   * 组织全量
   */
  deptFullId: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 排序号
   */
  sort: number
}

export interface DataCourseClassificationPageVO {
  /**
   *
   */
  list: CourseClassificationPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCourseClassificationPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCourseClassificationPageVO
  /**
   *
   */
  msg: string
}

export interface ResultListCourseClassification {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseClassification[]
  /**
   *
   */
  msg: string
}

export interface CountryAreaPageVO {
  /**
   * id
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 编辑人姓名
   */
  updateUserName: string
}

export interface ResultListCountryAreaPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CountryAreaPageVO[]
  /**
   *
   */
  msg: string
}

export interface ResultCountryAreaForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CountryAreaForm
  /**
   *
   */
  msg: string
}

export interface DataCountryAreaPageVO {
  /**
   *
   */
  list: CountryAreaPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCountryAreaPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCountryAreaPageVO
  /**
   *
   */
  msg: string
}

export interface ResultListTreeNodeObject {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: TreeNodeObject[]
  /**
   *
   */
  msg: string
}

export interface TreeNodeObject {
  /**
   *
   */
  id: string
  /**
   *
   */
  parentId: string
  /**
   *
   */
  name: string
  /**
   *
   */
  parent: boolean
  /**
   *
   */
  param: IObject
  /**
   *
   */
  biz: IObject
  /**
   *
   */
  children: IObject[]
}

export interface IPageCityEntity {
  /**
   *
   */
  size: number
  /**
   *
   */
  current: number
  /**
   *
   */
  records: CityEntity[]
  /**
   *
   */
  total: number
  /**
   *
   */
  pages: number
}

export interface CaptchaResult {
  /**
   * 验证码缓存key
   */
  captchaKey: string
  /**
   * 验证码图片Base64字符串
   */
  captchaBase64: string
}

export interface ResultCaptchaResult {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CaptchaResult
  /**
   *
   */
  msg: string
}

export interface ResultArticleManagementForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: ArticleManagementForm
  /**
   *
   */
  msg: string
}

export interface ArticleManagementPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 文章名称
   */
  title: string
  /**
   * 文章内容
   */
  articleDesc: string
  /**
   * 链接地址
   */
  linkUrl: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 文章分类
   */
  articleType: string
}

export interface DataArticleManagementPageVO {
  /**
   *
   */
  list: ArticleManagementPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultArticleManagementPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataArticleManagementPageVO
  /**
   *
   */
  msg: string
}

export interface DataOrderPageVO {
  /**
   *
   */
  list: OrderPageVO[]
  /**
   *
   */
  total: number
}

export interface OrderPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 订单的用户id
   */
  userId: string
  /**
   * 订单的用户姓名
   */
  userName: string
  /**
   * 订单的用户手机号
   */
  userPhone: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已完成；3.待退款 4已取消)
   */
  status: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  refundAmount: number
  /**
   *
   */
  orderNumber: string
  /**
   * 首次支付时间
   */
  firstPayTime: string
}

export interface PageResultOrderPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataOrderPageVO
  /**
   *
   */
  msg: string
}

export interface CoursePageVO {
  /**
   *
   */
  id: string
  /**
   *
   */
  trialLessonId: string
  /**
   * 课程名称
   */
  name: string
  /**上课地区 */
  countryAreas: string
  /**购买须知 */
  purchaseNotice: string
  /**是否展示价格 */
  isShowPrice:number
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 课班数量
   */
  classCount: number
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 课程售价
   */
  price: number
  /**
   * 审核原因
   */
  auditReason: string
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 机构ID
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 部门Fullid
   */
  treePath: string
  /**
   * 审核状态((1:审核通过;0:待审核；2审核不通过))
   */
  status: number
  /**
   * 逻辑删除标识(0:未删除;1:已删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   *
   */
  mainPicture: string
  /**
   * 上架状态((2：已下架1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   *
   */
  publicityPictureUrls: string[]
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  /**
   *
   */
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  commissionRate: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
}

export interface DataCoursePageVO {
  /**
   *
   */
  list: CoursePageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCoursePageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCoursePageVO
  /**
   *
   */
  msg: string
}

export interface CourseBO {
  /**
   *
   */
  id: string
  /**
   *
   */
  name: string
  /**
   *
   */
  ageRangeCode: string
  /**
   *
   */
  suitAgeStart: number
  /**
   *
   */
  suitAgeEnd: number
  /**
   *
   */
  teacherId: string
  /**
   *
   */
  teacherName: string
  /**
   *
   */
  institutionId: number
  /**
   *
   */
  institutionName: string
  /**
   *
   */
  classHourseNumber: number
  /**
   *
   */
  teachLanguageCode: string
  /**
   *
   */
  teachWayCode: string
  /**
   *
   */
  classCount: number
  /**
   *
   */
  minClassCount: number
  /**
   *
   */
  otherInstructions: string
  /**
   *
   */
  specialLabel: string
  /**
   *
   */
  teachingCharacteristics: string
  /**
   *
   */
  courseFeatures: string
  /**
   *
   */
  courseDescription: string
  /**
   *
   */
  startTime: string
  /**
   *
   */
  courseClassificationId: string
  /**
   *
   */
  goldContent: number
  /**
   *
   */
  comprehensiveEvaluation: number
  /**
   *
   */
  price: number
  /**
   *
   */
  auditReason: string
  /**
   *
   */
  deptId: number
  /**
   *
   */
  treePath: string
  /**
   *
   */
  status: number
  /**
   *
   */
  deleted: number
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  updateUser: string
  /**
   *
   */
  createUserName: string
  /**
   *
   */
  updateUserName: string
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 城市名称
   */
  cityName: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 区县名称
   */
  countyName: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 区县名称
   */
  provinceName: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   *
   */
  publicityPictureUrls: string[]
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  /**
   *
   */
  sortNumber: number
  /**
   *
   */
  trialLessonId: string
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   *
   */
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
}

export interface ResultListCourseBO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseBO[]
  /**
   *
   */
  msg: string
}

export interface ResultListCourseAuditRecord {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseAuditRecord[]
  /**
   *
   */
  msg: string
}

export interface ResultListCourseScheduleForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: CourseScheduleForm[]
  /**
   *
   */
  msg: string
}

export interface CommissionVO {
  /**
   * 佣金信息id
   */
  id: number
  /**
   * 订单id
   */
  orderId: string
  /**
   * 机构ID
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 佣金比例
   */
  commissionRate: number
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 佣金金额
   */
  commissionAmount: number
  /**
   * 结算状态
   */
  settlementStatus: string
  /**
   * 用户姓名
   */
  userName: string
  /**
   * 用户手机号
   */
  userPhone: string
}

export interface DataCommissionVO {
  /**
   *
   */
  list: CommissionVO[]
  /**
   *
   */
  total: number
}

export interface PageResultCommissionVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataCommissionVO
  /**
   *
   */
  msg: string
}

export interface ResultStudentBookingForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: StudentBookingForm
  /**
   *
   */
  msg: string
}

export interface DataServedCustomerForm {
  /**
   *
   */
  list: ServedCustomerForm[]
  /**
   *
   */
  total: number
}

export interface PageResultServedCustomerForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataServedCustomerForm
  /**
   *
   */
  msg: string
}

export interface DataRichTextPageVO {
  /**
   *
   */
  list: RichTextPageVO[]
  /**
   *
   */
  total: number
}

export interface PageResultRichTextPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataRichTextPageVO
  /**
   *
   */
  msg: string
}

export interface RichTextPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 图片url
   */
  mainPicture: string
  /**
   * 是否展示
   */
  isDisplay: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
}

export interface ResultFeedbackForm {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: FeedbackForm
  /**
   *
   */
  msg: string
}

export interface DataFeedback {
  /**
   *
   */
  list: Feedback[]
  /**
   *
   */
  total: number
}

export interface Feedback {
  /**
   *
   */
  createTime: string
  /**
   *
   */
  updateTime: string
  /**
   *
   */
  id: number
  /**
   *
   */
  feedbackContent: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeName: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeCode: string
  /**
   *
   */
  createUser: string
  /**
   *
   */
  createUserName: string
}

export interface PageResultFeedback {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataFeedback
  /**
   *
   */
  msg: string
}

export interface DataKsCustPageVO {
  /**
   *
   */
  list: KsCustPageVO[]
  /**
   *
   */
  total: number
}

export interface KsCustPageVO {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 用户账户
   */
  username: string
  /**
   * 用户密码
   */
  password: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 用户ID
   */
  userId: number
  /**
   *
   */
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 子账户人数
   */
  childNum: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  /**
   *
   */
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 性别 1 男  2 女
   */
  sex: boolean
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   *
   */
  courseId: string
  /**
   * 总积分
   */
  points: number
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
}

export interface PageResultKsCustPageVO {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: DataKsCustPageVO
  /**
   *
   */
  msg: string
}

export interface KsCustBaseDto {
  /**
   *
   */
  id: string
  /**
   *
   */
  name: string
  /**
   *
   */
  nickName: string
  /**
   *
   */
  phone: string
}

export interface ResultListKsCustBaseDto {
  /**
   *
   */
  code: string
  /**
   *
   */
  data: KsCustBaseDto[]
  /**
   *
   */
  msg: string
}

