// Generated by Node.js script
// !!!!! DO NOT EDIT !!!!!

import { IObject } from './commonTypes'

export interface ResultObject {
  code: string
  data: IObject
  msg: string
}

export interface UserForm {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 昵称
   */
  nickname: string
  /**
   * 手机号码
   */
  mobile: string
  /**
   * 性别
   */
  gender: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 邮箱
   */
  email: string
  /**
   * 用户状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 角色ID集合
   */
  roleIds: number[]
}

export interface UserChangePasswordForm {
  /**
   * 旧密码
   */
  srcPassword: string
  /**
   * 新密码
   */
  newPassword: string
  /**
   * 手机号
   */
  mobile: string
  /**
   * 邮箱
   */
  email: string
}

export interface RoleForm {
  /**
   * 角色ID
   */
  id: number
  /**
   * 角色名称
   */
  name: string
  /**
   * 角色编码
   */
  code: string
  /**
   * 排序
   */
  sort: number
  /**
   * 角色状态(1-正常；0-停用)
   */
  status: number
  /**
   * 数据权限
   */
  dataScope: number
}

export interface KeyValue {
  /**
   * 选项的值
   */
  key: string
  /**
   * 选项的标签
   */
  value: string
}

export interface MenuForm {
  /**
   * 菜单ID
   */
  id: number
  /**
   * 父菜单ID
   */
  parentId: number
  /**
   * 菜单名称
   */
  name: string
  /**
   * 菜单类型(1-菜单；2-目录；3-外链；4-按钮权限)
   */
  type: string
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径(vue页面完整路径，省略.vue后缀)
   */
  component: string
  /**
   * 权限标识
   */
  perm: string
  /**
   * 显示状态(1:显示;0:隐藏)
   */
  visible: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 菜单图标
   */
  icon: string
  /**
   * 跳转路径
   */
  redirect: string
  /**
   * 【菜单】是否开启页面缓存
   */
  keepAlive: number
  /**
   * 【目录】只有一个子路由是否始终显示
   */
  alwaysShow: number
  /**
   * 路由参数
   */
  params: KeyValue[]
  /**
   * 查询类型：1 查询所有  2 查询部分
   */
  queryType: number
}

export interface DictForm {
  /**
   * 字典ID
   */
  id: number
  /**
   * 类型编码
   */
  typeCode: string
  /**
   * 字典名称
   */
  name: string
  /**
   * 字典值
   */
  value: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序
   */
  sort: number
  /**
   * 字典备注
   */
  remark: string
}

export interface DictTypeForm {
  /**
   * 字典类型ID
   */
  id: number
  /**
   * 类型名称
   */
  name: string
  /**
   * 类型编码
   */
  code: string
  /**
   * 类型状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 备注
   */
  remark: string
}

export interface DeptForm {
  /**
   * 部门ID
   */
  id: number
  /**
   * 部门名称
   */
  name: string
  /**
   * 父部门ID
   */
  parentId: number
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
}

export interface IPageUserPageVO {
  size: number
  current: number
  records: UserPageVO[]
  pages: number
  total: number
}

export interface UserPageVO {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 手机号
   */
  mobile: string
  /**
   * 性别
   */
  genderLabel: string
  /**
   * 用户头像地址
   */
  avatar: string
  /**
   * 用户邮箱
   */
  email: string
  /**
   * 用户状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 部门名称
   */
  deptName: string
  /**
   * 角色名称，多个使用英文逗号(,)分割
   */
  roleNames: string
  /**
   * 创建时间
   */
  createTime: string
}

export interface UserDeptVO {
  /**
   * 部门或机构id，根据isInstitution而定
   */
  id: number
  /**
   * 部门或机构名称，根据isInstitution而定
   */
  name: string
  /**
   * 是否机构
   */
  isInstitution: boolean
}

export interface UserInfoVO {
  /**
   * 用户ID
   */
  userId: string
  /**
   * 用户名
   */
  username: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 头像地址
   */
  avatar: string
  /**
   * 用户角色编码集合
   */
  roles: string[]
  /**
   * 用户权限标识集合
   */
  perms: string[]
  dept: UserDeptVO
}

export interface OrderItem {
  column: string
  asc: boolean
}

export interface PageRolePageVO {
  records: RolePageVO[]
  total: number
  size: number
  current: number
  orders: OrderItem[]
  optimizeCountSql: PageRolePageVO
  searchCount: PageRolePageVO
  optimizeJoinOfCountSql: boolean
  maxLimit: number
  countId: string
  pages: number
}

export interface RolePageVO {
  /**
   * 角色ID
   */
  id: number
  /**
   * 角色名称
   */
  name: string
  /**
   * 角色编码
   */
  code: string
  /**
   * 角色状态
   */
  status: number
  /**
   * 排序
   */
  sort: number
  createTime: string
  updateTime: string
}

export interface Option {
  /**
   * 选项的值
   */
  value: IObject
  /**
   * 选项的标签
   */
  label: string
}

export interface OptionObject {
  /**
   * 选项的值
   */
  value: IObject
  /**
   * 选项的标签
   */
  label: string
  /**
   * 子选项列表
   */
  children: Option[]
}

export interface MenuVO {
  /**
   * 菜单ID
   */
  id: number
  /**
   * 父菜单ID
   */
  parentId: number
  /**
   * 菜单名称
   */
  name: string
  /**
   * 菜单类型
   */
  type: string
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径
   */
  component: string
  /**
   * 菜单排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 菜单是否可见(1:显示;0:隐藏)
   */
  visible: number
  /**
   * ICON
   */
  icon: string
  /**
   * 跳转路径
   */
  redirect: string
  /**
   * 按钮权限标识
   */
  perm: string
  /**
   * 子菜单
   */
  children: MenuVO[]
  /**
   * 查询类型：1 查询所有  2 查询部分
   */
  queryType: number
}

export interface Meta {
  /**
   * 路由title
   */
  title: string
  /**
   * ICON
   */
  icon: string
  /**
   * 是否隐藏(true-是 false-否)
   */
  hidden: boolean
  /**
   * 拥有路由权限的角色编码
   */
  roles: string[]
  /**
   * 【菜单】是否开启页面缓存
   */
  keepAlive: boolean
  /**
   * 【目录】只有一个子路由是否始终显示
   */
  alwaysShow: boolean
  /**
   * 路由参数
   */
  params: IObject
}

export interface RouteVO {
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径
   */
  component: string
  /**
   * 跳转链接
   */
  redirect: string
  /**
   * 路由名称
   */
  name: string
  meta: Meta
  /**
   * 子路由列表
   */
  children: RouteVO[]
}

export interface DictTypePageVO {
  /**
   * 字典类型ID
   */
  id: number
  /**
   * 类型名称
   */
  name: string
  /**
   * 类型编码
   */
  code: string
  /**
   * 状态：1:启用;0:禁用
   */
  status: number
  remark: string
}

export interface PageDictTypePageVO {
  records: DictTypePageVO[]
  total: number
  size: number
  current: number
  orders: OrderItem[]
  optimizeCountSql: PageDictTypePageVO
  searchCount: PageDictTypePageVO
  optimizeJoinOfCountSql: boolean
  maxLimit: number
  countId: string
  pages: number
}

export interface DictPageVO {
  /**
   * 字典ID
   */
  id: number
  /**
   * 字典名称
   */
  name: string
  /**
   * 字典值
   */
  value: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  defaulted: number
  remark: string
}

export interface PageDictPageVO {
  records: DictPageVO[]
  total: number
  size: number
  current: number
  orders: OrderItem[]
  optimizeCountSql: PageDictPageVO
  searchCount: PageDictPageVO
  optimizeJoinOfCountSql: boolean
  maxLimit: number
  countId: string
  pages: number
}

export interface HomeDataDto {
  history: string
  trainees: string
  goodRatings: string
}

export interface DeptVO {
  /**
   * 部门ID
   */
  id: number
  /**
   * 父部门ID
   */
  parentId: number
  /**
   * 部门名称
   */
  name: string
  /**
   * 排序
   */
  sort: number
  /**
   * 状态(1:启用；0:禁用)
   */
  status: number
  /**
   * 子部门
   */
  children: DeptVO[]
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 修改时间
   */
  updateTime: string
}

