// Generated by Node.js script

export type IObject = Record<string, any>

export interface CourseVO {
  id: string
  name: string
}

/**
 * 用户表表单对象
 */
export interface KsCustForm {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 用户账户
   */
  username: string
  /**
   * 用户密码
   */
  password: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 用户ID
   */
  userId: number
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 性别 1 男  2 女
   */
  sex: boolean
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   * 积分
   */
  points: number
  courseId: string
  courseList: CourseVO[]
  addresList: string[]
  childNum: number
  /**
   * 邀请他人的邀请码
   */
  invitationCustCode: string
  invitationCust: string
  custId: string
  /**
   * 自身邀请码
   */
  invitationCode: string
  /**
   * 邀请时间
   */
  invitationTime: string
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
  /**
   * 是否白名单(0否 1是)
   */
  isWhitelist: number
}

export interface KsCustQueryDto {
  parentId: string
}

/**
 * 用户表视图对象
 */
export interface KsCustVO {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 用户账户
   */
  username: string
  /**
   * 用户密码
   */
  password: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 用户ID
   */
  userId: number
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 性别 1 男  2 女
   */
  sex: boolean
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  courseId: string
  childNum: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  createUser: string
  createUserName: string
  /**
   * 黑名单  0 否  1  是
   */
  disallowLogin: number
}

export interface OpenIdQueryDto {
  code: string
  openId: string
  /**
   * 邀请码
   */
  invitationCode: string
  /**
   * 用户来源取自字典小程序码用途
   */
  type: string
}

export interface CouponListQuery {
  userId: string
  courseId: string
  courseClassId: string
  orderAmount: number
  date: string
}

export interface WxPayReqParam {
  totalPrice: string
  goodsName: string
  orderNumber: string
  orderId: string
}

export interface WxPayRefundReqParam {
  transactionId: string
  refundMoney: string
  totalMoney: string
}

/**
 * 收款账号请求参数
 */
export interface AccountReqParam {
  /**
   * 订单ID
   */
  orderId: string
}

/**
 * 机构支付方式VO
 */
export interface InstitutionPaymentInfoVO {
  /**
   * 收款账户名
   */
  beneficiaryName: string
  /**
   * 收款账号
   */
  accountNumber: string
  /**
   * 收款银行
   */
  bankName: string
  /**
   * 收款二维码base64
   */
  paymentQrCode: string
  /**
   * 支付宝收款二维码base64
   */
  aliPaymentQrCode: string
  /**
   * 收款方式，具体枚举查看字典paymentType，wechat-微信收款码，alipay-支付宝收款码，bank-银行转账
   */
  paymentType: string
}

export interface SOAPayReqParam {
  orderId: string
  payMode: string
}

/**
 * 拉卡拉创建订单结果
 */
export interface SOAPayDto {
  /**
   * 拉起地址
   */
  counterUrl: string
  /**
   * 是否支付完成
   */
  payment: boolean
  /**
   * 支付金额，单位分
   */
  fee: number
}

/**
 * 意见反馈表单对象
 */
export interface FeedbackForm {
  /**
   * 主键
   */
  id: number
  /**
   * 意见反馈
   */
  feedbackContent: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeName: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeCode: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人ID
   */
  createUserName: string
}

/**
 * 课程评价表表单对象
 */
export interface CourseEvaluationForm {
  /**
   * 主键
   */
  id: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 总评分
   */
  totalScore: number
}

/**
 * 约课对象
 */
export interface StudentCourseOperationForm {
  /**
   * 学生id
   */
  studentId: string
  /**
   * 约课明细ID
   */
  detailId: string
}

/**
 * 约课对象
 */
export interface CourseBookingForm {
  /**
   * 学生id
   */
  studentId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课时id列表
   */
  scheduleId: number
}

/**
 * 约课对象
 */
export interface OrderCourseBindForm {
  /**
   * 学生id
   */
  studentId: string
  /**
   * 主键
   */
  id: string
}

/**
 * 课程列表
 */
export interface CourseItem {
  /**
   * 课程ID
   */
  courseId: string
  /**
   * 购买数量
   */
  count: number
  /**
   * 机构ID
   */
  institutionId: string
  /**
   * 讲师ID
   */
  teacherId: string
}

export interface PreCalculatePriceForm {
  /**
   * 优惠券ID列表
   */
  couponIds: string[]
  /**
   * 课程列表
   */
  courseList: CourseItem[]
}

export interface OrderCreateForm {
  /**
   * 优惠券ID列表
   */
  couponIds: string[]
  /**
   * 课程列表
   */
  courseList: CourseItem[]
  /**
   * 价格id，创建订单时提交
   */
  priceId: string
}

export interface BasePageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
}

export interface ConsumptionRecordsDetailDto {
  courseName: string
  courseCount: number
}

export interface ConsumptionRecordsDto {
  payAmount: number
  orderTime: string
  id: string
  list: ConsumptionRecordsDetailDto[]
}

export interface DataConsumptionRecordsDto {
  list: ConsumptionRecordsDto[]
  total: number
}

/**
 * 讲师列表分页查询对象
 */
export interface TeacherInfoQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 关键词，支持姓名和简介
   */
  keys: string
  /**
   * 讲师标签
   */
  tags: string[]
  /**
   * 国家地区ID，上传最小一级的id
   */
  countryAreaId: string
}

export interface DataTeacherInfoVO {
  list: TeacherInfoVO[]
  total: number
}

/**
 * 讲师信息对象
 */
export interface TeacherInfoVO {
  /**
   * 讲师id
   */
  id: string
  /**
   * 讲师的用户id，可用于登陆后台系统
   */
  userId: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 年龄
   */
  age: number
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 所授专业
   */
  teachingMajor: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人
   */
  createUserName: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新人
   */
  updateUser: string
  /**
   * 更新人
   */
  updateUserName: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 讲师标签
   */
  tag: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 擅长学科
   */
  goodSubject: string
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 讲师titleCode
   */
  titleCode: string
  /**
   * 讲师titleName
   */
  titleName: string
  /**
   * 首页标语
   */
  homeSlogan: string
  /**
   * 列表标语
   */
  listSlogan: string
  /**
   * 讲师评分
   */
  evaluation: number
  goodFields: string[]
}

/**
 * 优秀讲师列表分页查询对象
 */
export interface ExcellentTeacherQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 备注信息
   */
  addressLike: string
  /**
   * 国家地区ID，上传最小一级的id
   */
  countryAreaId: string
}

export interface BaseQueryDto {
  ids: string[]
}

export interface CityEntity {
  id: string
  cityName: string
  cityShortName: string
  cityMergeName: string
  cityPinyin: string
  cityLng: number
  cityLat: number
  cityLevel: number
  parentId: string
  treePath: string
  cityState: number
  cityCode: string
}

export interface InvitationCustVo {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 用户昵称
   */
  username: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 是否消费  true 消费  false 没有消费
   */
  consumption: boolean
  /**
   * 积分
   */
  point: number
}

/**
 * 优惠劵表表单对象
 */
export interface CouponForm {
  /**
   * 主键
   */
  id: number
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 发放数量
   */
  number: number
  /**
   * 使用门槛(0无 其他数值为门槛金额)
   */
  useThreshold: number
  /**
   * 使用范围(1通用 2指定课程可用 3指定课程不可用)
   */
  useScope: number
  /**
   * 使用范围不为通用详情
   */
  userScopeDetail: string
  /**
   * 领取方式(1人工发放 2系统赠送)
   */
  receiveType: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 使用时间(1固定时间 2当日起几天 3次日起几天)
   */
  useRestrictedType: number
  /**
   * 使用时间天数
   */
  useRestrictedNum: number
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 修改人ID
   */
  updateBy: number
  deptId: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
  idPathList: string[]
}

export interface DataWechatUserCouponDTO {
  list: WechatUserCouponDTO[]
  total: number
}

export interface WechatUserCouponDTO {
  id: number
  userId: string
  userName: string
  couponId: number
  couponName: string
  couponPic: string
  couponThumbnail: string
  status: number
  useStatus: number
  createUser: string
  createTime: string
  updateUser: string
  updateTime: string
  delFlag: number
  /**
   * 订单id
   */
  orderId: string
  limitUsageEndTime: string
  limitUsageStartTime: string
  useScope: number
  receiveType: number
  deductionAmount: number
  businessNames: string
  type: number
  remark: string
}

/**
 * 优惠劵表分页视图对象
 */
export interface CouponPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 使用限制类型(1:限制使用时间;0:限制使用天数)
   */
  useRestrictedType: number
  /**
   * 满足优惠金额
   */
  amountMet: number
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  /**
   * 可用课程
   */
  courseId: string
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 修改人ID
   */
  updateBy: number
  deptId: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
}

export interface DataCouponPageVO {
  list: CouponPageVO[]
  total: number
}

export interface DataMemberRuleVO {
  list: MemberRuleVO[]
  total: number
}

/**
 * 会员等级规则对象
 */
export interface MemberRuleVO {
  /**
   * 会员等级规则ID
   */
  id: number
  /**
   * 会员等级规则ID
   */
  level: number
  /**
   * 会员等级名称
   */
  levelName: string
  /**
   * 会员等级规则ID
   */
  levelRule: number
  /**
   * 邀请加分比例
   */
  invitedRatio: number
  /**
   * 消费加分比例
   */
  consumeRatio: number
  /**
   * 积分兑换比例
   */
  exchangeRatio: number
  /**
   * 积分有效时长(天)
   */
  duration: number
  /**
   * 会员折扣
   */
  discount: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 可查看的课程数量，-1表示不限制
   */
  viewableCourseCount: number
  /**
   * 可查看的讲师数量，-1表示不限制
   */
  viewableTeacherCount: number
  /**
   * 能否查看课程价格，0不可以，1可以
   */
  isShowCoursePrice: number
  /**
   * 权益说明
   */
  interestsStatement: string
  /**
   * 积分获取
   */
  integralGain: string
  /**
   * 权益规则
   */
  equityRules: string
}

/**
 * 服务过的客户表单对象
 */
export interface ServedCustomerForm {
  /**
   * id
   */
  id: number
  /**
   * 服务过的客户中文名
   */
  chineseName: string
  /**
   * 服务过的客户英文名
   */
  englishName: string
  /**
   * logo地址
   */
  logoUrl: string
}

export interface DataSchoolForm {
  list: SchoolForm[]
  total: number
}

/**
 * 学校信息表单对象
 */
export interface SchoolForm {
  /**
   * id
   */
  id: number
  /**
   * 学校中文名
   */
  chineseName: string
  /**
   * 学校英文名
   */
  englishName: string
  /**
   * logo地址
   */
  logoUrl: string
}

/**
 * 富文本表表单对象
 */
export interface RichTextForm {
  /**
   * 主键
   */
  id: number
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 图片url
   */
  mainPicture: string
  /**
   * 是否展示
   */
  isDisplay: number
}

export interface DataRichTextSimplePageVO {
  list: RichTextSimplePageVO[]
  total: number
}

/**
 * 富文本表分页视图对象
 */
export interface RichTextSimplePageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 图片url
   */
  mainPicture: string
}

/**
 * 课程评价表分页视图对象
 */
export interface CourseEvaluationPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id
   */
  courseName: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 总评分
   */
  totalScore: number
}

export interface DataCourseEvaluationPageVO {
  list: CourseEvaluationPageVO[]
  total: number
}

/**
 * 后台手工约课Form
 */
export interface StudentBookingForm {
  /**
   * 主键
   */
  id: number
  /**
   * 学生id
   */
  studentId: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师id对应的姓名
   */
  selectedTeacherName: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 机构id
   */
  institutionId: string
  /**
   * 机构id对应的机构名称
   */
  selectedInstitutionName: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id对应的课程名称
   */
  selectedCourseName: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 背景颜色
   */
  background: string
  /**
   * 上课地点
   */
  location: string
  /**
   * 备注
   */
  remark: string
}

/**
 * 学生课表月度计数VO
 */
export interface StudentScheduleMouthCountVO {
  /**
   * 日期（格式：YYYY-MM-DD）
   */
  date: string
  /**
   * 对应日期的次数
   */
  count: number
}

export interface DataStudentOrderCoursePageVO {
  list: StudentOrderCoursePageVO[]
  total: number
}

/**
 * 用户课程表分页视图对象
 */
export interface StudentCourseDetailSlotVO {
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
}

/**
 * 用户课程表分页视图对象
 */
export interface StudentOrderCoursePageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 产品id
   */
  productId: number
  /**
   * 课程数量
   */
  productCount: number
  /**
   * 订单表id
   */
  orderId: string
  /**
   * 用户id
   */
  userId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 课程封面
   */
  coursePicture: string
  /**
   * 课时数量
   */
  courseCount: number
  /**
   * 已上数量
   */
  attendedCount: number
  /**
   * 已预约数量
   */
  appointmentCount: number
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 下单时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 讲师id
   */
  studentId: string
  /**
   * 讲师姓名
   */
  studentName: string
  /**
   * 学习状态
   */
  learnStatus: string
  lastCourse: StudentCourseDetailSlotVO
  /**
   * 适合年龄起始值
   */
  suitAgeStart: number
  /**
   * 适合年龄结束值
   */
  suitAgeEnd: number
  /**
   * 授课方式编码
   */
  teachWayCode: string
}

/**
 * 约课信息VO
 */
export interface CourseAvailVO {
  /**
   * 约课明细编号
   */
  scheduleId: number
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 预约状态，INIT-未预约，BOOKED-已预约
   */
  bookingStatus: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
}

/**
 * 用户课程表分页视图对象
 */
export interface StudentCourseDetailVO {
  /**
   * 课时id
   */
  scheduleId: string
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 约课状态，参考字典courseBookingStatus
   */
  bookingStatus: string
  /**
   * 教师授课状态，参考字典teachingStatus
   */
  teachingStatus: string
  evaluationId: string
}

export interface OrderDetail {
  createTime: string
  updateTime: string
  id: string
  productId: number
  productCount: number
  courseId: string
  teacherId: string
  orderId: string
  productPrice: number
  productAmount: number
  courseName: string
  courseHoursCount: number
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
  /**
   * 主图
   */
  mainPicture: string
  productName: string
}

/**
 * 订单表表单对象
 */
export interface OrderForm {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已支付；已完成)
   */
  status: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  createUserName: string
  orderDetails: OrderDetail[]
  coupons: UserCoupon[]
  refundAmount: number
  orderNumber: string
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 首次支付时间
   */
  firstPayTime: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 用户父级id，没有为父级自身id
   */
  userParentId: string
}

export interface UserCoupon {
  id: number
  userId: string
  userName: string
  couponId: number
  couponName: string
  couponPic: string
  couponThumbnail: string
  status: number
  useStatus: number
  createUser: string
  createTime: string
  updateUser: string
  updateTime: string
  delFlag: number
  /**
   * 订单id
   */
  orderId: string
}

export interface DataWechatOrderDto {
  list: WechatOrderDto[]
  total: number
}

export interface WechatOrderDto {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已完成；3.待退款 4已取消)
   */
  status: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  refundAmount: number
  orderNumber: string
  orderDetails: OrderDetail[]
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
}

/**
 * 讲师信息证明资料
 */
export interface ProofMaterialsForm {
  /**
   * 身份证正反面列表
   */
  idCards: string[]
  /**
   * 社会保障卡，驾照或护照列表
   */
  socialProofMaterials: string[]
  /**
   * 学历证明列表
   */
  degreeCertificates: string[]
}

/**
 * 讲师信息教育背景表单对象
 */
export interface TeacherEducationBackgroundForm {
  /**
   * 学校名称
   */
  schoolName: string
  /**
   * 所在国家
   */
  country: string
  /**
   * 专业名称
   */
  major: string
  /**
   * 学历
   */
  degree: string
  /**
   * 学习开始时间
   */
  studyStartDate: string
  /**
   * 学习结束时间
   */
  studyEndDate: string
}

/**
 * 讲师信息教育履历表单对象
 */
export interface TeacherExperienceForm {
  /**
   * 职务名称
   */
  jobTitle: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 在职开始日期
   */
  startDay: string
  /**
   * 在职结束日期
   */
  endDay: string
  /**
   * 教学内容
   */
  teachingContent: string
  /**
   * 获得成就奖项
   */
  achievements: string
}

/**
 * 讲师信息表单对象
 */
export interface TeacherInfoDto {
  id: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 所授专业
   */
  teachingMajor: string
  /**
   * 宣传语
   */
  slogan: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 备注信息
   */
  mark: string
  /**
   * 讲师标签
   */
  tag: string
  proofMaterials: ProofMaterialsForm
  introduction: TeacherIntroductionForm
  /**
   * 教育履历
   */
  experience: string
  /**
   * 教育履历
   */
  experienceList: TeacherExperienceForm[]
  /**
   * 教育背景列表
   */
  educationBackgroundList: TeacherEducationBackgroundForm[]
  evaluation: number
  isShowTeacherDetail: number
  titleCode: string
  /**
   * 首页标语
   */
  homeSlogan: string
  /**
   * 列表标语
   */
  listSlogan: string
  /**
   * 擅长科目
   */
  goodSubject: string
  /**
   * 擅长领域
   */
  goodFields: string[]
}

/**
 * 讲师表单自我介绍对象
 */
export interface TeacherIntroductionForm {
  /**
   * 详细介绍
   */
  detailedIntroduction: string
  /**
   * 视频介绍地址
   */
  videoIntroductionUrl: string
}

export interface DataTeacherCourseVO {
  list: TeacherCourseVO[]
  total: number
}

export interface TeacherCourseVO {
  /**
   * 主键id
   */
  id: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 课程图片url
   */
  mainPicture: string
}

/**
 * 课程主表表单对象
 */
export interface CourseForm {
  id: string
  trialLessonId: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 开课人数
   */
  classCount: number
  /**
   * 课班数量
   */
  minClassCount: number
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  /**
   * 课程售价
   */
  price: number
  /**
   * 审核原因
   */
  auditReason: string
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 部门Fullid
   */
  treePath: string
  /**
   * 审核状态((1:已审核;0:待审核))
   */
  status: number
  /**
   * 逻辑删除标识(0:未删除;1:已删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  createUser: string
  updateUser: string
  createUserName: string
  updateUserName: string
  mainPicture: string
  publicityPictureUrls: string[]
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  commissionRate: number
  /**
   * 新单佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  newCommissionRate: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 经度
   */
  longitude: string
  /**
   * 纬度
   */
  latitude: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 是否属于世界名校(0:否,1:是)
   */
  isWorldFamousSchool: number
  /**
   * 是否在世界名校板块展示(0:否,1:是)
   */
  isShowWorldFamousSchool: number
  /**
   * 在世界名校板块的排序号
   */
  worldFamousSchoolSort: number
  /**
   * 是否属于国际课程(0:否,1:是)
   */
  isInternationalCourse: number
  /**
   * 是否在国际课程板块展示(0:否,1:是)
   */
  isShowInternationalCourse: number
  /**
   * 在国际课程板块的排序号
   */
  internationalCourseSort: number
  /**
   * 是否属于学术能力(0:否,1:是)
   */
  isAcademicAbility: number
  /**
   * 是否在学术能力板块展示(0:否,1:是)
   */
  isShowAcademicAbility: number
  /**
   * 在学术能力板块的排序号
   */
  academicAbilitySort: number
  /**
   * 是否属于综合素质(0:否,1:是)
   */
  isComprehensiveQuality: number
  /**
   * 是否在综合素质板块展示(0:否,1:是)
   */
  isShowComprehensiveQuality: number
  /**
   * 在综合素质板块的排序号
   */
  comprehensiveQualitySort: number
}

/**
 * 课程详情VO
 */
export interface CourseDetailVO {
  /**
   * 课程名称
   */
  name: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 计费方式
   */
  priceMethod: string
  /**
   * 日期包细节
   */
  datePackageDetail: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  /**
   * 主图url
   */
  mainPicture: string
  /**
   * 轮播图url列表
   */
  publicityPictureUrls: string[]
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 最少开课人数，即开班人数
   */
  minClassCount: number
  /**
   * 最大人数
   */
  classCount: number
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 讲师列表
   */
  teachers: CourseTeacherVO[]
  /**
   * 已学人数
   */
  studentsNumber: number
  /**
   * 推荐顺序
   */
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 课程售价
   */
  price: number
}

/**
 * 课程详情VO
 */
export interface CourseTeacherVO {
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 课程售价
   */
  price: number
  /**
   * 试听id
   */
  trialLessonId: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 备注信息
   */
  mark: string
  isShowTeacherDetail: number
}

export interface CourseQueryPageVO {
  id: string
  name: string
  ageRangeCode: string
  suitAgeStart: number
  suitAgeEnd: number
  classHourseNumber: number
  teachLanguageCode: string
  teachWayCode: string
  classCount: number
  minClassCount: number
  otherInstructions: string
  specialLabel: string
  teachingCharacteristics: string
  courseFeatures: string
  courseDescription: string
  /**
   * 购买须知
   */
  purchaseNotice: string
  startTime: string
  courseClassificationId: string
  goldContent: number
  comprehensiveEvaluation: number
  isShowPrice: number
  price: number
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 轮播宣传图
   */
  publicityPictureUrls: string[]
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  studentsNumber: number
  sortNumber: number
  trialLessonId: string
  /**
   * 适用条件
   */
  applicableConditions: string
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  mark: string
}

export interface DataCourseQueryPageVO {
  list: CourseQueryPageVO[]
  total: number
}

/**
 * 国家地区表分页视图对象
 */
export interface CountryAreaPageVO {
  /**
   * id
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 是否在小程序展示(0-不展示，1-展示)
   */
  isShowMiniapp: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 编辑人姓名
   */
  updateUserName: string
}

export interface TreeNodeObject {
  id: string
  parentId: string
  name: string
  parent: boolean
  param: Record<string, any>
  biz: Record<string, any>
  children: Record<string, any>[]
}

export interface IPageCityEntity {
  size: number
  current: number
  total: number
  pages: number
  records: CityEntity[]
}

/**
 * 协议表表单对象
 */
export interface AgreementForm {
  /**
   * 主键
   */
  id: string
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 是否展示
   */
  isDisplay: number
}

/**
 * 用户表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/getKsCustForm
 */
export type GetWechatCustomerCustByidRequestParams = {
  /**
   * 用户表ID
   */
  id: string | number;
}

/**
 * 校验验证码是否存在
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/validInvitation
 */
export type GetWechatCustomerCustValidinvitationRequestParams = {
  invitationCode?: string | number;
}

/**
 * 查询邀请用户
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/queryInvitationList
 */
export type GetWechatCustomerCustInvitationRequestParams = {
  id?: string | number;
}

/**
 * 获取小程序邀请码
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/getWxaCodeUnLimit
 */
export type GetWechatCustomerCustGetwxacodeunlimitRequestParams = {
  /**
   * 微信页面参数
   */
  page?: string | number;
}

/**
 * 退出
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/100.小程序用户登录/loginOut
 */
export type GetWechatCustLoginoutRequestParams = {
  phone?: string | number;
}

/**
 * 优惠劵表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/getCouponForm
 */
export type GetWechatCouponsByidRequestParams = {
  /**
   * 优惠劵表ID
   */
  id: string | number;
}

/**
 * 用户优惠劵分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/listPagedCoupons
 */
export type GetWechatCouponsUserPageRequestParams = {
  /**
   * 用户id
   */
  userId?: string | number;
  /**
   * 0未使用 1已使用
   */
  useStatus?: string | number;
  date?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 领取优惠券
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/receive
 */
export type GetWechatCouponsReceiveRequestParams = {
  id?: string | number;
}

/**
 * 优惠劵表分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/listPagedCoupons_1
 */
export type GetWechatCouponsPageRequestParams = {
  /**
   * 关键字
   */
  keywords?: string | number;
  status?: string | number;
  level?: string | number;
  /**
   * 1 有效 
   */
  valid?: string | number;
  date?: string | number;
  receiveType?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 会员等级规则分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/会员等级规则接口/list
 */
export type GetStudentLevelRuleListRequestParams = {
  delFlag?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 学校信息分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学校信息接口/list_2
 */
export type GetSchoolsListRequestParams = {
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 富文本表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/富文本表接口/getRichTextForm
 */
export type GetRichtextsByidFormRequestParams = {
  /**
   * 富文本表ID
   */
  id: string | number;
}

/**
 * 富文本表分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/富文本表接口/listPagedRichTexts
 */
export type GetRichtextsPageRequestParams = {
  /**
   * 关键字
   */
  keywords?: string | number;
  /**
   * 是否展示 0-不展示，1-展示
   */
  isDisplay?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 课程评价表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/getCourseEvaluationForm
 */
export type GetCourseevaluationsByidFormRequestParams = {
  /**
   * 课程评价表ID
   */
  id: string | number;
}

/**
 * 课程评价表分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/listPagedCourseEvaluations
 */
export type GetCourseevaluationsPageRequestParams = {
  /**
   * 课程id
   */
  courseId?: string | number;
  /**
   * 教师id
   */
  teacherId?: string | number;
  /**
   * 最小分数
   */
  totalScoreStart?: string | number;
  /**
   * 最大分数
   */
  totalScoreEnd?: string | number;
  userId?: string | number;
  courseHoursId?: string | number;
  querySelf?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 判断用户是否有评价权限
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/judgeAuth
 */
export type GetCourseevaluationsJudge_authRequestParams = {
  courseId?: string | number;
}

/**
 * 学生客户端查看课程列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生课表接口/getStudentScheduleList
 */
export type GetApiV1StudentScheduleListRequestParams = {
  /**
   * 查询开始时间，闭区间
   */
  startTime?: string | number;
  /**
   * 查询结束时间，闭区间
   */
  endTime?: string | number;
  /**
   * 学生id
   */
  studentId?: string | number;
}

/**
 * 小程序端学生课表月度计数查询
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生课表接口/getStudentScheduleMouthCount
 */
export type GetApiV1StudentScheduleGetstudentschedulemouthcountRequestParams = {
  /**
   * 时区
   */
  timezone?: string | number;
  /**
   * 查询开始时间，闭区间
   */
  startTime?: string | number;
  /**
   * 查询结束时间，闭区间
   */
  endTime?: string | number;
  /**
   * 学生id
   */
  studentId?: string | number;
}

/**
 * 学生客户端查看未绑定的课程列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getUnbindOrderCoursesPage
 */
export type GetApiV1StudentCoursebookingUnbindListRequestParams = {
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 学生客户端查看子账号课程列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getSubUserOrderCoursesPage
 */
export type GetApiV1StudentCoursebookingSublistRequestParams = {
  /**
   * 学生id
   */
  studentId?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 学生客户端查看课程列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getOrderCourseList
 */
export type GetApiV1StudentCoursebookingListRequestParams = {
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 查看某课程某时间段内可约课时间
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getCourseAvail
 */
export type GetApiV1StudentCoursebookingGetcourseavailRequestParams = {
  /**
   * 课程id
   */
  courseId?: string | number;
  /**
   * 查询开始时间，闭区间
   */
  startTime?: string | number;
  /**
   * 查询结束时间，闭区间
   */
  endTime?: string | number;
  /**
   * 学生id
   */
  studentId?: string | number;
}

/**
 * 学生客户端查看上课状态详情
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getCourseDetailList
 */
export type GetApiV1StudentCoursebookingCoursedetailRequestParams = {
  /**
   * 学生id
   */
  studentId?: string | number;
  /**
   * 课程id
   */
  courseId?: string | number;
  /**
   * 查询开始时间，闭区间
   */
  startTime?: string | number;
  /**
   * 查询结束时间，闭区间
   */
  endTime?: string | number;
}

/**
 * 退单
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/refundOrder
 */
export type GetApiV1OrdersByidRefundRequestParams = {
  /**
   * 订单表ID
   */
  id: string | number;
}

/**
 * 订单表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/getOrderForm
 */
export type GetApiV1OrdersByidFormRequestParams = {
  /**
   * 订单表ID
   */
  id: string | number;
}

/**
 * 订单表分页列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/wechatPagedOrders
 */
export type GetApiV1OrdersWechatPageRequestParams = {
  /**
   * 关键字
   */
  keywords?: string | number;
  courseId?: string | number;
  orderTimeStart?: string | number;
  orderTimeEnd?: string | number;
  ids?: string | number;
  userId?: string | number;
  /**
   * 课程分类id
   */
  courseClassificationId?: string | number;
  /**
   *  状态(0全部;1:待支付;2:已完成；3.待退款 4已取消)
   */
  status?: string | number;
  /**
   * 1 预订单  2 订单
   */
  bookingOrder?: string | number;
  /**
   * 机构id
   */
  institutionId?: string | number;
  /**
   * 订单id
   */
  id?: string | number;
  /**
   * 学生信息，支持昵称和手机尾号
   */
  studentKeys?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 获取订单可用的优惠券列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/userCoupon
 */
export type GetApiV1OrdersUserCouponRequestParams = {
  /**
   * 订单表ID
   */
  id?: string | number;
}

/**
 * 退单详情
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/refundList
 */
export type GetApiV1OrdersRefundDetailRequestParams = {
  /**
   * 订单表ID
   */
  id?: string | number;
}

/**
 * 取消订单
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/cancelOrder
 */
export type GetApiV1OrdersCancelRequestParams = {
  id?: string | number;
}

/**
 * 获取讲师详情信息
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/getTeacherForm
 */
export type GetApiV1KsTeacherinfoByidRequestParams = {
  id: string | number;
}

/**
 * 分页查询相似领域的讲师列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/getSimilarTeachers
 */
export type GetApiV1KsTeacherinfoSimilarByteacheridRequestParams = {
  teacherId: string | number;
  pageNum?: string | number;
  pageSize?: string | number;
}

/**
 * 根据讲师id分页获取其课程列表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/getCourses
 */
export type GetApiV1KsTeacherinfoCoursesRequestParams = {
  /**
   * 讲师id
   */
  teacherId?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 课程主表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getCourseForm
 */
export type GetApiV1CoursesByidFormRequestParams = {
  /**
   * 课程主表ID
   */
  id: string | number;
}

/**
 * 课程主表表单数据V2
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getCourseDetail
 */
export type GetApiV1CoursesByidDetailRequestParams = {
  /**
   * 课程主表ID
   */
  id: string | number;
}

/**
 * 课程列表分页-小程序V2
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/listPagedCourses
 */
export type GetApiV1CoursesProceduresPageRequestParams = {
  /**
   * 课程名称
   */
  name?: string | number;
  /**
   * 课程分类id
   */
  courseClassificationId?: string | number;
  /**
   * 国家地区ID，上传最小一级的id
   */
  countryAreaId?: string | number;
  /**
   * 适用年龄
   */
  ageRangeCode?: string | number;
  suitAgeStart?: string | number;
  suitAgeEnd?: string | number;
  teachingMethodsCode?: string | number;
  /**
   * 授课方式
   */
  teachWayCode?: string | number;
  /**
   * 授课语言
   */
  teachLanguageCode?: string | number;
  /**
   * 地址搜索条件
   */
  addressLike?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 板块课程列表分页
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getListPagedCoursesBySector
 */
export type GetApiV1CoursesPagebysectorRequestParams = {
  /**
   * 课程名称
   */
  name?: string | number;
  /**
   * 课程分类id
   */
  courseClassificationId?: string | number;
  /**
   * 国家地区ID，上传最小一级的id
   */
  countryAreaId?: string | number;
  /**
   * 适用年龄
   */
  ageRangeCode?: string | number;
  suitAgeStart?: string | number;
  suitAgeEnd?: string | number;
  teachingMethodsCode?: string | number;
  /**
   * 授课方式
   */
  teachWayCode?: string | number;
  /**
   * 授课语言
   */
  teachLanguageCode?: string | number;
  /**
   * 地址搜索条件
   */
  addressLike?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * 课程名称关键词联想
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getNameSuggestions
 */
export type GetApiV1CoursesNameSuggestionsRequestParams = {
  /**
   * 搜索关键字
   */
  keyword?: string | number;
}

/**
 * 获取国家地区表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/国家地区表接口/listCourseClassifications
 */
export type GetApiV1CountryareaListRequestParams = {
  /**
   * 父级id
   */
  parentId?: string | number;
  /**
   * 多个名称用，隔开
   */
  names?: string | number;
  nameList?: string | number;
}

/**
 * undefined
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/treeLazy
 */
export type GetApiV1CityTreelazyRequestParams = {
  parentId?: string | number;
}

/**
 * undefined
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/search
 */
export type GetApiV1CitySearchRequestParams = {
  cityName?: string | number;
  cityState?: string | number;
  parentId?: string | number;
  needRoot?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * undefined
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/page
 */
export type GetApiV1CityPageRequestParams = {
  cityName?: string | number;
  cityState?: string | number;
  parentId?: string | number;
  needRoot?: string | number;
  /**
   * 页码
   */
  pageNum?: string | number;
  /**
   * 每页记录数
   */
  pageSize?: string | number;
}

/**
 * undefined
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/detail
 */
export type GetApiV1CityDetailRequestParams = {
  id?: string | number;
}

/**
 * 协议表表单数据
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/协议表接口小程序/getAgreementForm
 */
export type GetAgreementsByidFormRequestParams = {
  /**
   * 协议表ID
   */
  id: string | number;
}

/**
 * 删除优惠劵表
 * 
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/deleteCoupons
 */
export type DeleteWechatCouponsByidsRequestParams = {
  /**
   * 优惠劵表ID，多个以英文逗号(,)分割
   */
  ids: string | number;
}

