// Generated by Node.js script
// !!!!! DO NOT EDIT !!!!!

export type IObject = Record<string, any>

export interface ResultObject {
  code: string
  data: IObject
  msg: string
}

export interface CouponForm {
  /**
   * 主键
   */
  id: number
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 发放数量
   */
  number: number
  /**
   * 使用门槛(0无 其他数值为门槛金额)
   */
  useThreshold: number
  /**
   * 使用范围(1通用 2指定课程可用 3指定课程不可用)
   */
  useScope: number
  /**
   * 使用范围不为通用详情
   */
  userScopeDetail: string
  /**
   * 领取方式(1人工发放 2系统赠送)
   */
  receiveType: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 使用时间(1固定时间 2当日起几天 3次日起几天)
   */
  useRestrictedType: number
  /**
   * 使用时间天数
   */
  useRestrictedNum: number
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 修改人ID
   */
  updateBy: number
  deptId: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
  idPathList: string[]
}

export interface Result {
  code: string
  data: IObject
  msg: string
}

export interface UserForm {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 昵称
   */
  nickname: string
  /**
   * 手机号码
   */
  mobile: string
  /**
   * 性别
   */
  gender: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 邮箱
   */
  email: string
  /**
   * 用户状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 角色ID集合
   */
  roleIds: number[]
}

export interface UserChangePasswordForm {
  /**
   * 旧密码
   */
  srcPassword: string
  /**
   * 新密码
   */
  newPassword: string
  /**
   * 手机号
   */
  mobile: string
  /**
   * 邮箱
   */
  email: string
}

export interface RoleForm {
  /**
   * 角色ID
   */
  id: number
  /**
   * 角色名称
   */
  name: string
  /**
   * 角色编码
   */
  code: string
  /**
   * 排序
   */
  sort: number
  /**
   * 角色状态(1-正常；0-停用)
   */
  status: number
  /**
   * 数据权限
   */
  dataScope: number
}

export interface KeyValue {
  /**
   * 选项的值
   */
  key: string
  /**
   * 选项的标签
   */
  value: string
}

export interface MenuForm {
  /**
   * 菜单ID
   */
  id: number
  /**
   * 父菜单ID
   */
  parentId: number
  /**
   * 菜单名称
   */
  name: string
  /**
   * 菜单类型(1-菜单；2-目录；3-外链；4-按钮权限)
   */
  type: string
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径(vue页面完整路径，省略.vue后缀)
   */
  component: string
  /**
   * 权限标识
   */
  perm: string
  /**
   * 显示状态(1:显示;0:隐藏)
   */
  visible: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 菜单图标
   */
  icon: string
  /**
   * 跳转路径
   */
  redirect: string
  /**
   * 【菜单】是否开启页面缓存
   */
  keepAlive: number
  /**
   * 【目录】只有一个子路由是否始终显示
   */
  alwaysShow: number
  /**
   * 路由参数
   */
  params: KeyValue[]
  /**
   * 查询类型：1 查询所有  2 查询部分
   */
  queryType: number
}

export interface InstitutionForm {
  /**
   * 机构ID
   */
  id: number
  /**
   * 机构名称
   */
  name: string
  /**
   * 机构代码
   */
  institutionCode: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 机构负责人姓名
   */
  adminName: string
  /**
   * 机构负责人电话
   */
  adminMobile: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 类别，列表，上传字典institutionType的值
   */
  types: string[]
  /**
   * 简介
   */
  introduction: string
  /**
   * 图文详情
   */
  detail: string
  /**
   * 收款账户名
   */
  beneficiaryName: string
  /**
   * 收款账号
   */
  accountNumber: string
  /**
   * 收款银行
   */
  bankName: string
  /**
   * 收款二维码base64
   */
  paymentQrCode: string
  /**
   * 支付宝收款二维码base64
   */
  aliPaymentQrCode: string
  /**
   * 收款方式，具体枚举查看字典paymentType，wechat-微信收款码，alipay-支付宝收款码，bank-银行转账
   */
  paymentType: string
  /**
   * 结算类型(INSTITUTION:机构结算;TEACHER:讲师结算)
   */
  settlementType: string
  /**
   * 协议文件地址
   */
  protocolUrl: string
  /**
   * 等级
   */
  level: string
}

export interface SoaMemberCreateForm {
  /**
   * 机构id
   */
  institutionId: string
  /**
   * 类型，个人会员：2，企业会员：3，个人工商户：4
   */
  memberType: string
}

export interface ResultSOAMemberCreateDto {
  code: string
  data: SOAMemberCreateDto
  msg: string
}

export interface SOAMemberCreateDto {
  /**
   * 注册地址
   */
  url: string
}

export interface DictForm {
  /**
   * 字典ID
   */
  id: number
  /**
   * 类型编码
   */
  typeCode: string
  /**
   * 字典名称
   */
  name: string
  /**
   * 字典值
   */
  value: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序
   */
  sort: number
  /**
   * 字典备注
   */
  remark: string
}

export interface DictTypeForm {
  /**
   * 字典类型ID
   */
  id: number
  /**
   * 类型名称
   */
  name: string
  /**
   * 类型编码
   */
  code: string
  /**
   * 类型状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 备注
   */
  remark: string
}

export interface DeptForm {
  /**
   * 部门ID
   */
  id: number
  /**
   * 部门名称
   */
  name: string
  /**
   * 父部门ID
   */
  parentId: number
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
}

export interface CourseEvaluationForm {
  /**
   * 主键
   */
  id: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 总评分
   */
  totalScore: number
}

export interface CountryAreaForm {
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 是否在小程序展示(0-不展示，1-展示)
   */
  isShowMiniapp: number
  createTime: string
  createUser: string
  updateTime: string
  updateUser: string
  createUserName: string
  updateUserName: string
}

export interface AgreementForm {
  /**
   * 主键
   */
  id: string
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 是否展示
   */
  isDisplay: number
}

export interface OrderDetail {
  createTime: string
  updateTime: string
  id: string
  productId: number
  productCount: number
  courseId: string
  teacherId: string
  orderId: string
  productPrice: number
  productAmount: number
  courseName: string
  courseHoursCount: number
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
  /**
   * 主图
   */
  mainPicture: string
  productName: string
}

export interface OrderForm {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已支付；已完成)
   */
  status: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  createUserName: string
  orderDetails: OrderDetail[]
  coupons: UserCoupon[]
  refundAmount: number
  orderNumber: string
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 首次支付时间
   */
  firstPayTime: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 用户父级id，没有为父级自身id
   */
  userParentId: string
}

export interface UserCoupon {
  id: number
  userId: string
  userName: string
  couponId: number
  couponName: string
  couponPic: string
  couponThumbnail: string
  status: number
  useStatus: number
  createUser: string
  createTime: string
  updateUser: string
  updateTime: string
  delFlag: number
  /**
   * 订单id
   */
  orderId: string
}

export interface OrderAmountDto {
  id: string
  payAmount: number
}

export interface CommissionRate {
  /**
   * 开始天数
   */
  startDay: number
  endDay: number
  commissionRate: number
}

export interface CourseAddForm {
  /**
   * 课程名称
   */
  name: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 计费方式
   */
  priceMethod: string
  /**
   * 日期包细节
   */
  datePackageDetail: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  /**
   * 主图url
   */
  mainPicture: string
  /**
   * 轮播图url列表
   */
  publicityPictureUrls: string[]
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 最少开课人数，即开班人数
   */
  minClassCount: number
  /**
   * 最大人数
   */
  classCount: number
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 讲师列表
   */
  teachers: CourseTeacherRelationForm[]
  /**
   * 已学人数
   */
  studentsNumber: number
  /**
   * 推荐顺序
   */
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 是否属于世界名校(0:否,1:是)
   */
  isWorldFamousSchool: number
  /**
   * 是否在世界名校板块展示(0:否,1:是)
   */
  isShowWorldFamousSchool: number
  /**
   * 在世界名校板块的排序号
   */
  worldFamousSchoolSort: number
  /**
   * 是否属于国际课程(0:否,1:是)
   */
  isInternationalCourse: number
  /**
   * 是否在国际课程板块展示(0:否,1:是)
   */
  isShowInternationalCourse: number
  /**
   * 在国际课程板块的排序号
   */
  internationalCourseSort: number
  /**
   * 是否属于学术能力(0:否,1:是)
   */
  isAcademicAbility: number
  /**
   * 是否在学术能力板块展示(0:否,1:是)
   */
  isShowAcademicAbility: number
  /**
   * 在学术能力板块的排序号
   */
  academicAbilitySort: number
  /**
   * 是否属于综合素质(0:否,1:是)
   */
  isComprehensiveQuality: number
  /**
   * 是否在综合素质板块展示(0:否,1:是)
   */
  isShowComprehensiveQuality: number
  /**
   * 在综合素质板块的排序号
   */
  comprehensiveQualitySort: number
  /**
   * 搜索关键字
   */
  searchKeywords: string
}

export interface CourseTeacherRelationForm {
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 课程售价
   */
  price: number
  /**
   * 试听id
   */
  trialLessonId: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 新单佣金比例
   */
  newCommissionRate: number
  /**
   * 佣金比例
   */
  commissionRates: CommissionRate[]
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 备注信息
   */
  mark: string
}

export interface RichTextForm {
  /**
   * 主键
   */
  id: number
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 图片url
   */
  mainPicture: string
  /**
   * 是否展示
   */
  isDisplay: number
}

export interface BasePageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
}

export interface DataTeacherInfo {
  list: TeacherInfo[]
  total: number
}

export interface PageResultTeacherInfo {
  code: string
  data: DataTeacherInfo
  msg: string
}

export interface TeacherInfo {
  id: string
  userId: string
  name: string
  displayName: string
  englishName: string
  innerName: string
  nationality: string
  location: string
  countryAreas: string
  avatarUrl: string
  gender: string
  age: number
  teachingExperience: number
  birthday: string
  institutionId: number
  graduationSchool: string
  highestDegree: string
  major: string
  teachingMajor: string
  slogan: string
  experience: string
  createUser: string
  createTime: string
  updateUser: string
  updateTime: string
  delFlag: number
  sortNumber: number
  trialLessonId: string
  isShowExcellent: number
  tag: string
  evaluation: number
  mark: string
  goodSubject: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 管理人员所在的组织id
   */
  managerPersonDept: number
  titleCode: string
  titleName: string
  homeSlogan: string
  listSlogan: string
  goodFields: string
  searchKeywords: string
  isShowDetail: number
}

export interface TeacherInfoPageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 关键词，支持内部称呼，展示名称，导师简介，教学成果，备注信息
   */
  keys: string
  /**
   * 擅长领域
   */
  goodFields: string
  /**
   * 所属机构
   */
  institutionId: string
  /**
   * 创建人
   */
  createUser: string
}

export interface DataTeacherAdminInfoVo {
  list: TeacherAdminInfoVo[]
  total: number
}

export interface PageResultTeacherAdminInfoVo {
  code: string
  data: DataTeacherAdminInfoVo
  msg: string
}

export interface TeacherAdminInfoVo {
  /**
   * 讲师id
   */
  id: string
  /**
   * 内部称呼
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 擅长领域
   */
  goodFieldsStr: string
  goodFields: string
  /**
   * 创建人
   */
  createUserName: string
  /**
   * 教学成果
   */
  experience: string
  /**
   * 导师简介
   */
  teacherIntroduction: string
  /**
   * 所属机构
   */
  institutionName: string
  institutionId: number
  /**
   * 备注信息
   */
  mark: string
  titleCode: string
  /**
   * 讲师头衔
   */
  titleName: string
  /**
   * 机构级别
   */
  institutionLevel: string
}

export interface ProofMaterialsForm {
  /**
   * 身份证正反面列表
   */
  idCards: string[]
  /**
   * 社会保障卡，驾照或护照列表
   */
  socialProofMaterials: string[]
  /**
   * 学历证明列表
   */
  degreeCertificates: string[]
}

export interface TeacherEducationBackgroundForm {
  /**
   * 学校名称
   */
  schoolName: string
  /**
   * 所在国家
   */
  country: string
  /**
   * 专业名称
   */
  major: string
  /**
   * 学历
   */
  degree: string
  /**
   * 学习开始时间
   */
  studyStartDate: string
  /**
   * 学习结束时间
   */
  studyEndDate: string
}

export interface TeacherExperienceForm {
  /**
   * 职务名称
   */
  jobTitle: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 在职开始日期
   */
  startDay: string
  /**
   * 在职结束日期
   */
  endDay: string
  /**
   * 教学内容
   */
  teachingContent: string
  /**
   * 获得成就奖项
   */
  achievements: string
}

export interface TeacherInfoForm {
  id: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 内部姓名
   */
  innerName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 所授专业
   */
  teachingMajor: string
  /**
   * 宣传语
   */
  slogan: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 备注信息
   */
  mark: string
  /**
   * 讲师标签
   */
  tag: string
  /**
   * 擅长学科
   */
  goodSubject: string
  /**
   * 擅长领域
   */
  goodFields: string[]
  proofMaterials: ProofMaterialsForm
  introduction: TeacherIntroductionForm
  /**
   * 教育履历
   */
  experience: string
  /**
   * 教育履历
   */
  experienceList: TeacherExperienceForm[]
  /**
   * 教育背景列表
   */
  educationBackgroundList: TeacherEducationBackgroundForm[]
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 讲师titleCode
   */
  titleCode: string
  /**
   * 讲师titleName
   */
  titleName: string
  /**
   * 首页标语
   */
  homeSlogan: string
  /**
   * 列表标语
   */
  listSlogan: string
  /**
   * 搜索关键字
   */
  searchKeywords: string
  /**
   * 是否显示详情(0:不显示,1:显示)
   */
  isShowDetail: number
}

export interface TeacherIntroductionForm {
  /**
   * 详细介绍
   */
  detailedIntroduction: string
  /**
   * 视频介绍地址
   */
  videoIntroductionUrl: string
}

export interface TeacherSortNumberForm {
  /**
   * 要更新的讲师id
   */
  id: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
}

export interface DistributionQuery {
  /**
   * 待分配的用户
   */
  id: string
  /**
   * 待分配的用户的父级id
   */
  parentId: string
  /**
   * 分配的后台管理人员
   */
  userIds: string
}

export interface SplitToAccountForm {
  /**
   * 分账方账户id
   */
  accountId: string
  /**
   * 分账金额，单位元
   */
  splitAmount: number
}

export interface SplitCommissionForm {
  /**
   * 分账金额
   */
  splitAmount: number
}

export interface IPageSplitRecordVO {
  size: number
  records: SplitRecordVO[]
  total: number
  pages: number
  current: number
}

export interface ResultIPageSplitRecordVO {
  code: string
  data: IPageSplitRecordVO
  msg: string
}

export interface SplitRecordVO {
  /**
   * ID
   */
  id: number
  /**
   * 分账金额
   */
  amount: number
  /**
   * 备注
   */
  remark: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
}

export interface ResultMapStringSoaBalanceVO {
  code: string
  data: IObject
  msg: string
}

export interface SoaBalanceVO {
  /**
   * 冻结金额
   */
  freezeAmount: string
  /**
   * 可用金额
   */
  availableAmount: string
  /**
   * 总金额
   */
  totalAmount: string
}

export interface ConfirmPaymentReqParam {
  /**
   * 订单ID
   */
  orderId: string
}

export interface LevelRuleForm {
  /**
   * 会员等级规则ID
   */
  id: number
  /**
   * 等级
   */
  level: number
  /**
   * 等级名称
   */
  levelName: string
  /**
   * 等级积分
   */
  levelRule: number
  /**
   * 邀请加分比例
   */
  invitedRatio: number
  /**
   * 消费加分比例
   */
  consumeRatio: number
  /**
   * 积分兑换比例
   */
  exchangeRatio: number
  /**
   * 积分有效时长(天)
   */
  duration: number
  /**
   * 会员折扣
   */
  discount: number
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 能否查看课程价格，0不可以，1可以
   */
  isShowCoursePrice: number
  /**
   * 权益说明
   */
  interestsStatement: string
  /**
   * 积分获取
   */
  integralGain: string
  /**
   * 权益规则
   */
  equityRules: string
  /**
   * 可查看的课程数量，-1表示不限制
   */
  viewableCourseCount: number
  /**
   * 可查看的讲师数量，-1表示不限制
   */
  viewableTeacherCount: number
}

export interface UserCouponDto {
  userId: string
  idList: number[]
}

export interface CountryAreaPageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 分类名称
   */
  name: string
  /**
   * 分类名称
   */
  keywords: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 多个名称用，隔开
   */
  parentName: string
  /**
   * 多个名称用，隔开
   */
  names: string
}

export interface CountryAreaVO {
  /**
   * id
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 是否在小程序展示(0-不展示，1-展示)
   */
  isShowMiniapp: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 编辑人姓名
   */
  updateUserName: string
  /**
   * 子部门
   */
  children: CountryAreaVO[]
}

export interface ResultListCountryAreaVO {
  code: string
  data: CountryAreaVO[]
  msg: string
}

export interface ResultSOAPayDto {
  code: string
  data: SOAPayDto
  msg: string
}

export interface SOAPayDto {
  /**
   * 拉起地址
   */
  counterUrl: string
  /**
   * 是否支付完成
   */
  payment: boolean
  /**
   * 支付金额，单位分
   */
  fee: number
}

export interface OrderRefundForm {
  /**
   * 订单ID
   */
  orderId: string
  /**
   * 订单详情ID
   */
  detailId: string
  /**
   * 退款金额
   */
  refundAmount: number
  /**
   * 退款原因
   */
  reason: string
}

export interface OrderAdminAddForm {
  /**
   * 用户id
   */
  userId: string
  /**
   * 培训机构id
   */
  institutionId: string
  /**
   * 支付金额
   */
  payAmount: number
  orderDetails: OrderDetailAdminAddForm[]
  coupons: UserCoupon[]
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 支付时间
   */
  orderTime: string
}

export interface OrderDetailAdminAddForm {
  courseId: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 课程单价
   */
  productPrice: number
  /**
   * 课程金额
   */
  productAmount: number
  /**
   * 课时数量
   */
  courseHoursCount: number
}

export interface CourseSortNumberForm {
  /**
   * 要更新的讲师id
   */
  id: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
}

export interface CourseScheduleAddForm {
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 课程排班信息列表
   */
  schedules: CourseScheduleForm[]
}

export interface CourseScheduleForm {
  /**
   * 课程授课类型，oneByOne 一对一，bigCourse 大课
   */
  type: string
  /**
   * 课时id
   */
  scheduleId: number
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 预约状态
   */
  bookingStatus: string
  /**
   * 授课状态
   */
  teachingStatus: string
  /**
   * 课程主表id，如果学生约课就有该记录
   */
  courseId: string
  /**
   * 课程名称，如果学生约课就有该记录
   */
  courseName: string
  /**
   * 课程约课学生信息
   */
  students: CourseScheduleStudentForm[]
}

export interface CourseScheduleStudentForm {
  /**
   * 学生id，如果学生约课就有该记录
   */
  studentId: string
  /**
   * 课程名称，如果学生约课就有该记录
   */
  studentName: string
  bookingStatus: string
}

export interface CommissionSettlementForm {
  /**
   * 佣金ID
   */
  commissionId: string
  /**
   * 结算金额
   */
  amount: number
  /**
   * 结算模式，LAKALA：拉卡拉结算，NORMAL：线下普通结算
   */
  settlementMode: string
  /**
   * 结算场景
   */
  settlementScene: string
  /**
   * 账户类型
   */
  settlementType: string
  /**
   * 备注
   */
  remark: string
}

export interface SoaSettlementCheckDTO {
  /**
   * 验证码
   */
  captcha: string
}

export interface UserPointsDetailQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 会员id
   */
  userId: string
  year: string
  /**
   * 开始时间
   */
  createTimeStart: string
  /**
   * 结束时间
   */
  createTimeEnd: string
  /**
   * 积分类型
   */
  type: number
}

export interface DataUserPointsDetail {
  list: UserPointsDetail[]
  total: number
}

export interface PageResultUserPointsDetail {
  code: string
  data: DataUserPointsDetail
  msg: string
}

export interface UserPointsDetail {
  id: number
  /**
   * 用户id
   */
  userId: string
  /**
   * 用户名称
   */
  userName: string
  /**
   * 1, 注册获取积分 2, 消费获取积分 3, 积分兑换  4, 首次评价获取积分 5, 首次消费邀请人获取积分 6, 退款扣除积分
   */
  type: number
  /**
   * 积分数量
   */
  points: number
  /**
   * 创建时间
   */
  createTime: string
  createUser: string
  updateTime: string
  updateUser: string
  delFlag: number
  /**
   * 消费金额
   */
  amount: number
  /**
   * 描述信息
   */
  pointDesc: string
  expiresTime: string
  expiresFlag: number
  courseName: string
  orderId: string
  invitationCustId: string
  availablePoints: number
  consumeRatio: number
}

export interface StudentBookingConfigForm {
  /**
   * 主键
   */
  id: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师id对应的姓名
   */
  selectedTeacherName: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 机构id对应的机构名称
   */
  selectedInstitutionName: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id对应的课程名称
   */
  selectedCourseName: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 类型，0:全部学生，1:指定学生
   */
  type: string
  /**
   * 学生id，type为1时必填
   */
  studentId: string
  /**
   * 背景颜色
   */
  background: string
  /**
   * 上课地点
   */
  location: string
  /**
   * 备注
   */
  remark: string
}

export interface StudentBookingForm {
  /**
   * 主键
   */
  id: number
  /**
   * 学生id
   */
  studentId: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师id对应的姓名
   */
  selectedTeacherName: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 机构id
   */
  institutionId: string
  /**
   * 机构id对应的机构名称
   */
  selectedInstitutionName: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id对应的课程名称
   */
  selectedCourseName: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 背景颜色
   */
  background: string
  /**
   * 上课地点
   */
  location: string
  /**
   * 备注
   */
  remark: string
}

export interface StudentBookingCopyForm {
  /**
   * 要复制主键
   */
  idList: number[]
  /**
   * 学生id
   */
  studentId: string
  /**
   * 要拷贝到的开始时间
   */
  copyToStartTime: number
}

export interface ServedCustomerForm {
  /**
   * id
   */
  id: number
  /**
   * 服务过的客户中文名
   */
  chineseName: string
  /**
   * 服务过的客户英文名
   */
  englishName: string
  /**
   * logo地址
   */
  logoUrl: string
}

export interface SchoolForm {
  /**
   * id
   */
  id: number
  /**
   * 学校中文名
   */
  chineseName: string
  /**
   * 学校英文名
   */
  englishName: string
  /**
   * logo地址
   */
  logoUrl: string
}

export interface CourseVO {
  id: string
  name: string
}

export interface KsCustForm {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   * 积分
   */
  points: number
  courseId: string
  courseList: CourseVO[]
  addresList: string[]
  childNum: number
  /**
   * 邀请他人的邀请码
   */
  invitationCustCode: string
  invitationCust: string
  custId: string
  /**
   * 自身邀请码
   */
  invitationCode: string
  /**
   * 邀请时间
   */
  invitationTime: string
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
  /**
   * 是否白名单(0否 1是)
   */
  isWhitelist: number
  /**
   * 分销商
   */
  distributorsId: string
  /**
   * 是否可以获取积分 0 不能获取积分   1 可以获取积分
   */
  integralGain: number
  /**
   * 是否展示全部名称 0 脱敏显示   1 显示全称
   */
  displayFullName: number
  /**
   * 账号
   */
  username: string
}

export interface CustGoldDto {
  id: string
  addGold: number
}

export interface CustCouponQueryDto {
  couponIds: string[]
  id: string
}

export interface KsCustQueryDto {
  parentId: string
}

export interface KsCustChannelChangeDto {
  /**
   * 会员账号id
   */
  id: string
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
}

export interface KsCustAttachDto {
  /**
   * 目标父账号id
   */
  targetId: string
  /**
   * 待挂靠的会员id，挂靠后成为子账号
   */
  toAttachId: string
}

export interface ResultTeacherInfoForm {
  code: string
  data: TeacherInfoForm
  msg: string
}

export interface ResultListTeacherInfo {
  code: string
  data: TeacherInfo[]
  msg: string
}

export interface DataTeacherOptionsItemVO {
  list: TeacherOptionsItemVO[]
  total: number
}

export interface PageResultTeacherOptionsItemVO {
  code: string
  data: DataTeacherOptionsItemVO
  msg: string
}

export interface TeacherOptionsItemVO {
  /**
   * 讲师id
   */
  id: string
  /**
   * 讲师的用户id，可用于登陆后台系统
   */
  userId: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
}

export interface DataTeacherInfoVO {
  list: TeacherInfoVO[]
  total: number
}

export interface PageResultTeacherInfoVO {
  code: string
  data: DataTeacherInfoVO
  msg: string
}

export interface TeacherInfoVO {
  /**
   * 讲师id
   */
  id: string
  /**
   * 讲师的用户id，可用于登陆后台系统
   */
  userId: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 所在地
   */
  location: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 性别
   */
  gender: string
  /**
   * 年龄
   */
  age: number
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 所授专业
   */
  teachingMajor: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人
   */
  createUserName: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新人
   */
  updateUser: string
  /**
   * 更新人
   */
  updateUserName: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 讲师标签
   */
  tag: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 擅长学科
   */
  goodSubject: string
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 讲师titleCode
   */
  titleCode: string
  /**
   * 讲师titleName
   */
  titleName: string
  /**
   * 首页标语
   */
  homeSlogan: string
  /**
   * 列表标语
   */
  listSlogan: string
  /**
   * 讲师评分
   */
  evaluation: number
  goodFields: string[]
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 机构级别
   */
  institutionLevel: string
}

export interface DataMemberRuleVO {
  list: MemberRuleVO[]
  total: number
}

export interface MemberRuleVO {
  /**
   * 会员等级规则ID
   */
  id: number
  /**
   * 会员等级规则ID
   */
  level: number
  /**
   * 会员等级名称
   */
  levelName: string
  /**
   * 会员等级规则ID
   */
  levelRule: number
  /**
   * 邀请加分比例
   */
  invitedRatio: number
  /**
   * 消费加分比例
   */
  consumeRatio: number
  /**
   * 积分兑换比例
   */
  exchangeRatio: number
  /**
   * 积分有效时长(天)
   */
  duration: number
  /**
   * 会员折扣
   */
  discount: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 可查看的课程数量，-1表示不限制
   */
  viewableCourseCount: number
  /**
   * 可查看的讲师数量，-1表示不限制
   */
  viewableTeacherCount: number
  /**
   * 能否查看课程价格，0不可以，1可以
   */
  isShowCoursePrice: number
  /**
   * 权益说明
   */
  interestsStatement: string
  /**
   * 积分获取
   */
  integralGain: string
  /**
   * 权益规则
   */
  equityRules: string
}

export interface PageResultMemberRuleVO {
  code: string
  data: DataMemberRuleVO
  msg: string
}

export interface BaseDto {
  level: number
  name: string
}

export interface ResultListBaseDto {
  code: string
  data: BaseDto[]
  msg: string
}

export interface ResultCouponForm {
  code: string
  data: CouponForm
  msg: string
}

export interface CouponPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 使用限制类型(1:限制使用时间;0:限制使用天数)
   */
  useRestrictedType: number
  /**
   * 满足优惠金额
   */
  amountMet: number
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  /**
   * 可用课程
   */
  courseId: string
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 修改人ID
   */
  updateBy: number
  deptId: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
}

export interface DataCouponPageVO {
  list: CouponPageVO[]
  total: number
}

export interface PageResultCouponPageVO {
  code: string
  data: DataCouponPageVO
  msg: string
}

export interface ResultUserForm {
  code: string
  data: UserForm
  msg: string
}

export interface DataUserPageVO {
  list: UserPageVO[]
  total: number
}

export interface PageResultUserPageVO {
  code: string
  data: DataUserPageVO
  msg: string
}

export interface UserPageVO {
  /**
   * 用户ID
   */
  id: string
  /**
   * 用户名
   */
  username: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 手机号
   */
  mobile: string
  /**
   * 性别
   */
  genderLabel: string
  /**
   * 用户头像地址
   */
  avatar: string
  /**
   * 用户邮箱
   */
  email: string
  /**
   * 用户状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 部门名称
   */
  deptName: string
  /**
   * 角色名称，多个使用英文逗号(,)分割
   */
  roleNames: string
  /**
   * 创建时间
   */
  createTime: string
}

export interface ResultUserInfoVO {
  code: string
  data: UserInfoVO
  msg: string
}

export interface UserDeptVO {
  /**
   * 部门或机构id，根据isInstitution而定
   */
  id: number
  /**
   * 部门或机构名称，根据isInstitution而定
   */
  name: string
  /**
   * 是否机构
   */
  isInstitution: boolean
}

export interface UserInfoVO {
  /**
   * 用户ID
   */
  userId: string
  /**
   * 用户名
   */
  username: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 头像地址
   */
  avatar: string
  /**
   * 用户角色编码集合
   */
  roles: string[]
  /**
   * 用户权限标识集合
   */
  perms: string[]
  dept: UserDeptVO
}

export interface ResultListSysUser {
  code: string
  data: SysUser[]
  msg: string
}

export interface SysUser {
  createTime: string
  updateTime: string
  id: string
  username: string
  nickname: string
  gender: number
  password: string
  deptId: number
  avatar: string
  mobile: string
  status: number
  email: string
  deleted: number
  invitationCode: string
}

export interface ResultListLong {
  code: string
  data: number[]
  msg: string
}

export interface ResultRoleForm {
  code: string
  data: RoleForm
  msg: string
}

export interface DataRolePageVO {
  list: RolePageVO[]
  total: number
}

export interface PageResultRolePageVO {
  code: string
  data: DataRolePageVO
  msg: string
}

export interface RolePageVO {
  /**
   * 角色ID
   */
  id: number
  /**
   * 角色名称
   */
  name: string
  /**
   * 角色编码
   */
  code: string
  /**
   * 角色状态
   */
  status: number
  /**
   * 排序
   */
  sort: number
  createTime: string
  updateTime: string
}

export interface Option {
  /**
   * 选项的值
   */
  value: IObject
  /**
   * 选项的标签
   */
  label: string
}

export interface OptionObject {
  /**
   * 选项的值
   */
  value: IObject
  /**
   * 选项的标签
   */
  label: string
  /**
   * 子选项列表
   */
  children: Option[]
}

export interface ResultListOptionObject {
  code: string
  data: OptionObject[]
  msg: string
}

export interface MenuVO {
  /**
   * 菜单ID
   */
  id: number
  /**
   * 父菜单ID
   */
  parentId: number
  /**
   * 菜单名称
   */
  name: string
  /**
   * 菜单类型
   */
  type: string
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径
   */
  component: string
  /**
   * 菜单排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 菜单是否可见(1:显示;0:隐藏)
   */
  visible: number
  /**
   * ICON
   */
  icon: string
  /**
   * 跳转路径
   */
  redirect: string
  /**
   * 按钮权限标识
   */
  perm: string
  /**
   * 子菜单
   */
  children: MenuVO[]
  /**
   * 查询类型：1 查询所有  2 查询部分
   */
  queryType: number
}

export interface ResultListMenuVO {
  code: string
  data: MenuVO[]
  msg: string
}

export interface ResultMenuForm {
  code: string
  data: MenuForm
  msg: string
}

export interface Meta {
  /**
   * 路由title
   */
  title: string
  /**
   * ICON
   */
  icon: string
  /**
   * 是否隐藏(true-是 false-否)
   */
  hidden: boolean
  /**
   * 拥有路由权限的角色编码
   */
  roles: string[]
  /**
   * 【菜单】是否开启页面缓存
   */
  keepAlive: boolean
  /**
   * 【目录】只有一个子路由是否始终显示
   */
  alwaysShow: boolean
  /**
   * 路由参数
   */
  params: IObject
}

export interface ResultListRouteVO {
  code: string
  data: RouteVO[]
  msg: string
}

export interface RouteVO {
  /**
   * 路由路径
   */
  path: string
  /**
   * 组件路径
   */
  component: string
  /**
   * 跳转链接
   */
  redirect: string
  /**
   * 路由名称
   */
  name: string
  meta: Meta
  /**
   * 子路由列表
   */
  children: RouteVO[]
}

export interface InstitutionVO {
  /**
   * 机构ID
   */
  id: number
  /**
   * 机构名称
   */
  name: string
  /**
   * 机构代号
   */
  institutionCode: string
  /**
   * 排序
   */
  sort: number
  /**
   * 管理者id，可用于登陆
   */
  adminId: string
  /**
   * 状态(1:启用；0:禁用)
   */
  status: number
  /**
   * 详细地址
   */
  address: string
  /**
   * 类别，列表，上传字典institutionType的值
   */
  types: string[]
  /**
   * 简介
   */
  introduction: string
  /**
   * 图文详情
   */
  detail: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 修改时间
   */
  updateTime: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 级别，取字典InstitutionLevel
   */
  level: string
  /**
   * 创建人名称
   */
  createByName: string
}

export interface ResultListInstitutionVO {
  code: string
  data: InstitutionVO[]
  msg: string
}

export interface ResultString {
  code: string
  data: string
  msg: string
}

export interface InstitutionDetailVO {
  /**
   * 机构ID
   */
  id: number
  /**
   * 机构名称
   */
  name: string
  /**
   * 机构代码
   */
  institutionCode: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  /**
   * 排序(数字越小排名越靠前)
   */
  sort: number
  /**
   * 机构负责人姓名
   */
  adminName: string
  /**
   * 机构负责人电话
   */
  adminMobile: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 类别，列表，上传字典institutionType的值
   */
  types: string[]
  /**
   * 简介
   */
  introduction: string
  /**
   * 图文详情
   */
  detail: string
  /**
   * 收款账户名
   */
  beneficiaryName: string
  /**
   * 收款账号
   */
  accountNumber: string
  /**
   * 收款银行
   */
  bankName: string
  /**
   * 收款二维码base64
   */
  paymentQrCode: string
  /**
   * 支付宝收款二维码base64
   */
  aliPaymentQrCode: string
  /**
   * 收款方式，具体枚举查看字典paymentType，wechat-微信收款码，alipay-支付宝收款码，bank-银行转账
   */
  paymentType: string
  /**
   * 结算类型(INSTITUTION:机构结算;TEACHER:讲师结算)
   */
  settlementType: string
  /**
   * 协议文件地址
   */
  protocolUrl: string
  /**
   * 等级
   */
  level: string
}

export interface ResultInstitutionDetailVO {
  code: string
  data: InstitutionDetailVO
  msg: string
}

export interface ResultListSysDept {
  code: string
  data: SysDept[]
  msg: string
}

export interface SysDept {
  createTime: string
  updateTime: string
  id: number
  name: string
  parentId: number
  treePath: string
  sort: number
  status: number
  deleted: number
  createBy: string
  updateBy: string
  isInstitution: number
  provinceCode: string
  cityCode: string
  countyCode: string
  address: string
  types: string
  introduction: string
  detail: string
  institutionCode: string
  adminName: string
  adminMobile: string
  beneficiaryName: string
  accountNumber: string
  bankName: string
  paymentQrCode: string
  aliPaymentQrCode: string
  paymentType: string
  settlementType: string
  isNewOrder: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 管理人员所在的组织id
   */
  managerPersonDept: number
  protocolUrl: string
  level: string
}

export interface ResultDictForm {
  code: string
  data: DictForm
  msg: string
}

export interface ResultDictTypeForm {
  code: string
  data: DictTypeForm
  msg: string
}

export interface DataDictTypePageVO {
  list: DictTypePageVO[]
  total: number
}

export interface DictTypePageVO {
  /**
   * 字典类型ID
   */
  id: number
  /**
   * 类型名称
   */
  name: string
  /**
   * 类型编码
   */
  code: string
  /**
   * 状态：1:启用;0:禁用
   */
  status: number
  remark: string
}

export interface PageResultDictTypePageVO {
  code: string
  data: DataDictTypePageVO
  msg: string
}

export interface DataDictPageVO {
  list: DictPageVO[]
  total: number
}

export interface DictPageVO {
  /**
   * 字典ID
   */
  id: number
  /**
   * 字典名称
   */
  name: string
  /**
   * 字典值
   */
  value: string
  /**
   * 状态(1:启用;0:禁用)
   */
  status: number
  defaulted: number
  remark: string
}

export interface PageResultDictPageVO {
  code: string
  data: DataDictPageVO
  msg: string
}

export interface DeptVO {
  /**
   * 部门ID
   */
  id: number
  /**
   * 父部门ID
   */
  parentId: number
  /**
   * 部门名称
   */
  name: string
  /**
   * 排序
   */
  sort: number
  /**
   * 状态(1:启用；0:禁用)
   */
  status: number
  /**
   * 子部门
   */
  children: DeptVO[]
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 修改时间
   */
  updateTime: string
}

export interface ResultListDeptVO {
  code: string
  data: DeptVO[]
  msg: string
}

export interface ResultDeptForm {
  code: string
  data: DeptForm
  msg: string
}

export interface ResultCourseEvaluationForm {
  code: string
  data: CourseEvaluationForm
  msg: string
}

export interface CourseEvaluationPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id
   */
  courseName: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 总评分
   */
  totalScore: number
}

export interface DataCourseEvaluationPageVO {
  list: CourseEvaluationPageVO[]
  total: number
}

export interface PageResultCourseEvaluationPageVO {
  code: string
  data: DataCourseEvaluationPageVO
  msg: string
}

export interface ResultCountryAreaForm {
  code: string
  data: CountryAreaForm
  msg: string
}

export interface CountryAreaPageVO {
  /**
   * id
   */
  id: string
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 父级id
   */
  parentId: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 是否在小程序展示(0-不展示，1-展示)
   */
  isShowMiniapp: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 编辑人姓名
   */
  updateUserName: string
}

export interface DataCountryAreaPageVO {
  list: CountryAreaPageVO[]
  total: number
}

export interface PageResultCountryAreaPageVO {
  code: string
  data: DataCountryAreaPageVO
  msg: string
}

export interface ResultAgreementForm {
  code: string
  data: AgreementForm
  msg: string
}

export interface AgreementPageVO {
  /**
   * 主键
   */
  id: string
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 是否展示
   */
  isDisplay: number
}

export interface DataAgreementPageVO {
  list: AgreementPageVO[]
  total: number
}

export interface PageResultAgreementPageVO {
  code: string
  data: DataAgreementPageVO
  msg: string
}

export interface OrderRefundVO {
  /**
   * 退款记录ID
   */
  id: string
  /**
   * 订单ID
   */
  orderId: string
  /**
   * 订单详情ID
   */
  detailId: string
  /**
   * 退款金额
   */
  refundAmount: number
  /**
   * 退款原因
   */
  reason: string
  /**
   * 退款状态(1:待退款;2:已退款;3:已取消;4:已拒绝)
   */
  status: number
  /**
   * 备注
   */
  remark: string
  /**
   * 申请人ID
   */
  applyUser: string
  /**
   * 申请人姓名
   */
  applyUserName: string
  /**
   * 申请时间
   */
  applyTime: string
  /**
   * 审批人ID
   */
  approveUser: string
  /**
   * 审批人姓名
   */
  approveUserName: string
  /**
   * 审批时间
   */
  approveTime: string
}

export interface ResultListOrderRefundVO {
  code: string
  data: OrderRefundVO[]
  msg: string
}

export interface OrderDetailVO {
  id: string
  productId: number
  productCount: number
  courseId: string
  courseName: string
  teacherId: string
  teacherName: string
  productPrice: number
  productAmount: number
  courseHoursCount: number
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类全路径
   */
  idPath: string
  /**
   * 主图
   */
  mainPicture: string
  productName: string
}

export interface OrderVO {
  /**
   * 主键
   */
  id: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 用户父级id，没有为父级自身id
   */
  userParentId: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 状态(1:待支付;2:已支付；已完成)
   */
  status: number
  /**
   * 结算状态(1:未结算;2:部分结算;3:已结算)
   */
  settlementStatus: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
  createUserName: string
  refundAmount: number
  orderNumber: string
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 首次支付时间
   */
  firstPayTime: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 订单详情列表
   */
  orderDetails: OrderDetailVO[]
}

export interface ResultOrderVO {
  code: string
  data: OrderVO
  msg: string
}

export interface ResultOrderForm {
  code: string
  data: OrderForm
  msg: string
}

export interface DataOrderBO {
  list: OrderBO[]
  total: number
}

export interface OrderBO {
  id: string
  userId: string
  userName: string
  userPhone: string
  deptId: string
  institutionName: string
  orderAmount: number
  payAmount: number
  discountAmount: number
  status: number
  settlementStatus: number
  payWay: number
  deleted: number
  orderTime: string
  createTime: string
  firstPayTime: string
  updateTime: string
  createUser: string
  updateUser: string
  createUserName: string
  /**
   * 已退款金额
   */
  refundAmount: number
  /**
   * 待退款金额
   */
  pendingRefundAmount: number
  orderNumber: string
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 用户父级id，没有为父级自身id
   */
  userParentId: string
}

export interface PageResultOrderBO {
  code: string
  data: DataOrderBO
  msg: string
}

export interface ChannelOrderVO {
  /**
   * 订单号
   */
  orderNumber: string
  /**
   * 订单昵称
   */
  userName: string
  /**
   * 手机号
   */
  userPhone: string
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 结算状态
   */
  settlementStatus: number
  /**
   * 佣金比例
   */
  commissionRate: number
  /**
   * 渠道佣金
   */
  channelAmount: number
}

export interface DataChannelOrderVO {
  list: ChannelOrderVO[]
  total: number
}

export interface PageResultChannelOrderVO {
  code: string
  data: DataChannelOrderVO
  msg: string
}

export interface ResultCourseAddForm {
  code: string
  data: CourseAddForm
  msg: string
}

export interface ResultBoolean {
  code: string
  data: boolean
  msg: string
}

export interface CourseAdminPageVO {
  id: string
  trialLessonId: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 课班数量
   */
  classCount: number
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 课程售价
   */
  price: number
  /**
   * 审核原因
   */
  auditReason: string
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 机构ID
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 部门Fullid
   */
  treePath: string
  /**
   * 审核状态((1:审核通过;0:待审核；2审核不通过))
   */
  status: number
  /**
   * 逻辑删除标识(0:未删除;1:已删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  createUser: string
  updateUser: string
  createUserName: string
  updateUserName: string
  mainPicture: string
  /**
   * 上架状态((2：已下架1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  publicityPictureUrls: string[]
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  commissionRate: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
}

export interface DataCourseAdminPageVO {
  list: CourseAdminPageVO[]
  total: number
}

export interface PageResultCourseAdminPageVO {
  code: string
  data: DataCourseAdminPageVO
  msg: string
}

export interface CourseForm {
  id: string
  trialLessonId: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 开课人数
   */
  classCount: number
  /**
   * 课班数量
   */
  minClassCount: number
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  /**
   * 课程售价
   */
  price: number
  /**
   * 审核原因
   */
  auditReason: string
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 部门Fullid
   */
  treePath: string
  /**
   * 审核状态((1:已审核;0:待审核))
   */
  status: number
  /**
   * 逻辑删除标识(0:未删除;1:已删除)
   */
  deleted: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  createUser: string
  updateUser: string
  createUserName: string
  updateUserName: string
  mainPicture: string
  publicityPictureUrls: string[]
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  sortNumber: number
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  commissionRate: number
  /**
   * 新单佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  newCommissionRate: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 经度
   */
  longitude: string
  /**
   * 纬度
   */
  latitude: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 是否属于世界名校(0:否,1:是)
   */
  isWorldFamousSchool: number
  /**
   * 是否在世界名校板块展示(0:否,1:是)
   */
  isShowWorldFamousSchool: number
  /**
   * 在世界名校板块的排序号
   */
  worldFamousSchoolSort: number
  /**
   * 是否属于国际课程(0:否,1:是)
   */
  isInternationalCourse: number
  /**
   * 是否在国际课程板块展示(0:否,1:是)
   */
  isShowInternationalCourse: number
  /**
   * 在国际课程板块的排序号
   */
  internationalCourseSort: number
  /**
   * 是否属于学术能力(0:否,1:是)
   */
  isAcademicAbility: number
  /**
   * 是否在学术能力板块展示(0:否,1:是)
   */
  isShowAcademicAbility: number
  /**
   * 在学术能力板块的排序号
   */
  academicAbilitySort: number
  /**
   * 是否属于综合素质(0:否,1:是)
   */
  isComprehensiveQuality: number
  /**
   * 是否在综合素质板块展示(0:否,1:是)
   */
  isShowComprehensiveQuality: number
  /**
   * 在综合素质板块的排序号
   */
  comprehensiveQualitySort: number
}

export interface ResultCourseForm {
  code: string
  data: CourseForm
  msg: string
}

export interface CourseBO {
  id: string
  name: string
  ageRangeCode: string
  suitAgeStart: number
  suitAgeEnd: number
  institutionId: number
  institutionName: string
  classHourseNumber: number
  teachLanguageCode: string
  teachWayCode: string
  classCount: number
  minClassCount: number
  otherInstructions: string
  specialLabel: string
  teachingCharacteristics: string
  courseFeatures: string
  courseDescription: string
  purchaseNotice: string
  startTime: string
  courseClassificationId: string
  goldContent: number
  comprehensiveEvaluation: number
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  price: number
  auditReason: string
  deptId: number
  treePath: string
  status: number
  deleted: number
  createTime: string
  updateTime: string
  createUser: string
  updateUser: string
  createUserName: string
  updateUserName: string
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 城市名称
   */
  cityName: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 区县名称
   */
  countyName: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 区县名称
   */
  provinceName: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  /**
   * 详细地址
   */
  address: string
  publicityPictureUrls: string[]
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 学习人数
   */
  studentsNumber: number
  sortNumber: number
  trialLessonId: string
  /**
   * 适用条件
   */
  applicableConditions: string
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
}

export interface ResultListCourseBO {
  code: string
  data: CourseBO[]
  msg: string
}

export interface CourseTeacherPageVO {
  id: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 计费方式
   */
  priceMethod: string
  /**
   * 日期包细节
   */
  datePackageDetail: string
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 主图url
   */
  mainPicture: string
  /**
   * 轮播图url列表
   */
  publicityPictureUrls: string[]
  /**
   * 讲师列表
   */
  teachers: CourseTeacherRelationForm[]
}

export interface DataCourseTeacherPageVO {
  list: CourseTeacherPageVO[]
  total: number
}

export interface PageResultCourseTeacherPageVO {
  code: string
  data: DataCourseTeacherPageVO
  msg: string
}

export interface CourseAuditRecord {
  createTime: string
  updateTime: string
  id: number
  courseId: string
  auditReason: string
  auditStatus: number
  createUser: string
  createUserName: string
}

export interface ResultListCourseAuditRecord {
  code: string
  data: CourseAuditRecord[]
  msg: string
}

export interface Course {
  createTime: string
  updateTime: string
  id: string
  name: string
  ageRangeCode: string
  suitAgeStart: number
  suitAgeEnd: number
  classHourseNumber: number
  teachLanguageCode: string
  teachWayCode: string
  priceMethod: string
  datePackageDetail: string
  classCount: number
  minClassCount: number
  otherInstructions: string
  specialLabel: string
  teachingCharacteristics: string
  courseFeatures: string
  courseDescription: string
  purchaseNotice: string
  startTime: string
  courseClassificationId: string
  goldContent: number
  comprehensiveEvaluation: number
  isShowPrice: number
  price: number
  commissionRate: number
  newCommissionRate: number
  institutionId: number
  deptId: number
  treePath: string
  status: number
  deleted: number
  createUser: string
  updateUser: string
  createUserName: string
  updateUserName: string
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 城市编码
   */
  cityCode: string
  /**
   * 区县编码
   */
  countyCode: string
  /**
   * 省份编码
   */
  provinceCode: string
  /**
   * 省市区名称
   */
  addressMargeName: string
  countryAreas: string
  /**
   * 详细地址
   */
  address: string
  publicityPicture: string
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  studentsNumber: number
  sortNumber: number
  trialLessonId: string
  /**
   * 适用条件
   */
  applicableConditions: string
  singleClassDuration: number
  /**
   * 购买数量
   */
  buyCount: string
  longitude: string
  latitude: string
  /**
   * 是否属于世界名校
   */
  isWorldFamousSchool: number
  /**
   * 是否在世界名校板块展示
   */
  isShowWorldFamousSchool: number
  /**
   * 在世界名校板块的排序号
   */
  worldFamousSchoolSort: number
  /**
   * 是否属于国际课程
   */
  isInternationalCourse: number
  /**
   * 是否在国际课程板块展示
   */
  isShowInternationalCourse: number
  /**
   * 在国际课程板块的排序号
   */
  internationalCourseSort: number
  /**
   * 是否属于学术能力
   */
  isAcademicAbility: number
  /**
   * 是否在学术能力板块展示
   */
  isShowAcademicAbility: number
  /**
   * 在学术能力板块的排序号
   */
  academicAbilitySort: number
  /**
   * 是否属于综合素质
   */
  isComprehensiveQuality: number
  /**
   * 是否在综合素质板块展示
   */
  isShowComprehensiveQuality: number
  /**
   * 在综合素质板块的排序号
   */
  comprehensiveQualitySort: number
  searchKeywords: string
  mark: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 管理人员所在的组织id
   */
  managerPersonDept: number
}

export interface DataCourse {
  list: Course[]
  total: number
}

export interface PageResultCourse {
  code: string
  data: DataCourse
  msg: string
}

export interface ResultListCourse {
  code: string
  data: Course[]
  msg: string
}

export interface ResultListCourseScheduleForm {
  code: string
  data: CourseScheduleForm[]
  msg: string
}

export interface CommissionSettlementVO {
  /**
   * 结算记录ID
   */
  id: number
  /**
   * 佣金ID
   */
  commissionId: number
  /**
   * 结算金额
   */
  settlementAmount: number
  /**
   * 结算模式，LAKALA：拉卡拉结算，NORMAL：线下普通结算
   */
  settlementMode: string
  /**
   * 结算场景
   */
  settlementScene: string
  /**
   * 结算类型
   */
  settlementType: string
  /**
   * 结算对象ID
   */
  settlementObjectId: string
  /**
   * 结算对象名称
   */
  settlementObjectName: string
  /**
   * 结算状态
   */
  settlementStatus: string
  /**
   * 结算时间
   */
  settlementTime: string
  /**
   * 失败原因
   */
  failureReason: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 备注
   */
  remark: string
}

export interface ResultListCommissionSettlementVO {
  code: string
  data: CommissionSettlementVO[]
  msg: string
}

export interface CommissionSettlementInfoVO {
  /**
   * 佣金ID
   */
  id: number
  /**
   * 机构ID
   */
  institutionId: number
  /**
   * 结算类型
   */
  settlementType: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 讲师ID
   */
  teacherId: number
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 课程ID
   */
  courseId: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 订单号
   */
  orderNo: string
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 佣金金额
   */
  commissionAmount: number
  /**
   * 佣金比例
   */
  commissionRate: number
  /**
   * 结算状态(1:未结算;2:部分结算;3:已结算)
   */
  settlementStatus: string
  /**
   * 结算时间
   */
  settlementTime: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 拉卡拉会员号
   */
  soaMemberNo: string
  /**
   * 拉卡拉银行卡编号
   */
  soaCardNo: string
  /**
   * 拉卡拉会员状态，1-有效，10-锁定，20-关闭，99-待审核
   */
  soaMemberState: string
  /**
   * 已结算金额
   */
  settledAmount: number
  /**
   * 剩余可结算金额
   */
  remainingAmount: number
}

export interface ResultCommissionSettlementInfoVO {
  code: string
  data: CommissionSettlementInfoVO
  msg: string
}

export interface CommissionVO {
  /**
   * 佣金信息id
   */
  id: number
  /**
   * 订单id
   */
  orderId: string
  /**
   * 机构ID
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 佣金比例
   */
  commissionRate: number
  /**
   * 订单金额
   */
  orderAmount: number
  /**
   * 佣金金额
   */
  commissionAmount: number
  /**
   * 结算状态
   */
  settlementStatus: string
  /**
   * 用户姓名
   */
  userName: string
  /**
   * 用户手机号
   */
  userPhone: string
  /**
   * 已结算金额
   */
  settledAmount: number
}

export interface DataCommissionVO {
  list: CommissionVO[]
  total: number
}

export interface PageResultCommissionVO {
  code: string
  data: DataCommissionVO
  msg: string
}

export interface ResultStudentBookingConfigForm {
  code: string
  data: StudentBookingConfigForm
  msg: string
}

export interface DataStudentBookingConfigForm {
  list: StudentBookingConfigForm[]
  total: number
}

export interface PageResultStudentBookingConfigForm {
  code: string
  data: DataStudentBookingConfigForm
  msg: string
}

export interface ResultStudentBookingForm {
  code: string
  data: StudentBookingForm
  msg: string
}

export interface ResultListStudentBookingForm {
  code: string
  data: StudentBookingForm[]
  msg: string
}

export interface DataServedCustomerForm {
  list: ServedCustomerForm[]
  total: number
}

export interface PageResultServedCustomerForm {
  code: string
  data: DataServedCustomerForm
  msg: string
}

export interface DataSchoolForm {
  list: SchoolForm[]
  total: number
}

export interface PageResultSchoolForm {
  code: string
  data: DataSchoolForm
  msg: string
}

export interface ResultRichTextForm {
  code: string
  data: RichTextForm
  msg: string
}

export interface DataRichTextPageVO {
  list: RichTextPageVO[]
  total: number
}

export interface PageResultRichTextPageVO {
  code: string
  data: DataRichTextPageVO
  msg: string
}

export interface RichTextPageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 标题
   */
  title: string
  /**
   * 内容
   */
  contentData: string
  /**
   * 图片url
   */
  mainPicture: string
  /**
   * 是否展示
   */
  isDisplay: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 修改人ID
   */
  updateUser: string
}

export interface FeedbackForm {
  /**
   * 主键
   */
  id: number
  /**
   * 意见反馈
   */
  feedbackContent: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeName: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeCode: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人ID
   */
  createUserName: string
}

export interface ResultFeedbackForm {
  code: string
  data: FeedbackForm
  msg: string
}

export interface DataFeedback {
  list: Feedback[]
  total: number
}

export interface Feedback {
  createTime: string
  updateTime: string
  id: number
  feedbackContent: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeName: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeCode: string
  createUser: string
  createUserName: string
}

export interface PageResultFeedback {
  code: string
  data: DataFeedback
  msg: string
}

export interface ResultKsCustForm {
  code: string
  data: KsCustForm
  msg: string
}

export interface DataKsCustPageVO {
  list: KsCustPageVO[]
  total: number
}

export interface KsCustPageVO {
  /**
   * 用户id
   */
  id: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 性别
   */
  gender: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 父级id
   */
  parentId: string
  registerFrom: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 子账户人数
   */
  childNum: number
  /**
   * 常住地
   */
  addres: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
  deleted: number
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 生日
   */
  birthday: string
  /**
   * 用户等级
   */
  level: number
  /**
   * wechat openID
   */
  openId: string
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 希望学习的课程
   */
  courses: string
  courseId: string
  /**
   * 总积分
   */
  points: number
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
  /**
   * 用户来源取自字典小程序码用途
   */
  userSource: string
  /**
   * 邀请人名称
   */
  invitationCust: string
  /**
   * 黑名单  0 否  1  是
   */
  disallowLogin: number
  /**
   * 分销商
   */
  distributorsId: string
  /**
   * 是否可以获取积分 0 不能获取积分   1 可以获取积分
   */
  integralGain: number
  /**
   * 是否展示全部名称 0 脱敏显示   1 显示全称
   */
  displayFullName: number
  /**
   * 账号
   */
  username: string
}

export interface PageResultKsCustPageVO {
  code: string
  data: DataKsCustPageVO
  msg: string
}

export interface KsCustBaseDto {
  id: string
  name: string
  nickName: string
  phone: string
}

export interface ResultListKsCustBaseDto {
  code: string
  data: KsCustBaseDto[]
  msg: string
}

export interface KsCust {
  id: string
  avatar: string
  nickname: string
  realName: string
  gender: string
  mark: string
  parentId: string
  registerFrom: string
  phone: string
  balance: number
  goldBalance: number
  integralBalance: number
  status: boolean
  preferenceColor: string
  familyMemberCount: number
  addres: string
  wxProfile: string
  deleted: number
  createTime: string
  updateTime: string
  birthday: string
  level: number
  points: number
  effectivePoints: number
  availablePoints: number
  expiredPoints: number
  usedPoints: number
  openId: string
  hobbies: string
  courses: string
  courseId: string
  childNum: number
  invitationCode: string
  custId: string
  /**
   * 邀请时间
   */
  invitationTime: string
  channel: string
  managerPerson: string
  createUser: string
  createUserName: string
  unlimitCode: string
  /**
   * 用户来源取自字典小程序码用途
   */
  userSource: string
  /**
   * 邀请人名称
   */
  invitationCust: string
  /**
   * 邀请人类型  1 员工  2 会员
   */
  invitationType: number
  /**
   * 黑名单  0 否  1  是
   */
  disallowLogin: number
  isWhitelist: number
  /**
   * 邀请人部门id
   */
  invitationCustDeptId: number
  /**
   * 分销商
   */
  distributorsId: string
  /**
   * 是否可以获取积分 0 不能获取积分   1 可以获取积分
   */
  integralGain: number
  /**
   * 是否展示全部名称 0 脱敏显示   1 显示全称
   */
  displayFullName: number
  /**
   * 账号
   */
  username: string
}

export interface ResultListKsCust {
  code: string
  data: KsCust[]
  msg: string
}

export interface ChannelKsCustVO {
  id: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 状态 1为正常，0为禁止
   */
  status: boolean
}

export interface DataChannelKsCustVO {
  list: ChannelKsCustVO[]
  total: number
}

export interface PageResultChannelKsCustVO {
  code: string
  data: DataChannelKsCustVO
  msg: string
}

