// Generated by Node.js script
// !!!!! DO NOT EDIT !!!!!

import type {
  AccountReqParam,
  AgreementForm,
  BasePageQuery,
  BaseQueryDto,
  CityEntity,
  CountryAreaPageVO,
  CouponForm,
  CouponListQuery,
  CourseAvailVO,
  CourseBookingForm,
  CourseDetailVO,
  CourseEvaluationForm,
  CourseForm,
  DataConsumptionRecordsDto,
  DataCouponPageVO,
  DataCourseEvaluationPageVO,
  DataCourseQueryPageVO,
  DataMemberRuleVO,
  DataRichTextSimplePageVO,
  DataSchoolForm,
  DataStudentOrderCoursePageVO,
  DataSysMessage,
  DataTeacherCourseVO,
  DataTeacherInfoVO,
  DataUserPointsDetail,
  DataWechatOrderDto,
  DataWechatUserCouponDTO,
  ExcellentTeacherQuery,
  FeedbackForm,
  IObject,
  IPageCityEntity,
  IPageUserPointsDetail,
  InstitutionPaymentInfoVO,
  InvitationCustVo,
  KsCustForm,
  KsCustQueryDto,
  KsCustVO,
  OpenIdQueryDto,
  OrderCourseBindForm,
  OrderCourseDTO,
  OrderCreateForm,
  OrderForm,
  OrderRefundForm,
  PreCalculatePriceForm,
  RichTextForm,
  SOAPayDto,
  SOAPayReqParam,
  ServedCustomerForm,
  StudentBookingForm,
  StudentCourseDetailVO,
  StudentCourseOperationForm,
  StudentScheduleMouthCountVO,
  SurveyResponseFrom,
  TeacherInfoDto,
  TeacherInfoQuery,
  TreeNodeObject,
  UserPointsDetailQuery,
  WechatSysMessageForm,
  WxPayRefundReqParam,
  WxPayReqParam
} from './types/wxTypes'
import request from '@/utils/request'

type RequestOptions = {
  requestType?: 'GET' | 'POST' | 'PUT' | 'DELETE',
  showLoading?: boolean,
  showError?: boolean
}


/**
 * 更新成已回答过问题
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/updateAnswerQuestion
 *
 * 请求头: post /wechat/customer/cust/updateAnswerQuestion
 */
export function postWechatCustomerCustUpdateanswerquestion(options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/updateAnswerQuestion',
    {},
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 性格测试提交
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/submit
 *
 * 请求头: post /wechat/customer/cust/submit
 */
export function postWechatCustomerCustSubmit(data: SurveyResponseFrom, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/submit',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 修改用户表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/updateKsCust
 *
 * 请求头: post /wechat/customer/cust/edit
 */
export function postWechatCustomerCustEdit(data: KsCustForm, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/edit',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 查询用户子集
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/childList
 *
 * 请求头: post /wechat/customer/cust/child
 */
export function postWechatCustomerCustChild(data: KsCustQueryDto, options?: RequestOptions) {
  return request<any, KsCustVO[]>(
    'wechat/customer/cust/child',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 新增用户表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/saveKsCust
 *
 * 请求头: post /wechat/customer/cust/add
 */
export function postWechatCustomerCustAdd(data: KsCustForm, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/add',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 获取电话号码
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/100.小程序用户登录/getPhoneNumber
 *
 * 请求头: post /wechat/cust/getPhoneNumber
 */
export function postWechatCustGetphonenumber(data: OpenIdQueryDto, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/cust/getPhoneNumber',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 获取openId
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/100.小程序用户登录/getOpenId
 *
 * 请求头: post /wechat/cust/getOpenId
 */
export function postWechatCustGetopenid(data: OpenIdQueryDto, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/cust/getOpenId',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 获取支付订单所需要的优惠券
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/getCouponListByUserId
 *
 * 请求头: post /wechat/coupons/order/list
 */
export function postWechatCouponsOrderList(data: CouponListQuery, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/coupons/order/list',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 微信预支付
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/vx-pay-controller/wxPay
 *
 * 请求头: post /vxPay/vxv3pay
 */
export function postVxpayVxv3pay(data: WxPayReqParam, options?: RequestOptions) {
  return request<any, IObject>(
    'vxPay/vxv3pay',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/vx-pay-controller/payRefund
 *
 * 请求头: post /vxPay/vxPayRefund
 */
export function postVxpayVxpayrefund(data: WxPayRefundReqParam, options?: RequestOptions) {
  return request<any, IObject>(
    'vxPay/vxPayRefund',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/vx-pay-controller/refundWechatCallback
 *
 * 请求头: post /vxPay/refundWechatCallback
 */
export function postVxpayRefundwechatcallback(options?: RequestOptions) {
  return request<any, any>(
    'vxPay/refundWechatCallback',
    {},
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 获取收款码
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/vx-pay-controller/getAccount
 *
 * 请求头: post /vxPay/paymentQrCode
 */
export function postVxpayPaymentqrcode(data: AccountReqParam, options?: RequestOptions) {
  return request<any, InstitutionPaymentInfoVO>(
    'vxPay/paymentQrCode',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 微信下单
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/vx-pay-controller/payNotify
 *
 * 请求头: post /vxPay/payNotify
 */
export function postVxpayPaynotify(options?: RequestOptions) {
  return request<any, any>(
    'vxPay/payNotify',
    {},
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 小程序用户积分明细列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户积分接口/list
 *
 * 请求头: post /user/points/wechat-list
 */
export function postUserPointsWechatList(data: UserPointsDetailQuery, options?: RequestOptions) {
  return request<any, IPageUserPointsDetail>(
    'user/points/wechat-list',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 用户积分明细分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户积分接口/page
 *
 * 请求头: post /user/points/page
 */
export function postUserPointsPage(data: UserPointsDetailQuery, options?: RequestOptions) {
  return request<any, DataUserPointsDetail>(
    'user/points/page',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 新增消息通知
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/消息通知表接口/addMessage
 *
 * 请求头: post /sysMessages/add
 */
export function postSysmessagesAdd(data: WechatSysMessageForm, options?: RequestOptions) {
  return request<any, IObject>(
    'sysMessages/add',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 拉卡拉创建订单
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/createSOAOrder
 *
 * 请求头: post /soaPay/createSOAOrder
 */
export function postSoapayCreatesoaorder(data: SOAPayReqParam, options?: RequestOptions) {
  return request<any, SOAPayDto>(
    'soaPay/createSOAOrder',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 新增意见反馈
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/意见反馈接口/saveFeedback
 *
 * 请求头: post /feedbacks
 */
export function postFeedbacks(data: FeedbackForm, options?: RequestOptions) {
  return request<any, IObject>(
    'feedbacks',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 新增课程评价表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/saveCourseEvaluation
 *
 * 请求头: post /courseEvaluations
 */
export function postCourseevaluations(data: CourseEvaluationForm, options?: RequestOptions) {
  return request<any, IObject>(
    'courseEvaluations',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 学生拒绝讲师取消约课
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/rejectCancel
 *
 * 请求头: post /api/v1/student/courseBooking/rejectCancel
 */
export function postApiV1StudentCoursebookingRejectcancel(data: StudentCourseOperationForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/student/courseBooking/rejectCancel',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 学生约课
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/bookCourse
 *
 * 请求头: post /api/v1/student/courseBooking/book
 */
export function postApiV1StudentCoursebookingBook(data: CourseBookingForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/student/courseBooking/book',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 学生客户端课程绑定学生
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/bindOrderCourse
 *
 * 请求头: post /api/v1/student/courseBooking/bind
 */
export function postApiV1StudentCoursebookingBind(data: OrderCourseBindForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/student/courseBooking/bind',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 学生同意讲师取消约课
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/approvalCancel
 *
 * 请求头: post /api/v1/student/courseBooking/approvalCancel
 */
export function postApiV1StudentCoursebookingApprovalcancel(data: StudentCourseOperationForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/student/courseBooking/approvalCancel',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 申请取消约课（学生约课后，未上课）
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/applyCancellation
 *
 * 请求头: post /api/v1/student/courseBooking/applyCancellation
 */
export function postApiV1StudentCoursebookingApplycancellation(data: StudentCourseOperationForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/student/courseBooking/applyCancellation',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 预先计算价格
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/preCalculatePrice
 *
 * 请求头: post /api/v1/orders/wechat/pre-calculate
 */
export function postApiV1OrdersWechatPreCalculate(data: PreCalculatePriceForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/orders/wechat/pre-calculate',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 微信下单V2
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/createOrder
 *
 * 请求头: post /api/v1/orders/wechat/create
 */
export function postApiV1OrdersWechatCreate(data: OrderCreateForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/orders/wechat/create',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 消费记录
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/consumptionRecords
 *
 * 请求头: post /api/v1/orders/consumption-records
 */
export function postApiV1OrdersConsumptionRecords(data: BasePageQuery, options?: RequestOptions) {
  return request<any, DataConsumptionRecordsDto>(
    'api/v1/orders/consumption-records',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 申请退款
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/applyRefund
 *
 * 请求头: post /api/v1/orders/apply-refund
 */
export function postApiV1OrdersApplyRefund(data: OrderRefundForm, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/orders/apply-refund',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 讲师信息分页搜索接口
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/selectPage
 *
 * 请求头: post /api/v1/ks/teacherInfo/page
 */
export function postApiV1KsTeacherinfoPage(data: TeacherInfoQuery, options?: RequestOptions) {
  return request<any, DataTeacherInfoVO>(
    'api/v1/ks/teacherInfo/page',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 优秀讲师信息分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/selectExcellentPage
 *
 * 请求头: post /api/v1/ks/teacherInfo/excellent-page
 */
export function postApiV1KsTeacherinfoExcellentPage(data: ExcellentTeacherQuery, options?: RequestOptions) {
  return request<any, DataTeacherInfoVO>(
    'api/v1/ks/teacherInfo/excellent-page',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/stop
 *
 * 请求头: post /api/v1/city/stop
 */
export function postApiV1CityStop(data: BaseQueryDto, options?: RequestOptions) {
  return request<any, any>(
    'api/v1/city/stop',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/start
 *
 * 请求头: post /api/v1/city/start
 */
export function postApiV1CityStart(data: BaseQueryDto, options?: RequestOptions) {
  return request<any, any>(
    'api/v1/city/start',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/edit
 *
 * 请求头: post /api/v1/city/edit
 */
export function postApiV1CityEdit(data: CityEntity, options?: RequestOptions) {
  return request<any, any>(
    'api/v1/city/edit',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/delete
 *
 * 请求头: post /api/v1/city/delete
 */
export function postApiV1CityDelete(data: BaseQueryDto, options?: RequestOptions) {
  return request<any, any>(
    'api/v1/city/delete',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/add
 *
 * 请求头: post /api/v1/city/add
 */
export function postApiV1CityAdd(data: CityEntity, options?: RequestOptions) {
  return request<any, any>(
    'api/v1/city/add',
    data,
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * 用户表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/getKsCustForm
 *
 * 请求头: get /wechat/customer/cust/{id}
 */
export function getWechatCustomerCustByid(params: { id: string }, options?: RequestOptions) {
  return request<any, KsCustForm>(
    `wechat/customer/cust/${params.id}`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 校验验证码是否存在
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/validInvitation
 *
 * 请求头: get /wechat/customer/cust/validInvitation
 */
export function getWechatCustomerCustValidinvitation(params: { invitationCode: string }, options?: RequestOptions) {
  return request<any, boolean>(
    'wechat/customer/cust/validInvitation',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 查询邀请用户
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/queryInvitationList
 *
 * 请求头: get /wechat/customer/cust/invitation
 */
export function getWechatCustomerCustInvitation(params: { id: string }, options?: RequestOptions) {
  return request<any, InvitationCustVo[]>(
    'wechat/customer/cust/invitation',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取小程序邀请码
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/getWxaCodeUnLimit
 *
 * 请求头: get /wechat/customer/cust/getWxaCodeUnLimit
 */
export function getWechatCustomerCustGetwxacodeunlimit(params: { page?: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/getWxaCodeUnLimit',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取性格测试信息
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/submit_1
 *
 * 请求头: get /wechat/customer/cust/getTestResult
 */
export function getWechatCustomerCustGettestresult(options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/getTestResult',
    {},
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取积分
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/getPoints
 *
 * 请求头: get /wechat/customer/cust/getPoints
 */
export function getWechatCustomerCustGetpoints(options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/getPoints',
    {},
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 下载性格测试文档
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/用户接口/downloadFile
 *
 * 请求头: get /wechat/customer/cust/downloadFile
 */
export function getWechatCustomerCustDownloadfile(options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/customer/cust/downloadFile',
    {},
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 退出
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/100.小程序用户登录/loginOut
 *
 * 请求头: get /wechat/cust/loginOut
 */
export function getWechatCustLoginout(params: { phone: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/cust/loginOut',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 优惠劵表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/getCouponForm
 *
 * 请求头: get /wechat/coupons/{id}
 */
export function getWechatCouponsByid(params: { id: number }, options?: RequestOptions) {
  return request<any, CouponForm>(
    `wechat/coupons/${params.id}`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 用户优惠劵分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/listPagedCoupons
 *
 * 请求头: get /wechat/coupons/user/page
 */
export function getWechatCouponsUserPage(params: { userId?: string, useStatus?: string, date?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataWechatUserCouponDTO>(
    'wechat/coupons/user/page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 领取优惠券
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/receive
 *
 * 请求头: get /wechat/coupons/receive
 */
export function getWechatCouponsReceive(params: { id: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'wechat/coupons/receive',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 优惠劵表分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/listPagedCoupons_1
 *
 * 请求头: get /wechat/coupons/page
 */
export function getWechatCouponsPage(params: { keywords?: string, status?: number, level?: number, valid?: string, date?: string, receiveType?: number, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataCouponPageVO>(
    'wechat/coupons/page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 阅读消息
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/消息通知表接口/readMessage
 *
 * 请求头: get /sysMessages/read
 */
export function getSysmessagesRead(params: { ids: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'sysMessages/read',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 消息通知表分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/消息通知表接口/listPagedSysMessages
 *
 * 请求头: get /sysMessages/page
 */
export function getSysmessagesPage(params: { userId?: string, createTimeStart?: string, createTimeEnd?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataSysMessage>(
    'sysMessages/page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 会员等级规则分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/会员等级规则接口/list_1
 *
 * 请求头: get /student/level/rule/list
 */
export function getStudentLevelRuleList(params: { delFlag?: number, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataMemberRuleVO>(
    'student/level/rule/list',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 服务过的客户分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/服务过的客户信息接口/list_2
 *
 * 请求头: get /servedCustomer/list
 */
export function getServedcustomerList(options?: RequestOptions) {
  return request<any, ServedCustomerForm[]>(
    'servedCustomer/list',
    {},
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 学校信息分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学校信息接口/list_3
 *
 * 请求头: get /schools/list
 */
export function getSchoolsList(params: { pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataSchoolForm>(
    'schools/list',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 富文本表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/富文本表接口/getRichTextForm
 *
 * 请求头: get /richTexts/{id}/form
 */
export function getRichtextsByidForm(params: { id: number }, options?: RequestOptions) {
  return request<any, RichTextForm>(
    `richTexts/${params.id}/form`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 富文本表分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/富文本表接口/listPagedRichTexts
 *
 * 请求头: get /richTexts/page
 */
export function getRichtextsPage(params: { keywords?: string, isDisplay?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataRichTextSimplePageVO>(
    'richTexts/page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 课程评价表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/getCourseEvaluationForm
 *
 * 请求头: get /courseEvaluations/{id}/form
 */
export function getCourseevaluationsByidForm(params: { id: number }, options?: RequestOptions) {
  return request<any, CourseEvaluationForm>(
    `courseEvaluations/${params.id}/form`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 课程评价表分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/listPagedCourseEvaluations
 *
 * 请求头: get /courseEvaluations/page
 */
export function getCourseevaluationsPage(params: { courseId?: string, teacherId?: string, totalScoreStart?: string, totalScoreEnd?: string, userId?: string, courseHoursId?: string, querySelf?: string, auditStatus?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataCourseEvaluationPageVO>(
    'courseEvaluations/page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 判断用户是否有评价权限
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程评价表接口/judgeAuth
 *
 * 请求头: get /courseEvaluations/judge_auth
 */
export function getCourseevaluationsJudge_auth(params: { courseId: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'courseEvaluations/judge_auth',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 学生客户端查看课程列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生课表接口/getStudentScheduleList
 *
 * 请求头: get /api/v1/student/schedule/list
 */
export function getApiV1StudentScheduleList(params: { startTime?: string, endTime?: string, studentId: string }, options?: RequestOptions) {
  return request<any, StudentBookingForm[]>(
    'api/v1/student/schedule/list',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 小程序端学生课表月度计数查询
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生课表接口/getStudentScheduleMouthCount
 *
 * 请求头: get /api/v1/student/schedule/getStudentScheduleMouthCount
 */
export function getApiV1StudentScheduleGetstudentschedulemouthcount(params: { timezone?: string, startTime?: string, endTime?: string, studentId: string }, options?: RequestOptions) {
  return request<any, StudentScheduleMouthCountVO[]>(
    'api/v1/student/schedule/getStudentScheduleMouthCount',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 学生客户端查看未绑定的课程列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getUnbindOrderCoursesPage
 *
 * 请求头: get /api/v1/student/courseBooking/unbind-list
 */
export function getApiV1StudentCoursebookingUnbindList(params: { pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataStudentOrderCoursePageVO>(
    'api/v1/student/courseBooking/unbind-list',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 学生客户端查看子账号课程列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getSubUserOrderCoursesPage
 *
 * 请求头: get /api/v1/student/courseBooking/sublist
 */
export function getApiV1StudentCoursebookingSublist(params: { studentId?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataStudentOrderCoursePageVO>(
    'api/v1/student/courseBooking/sublist',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 学生客户端查看课程列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getOrderCourseList
 *
 * 请求头: get /api/v1/student/courseBooking/list
 */
export function getApiV1StudentCoursebookingList(params: { pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataStudentOrderCoursePageVO>(
    'api/v1/student/courseBooking/list',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 查看某课程某时间段内可约课时间
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getCourseAvail
 *
 * 请求头: get /api/v1/student/courseBooking/getCourseAvail
 */
export function getApiV1StudentCoursebookingGetcourseavail(params: { courseId: string, startTime?: string, endTime?: string, studentId: string }, options?: RequestOptions) {
  return request<any, CourseAvailVO[]>(
    'api/v1/student/courseBooking/getCourseAvail',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 学生客户端查看上课状态详情
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/学生约课接口/getCourseDetailList
 *
 * 请求头: get /api/v1/student/courseBooking/courseDetail
 */
export function getApiV1StudentCoursebookingCoursedetail(params: { studentId: string, courseId: string, startTime?: string, endTime?: string }, options?: RequestOptions) {
  return request<any, StudentCourseDetailVO[]>(
    'api/v1/student/courseBooking/courseDetail',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 退单
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/refundOrder
 *
 * 请求头: get /api/v1/orders/{id}/refund
 */
export function getApiV1OrdersByidRefund(params: { id: string }, options?: RequestOptions) {
  return request<any, IObject>(
    `api/v1/orders/${params.id}/refund`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 订单表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/getOrderForm
 *
 * 请求头: get /api/v1/orders/{id}/form
 */
export function getApiV1OrdersByidForm(params: { id: string }, options?: RequestOptions) {
  return request<any, OrderForm>(
    `api/v1/orders/${params.id}/form`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 订单表分页列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/wechatPagedOrders
 *
 * 请求头: get /api/v1/orders/wechat-page
 */
export function getApiV1OrdersWechatPage(params: { keywords?: string, courseId?: string, orderTimeStart?: string, orderTimeEnd?: string, ids?: string[], userId?: string, courseClassificationId?: string, status?: string, bookingOrder?: string, institutionId?: string, id?: string, studentKeys?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataWechatOrderDto>(
    'api/v1/orders/wechat-page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取订单可用的优惠券列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/userCoupon
 *
 * 请求头: get /api/v1/orders/user-coupon
 */
export function getApiV1OrdersUserCoupon(params: { id: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/orders/user-coupon',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 退单详情
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/refundList
 *
 * 请求头: get /api/v1/orders/refund/detail
 */
export function getApiV1OrdersRefundDetail(params: { id: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/orders/refund/detail',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取订单课程列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/getCourse
 *
 * 请求头: get /api/v1/orders/course
 */
export function getApiV1OrdersCourse(params: { orderId: string }, options?: RequestOptions) {
  return request<any, OrderCourseDTO[]>(
    'api/v1/orders/course',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 取消订单
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序订单表接口/cancelOrder
 *
 * 请求头: get /api/v1/orders/cancel
 */
export function getApiV1OrdersCancel(params: { id: string }, options?: RequestOptions) {
  return request<any, IObject>(
    'api/v1/orders/cancel',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取讲师详情信息
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/getTeacherForm
 *
 * 请求头: get /api/v1/ks/teacherInfo/{id}
 */
export function getApiV1KsTeacherinfoByid(params: { id: string }, options?: RequestOptions) {
  return request<any, TeacherInfoDto>(
    `api/v1/ks/teacherInfo/${params.id}`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 分页查询相似领域的讲师列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/getSimilarTeachers
 *
 * 请求头: get /api/v1/ks/teacherInfo/similar/{teacherId}
 */
export function getApiV1KsTeacherinfoSimilarByteacherid(params: { teacherId: string, pageNum?: number, pageSize?: number }, options?: RequestOptions) {
  return request<any, DataTeacherInfoVO>(
    `api/v1/ks/teacherInfo/similar/${params.teacherId}`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 首页推荐讲师信息接口
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/recommended
 *
 * 请求头: get /api/v1/ks/teacherInfo/recommended
 */
export function getApiV1KsTeacherinfoRecommended(params: { school?: string, internationalType?: string, type?: string, grade?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataTeacherInfoVO>(
    'api/v1/ks/teacherInfo/recommended',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 根据讲师id分页获取其课程列表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序端讲师信息接口/getCourses
 *
 * 请求头: get /api/v1/ks/teacherInfo/courses
 */
export function getApiV1KsTeacherinfoCourses(params: { teacherId: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataTeacherCourseVO>(
    'api/v1/ks/teacherInfo/courses',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 课程主表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getCourseForm
 *
 * 请求头: get /api/v1/courses/{id}/form
 */
export function getApiV1CoursesByidForm(params: { id: string }, options?: RequestOptions) {
  return request<any, CourseForm>(
    `api/v1/courses/${params.id}/form`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 课程主表表单数据V2
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getCourseDetail
 *
 * 请求头: get /api/v1/courses/{id}/detail
 */
export function getApiV1CoursesByidDetail(params: { id: string }, options?: RequestOptions) {
  return request<any, CourseDetailVO>(
    `api/v1/courses/${params.id}/detail`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 课程列表分页-小程序V2
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/listPagedCourses
 *
 * 请求头: get /api/v1/courses/procedures-page
 */
export function getApiV1CoursesProceduresPage(params: { name?: string, courseClassificationId?: string, countryAreaId?: string, ageRangeCode?: string, suitAgeStart?: number, suitAgeEnd?: number, teachingMethodsCode?: string, teachWayCode?: string, teachLanguageCode?: string, addressLike?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataCourseQueryPageVO>(
    'api/v1/courses/procedures-page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 板块课程列表分页
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getListPagedCoursesBySector
 *
 * 请求头: get /api/v1/courses/pageBySector
 */
export function getApiV1CoursesPagebysector(params: { name?: string, courseClassificationId?: string, countryAreaId?: string, ageRangeCode?: string, suitAgeStart?: number, suitAgeEnd?: number, teachingMethodsCode?: string, teachWayCode?: string, teachLanguageCode?: string, addressLike?: string, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, DataCourseQueryPageVO>(
    'api/v1/courses/pageBySector',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 课程名称关键词联想
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序课程主表接口/getNameSuggestions
 *
 * 请求头: get /api/v1/courses/name-suggestions
 */
export function getApiV1CoursesNameSuggestions(params: { keyword: string }, options?: RequestOptions) {
  return request<any, string[]>(
    'api/v1/courses/name-suggestions',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 获取国家地区表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/国家地区表接口/listCourseClassifications
 *
 * 请求头: get /api/v1/countryArea/list
 */
export function getApiV1CountryareaList(params: { parentId?: string, names?: string, nameList?: string[] }, options?: RequestOptions) {
  return request<any, CountryAreaPageVO[]>(
    'api/v1/countryArea/list',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 地区树
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/tree
 *
 * 请求头: get /api/v1/city/tree
 */
export function getApiV1CityTree(options?: RequestOptions) {
  return request<any, TreeNodeObject[]>(
    'api/v1/city/tree',
    {},
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/treeLazy
 *
 * 请求头: get /api/v1/city/treeLazy
 */
export function getApiV1CityTreelazy(params: { parentId: string }, options?: RequestOptions) {
  return request<any, TreeNodeObject[]>(
    'api/v1/city/treeLazy',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/search
 *
 * 请求头: get /api/v1/city/search
 */
export function getApiV1CitySearch(params: { cityName?: string, cityState?: number, parentId?: string, needRoot?: number, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, any>(
    'api/v1/city/search',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/page_1
 *
 * 请求头: get /api/v1/city/page
 */
export function getApiV1CityPage(params: { cityName?: string, cityState?: number, parentId?: string, needRoot?: number, pageNum?: string, pageSize?: string }, options?: RequestOptions) {
  return request<any, IPageCityEntity>(
    'api/v1/city/page',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/地区管理接口/detail
 *
 * 请求头: get /api/v1/city/detail
 */
export function getApiV1CityDetail(params: { id: string }, options?: RequestOptions) {
  return request<any, CityEntity>(
    'api/v1/city/detail',
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 协议表表单数据
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/协议表接口小程序/getAgreementForm
 *
 * 请求头: get /agreements/{id}/form
 */
export function getAgreementsByidForm(params: { id: string }, options?: RequestOptions) {
  return request<any, AgreementForm>(
    `agreements/${params.id}/form`,
    params,
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * 删除优惠劵表
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/小程序优惠劵接口/deleteCoupons
 *
 * 请求头: delete /wechat/coupons/{ids}
 */
export function deleteWechatCouponsByids(params: { ids: string }, options?: RequestOptions) {
  return request<any, IObject>(
    `wechat/coupons/${params.ids}`,
    params,
    { requestType: 'DELETE', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo
 *
 * 请求头: get /soaPay/backNotice
 */
export function getSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'GET', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo_3
 *
 * 请求头: put /soaPay/backNotice
 */
export function putSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'PUT', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo_2
 *
 * 请求头: post /soaPay/backNotice
 */
export function postSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'POST', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo_5
 *
 * 请求头: delete /soaPay/backNotice
 */
export function deleteSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'DELETE', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo_6
 *
 * 请求头: options /soaPay/backNotice
 */
export function optionsSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'OPTIONS', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo_1
 *
 * 请求头: head /soaPay/backNotice
 */
export function headSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'HEAD', ...options }
  ).then(res => res)
}

/**
 * undefined
 *
 * 接口文档: https://dsjedu.com.cn/prod-api/doc.html#/小程序端/soa-pay-controller/backNoticeDemo_4
 *
 * 请求头: patch /soaPay/backNotice
 */
export function patchSoapayBacknotice(options?: RequestOptions) {
  return request<any, any>(
    'soaPay/backNotice',
    {},
    { requestType: 'PATCH', ...options }
  ).then(res => res)
}

