// Generated by Node.js script
// !!!!! DO NOT EDIT !!!!!

import type {
  DeptForm,
  DictForm,
  DictTypeForm,
  HomeDataDto,
  IPageUserPageVO,
  MenuForm,
  PageDictPageVO,
  PageDictTypePageVO,
  PageRolePageVO,
  RoleForm,
  UserChangePasswordForm,
  UserForm,
  UserInfoVO
} from './types/systemTypes'
import request from '@/utils/request'


/**
 * 修改用户
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/updateUser
 * 
 * 请求头: put /api/v1/users/{userId}
 */
export function putApiV1UsersByuserid(params: { userId: string }, data: UserForm) {
  return request<any, any>({
    url: `/api/v1/users/${params.userId}`,
    method: 'put',
    data,
    params,
  })
}

/**
 * 用户自己修改密码
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/changePassword
 * 
 * 请求头: put /api/v1/users/changePassword
 */
export function putApiV1UsersChangepassword(data: UserChangePasswordForm) {
  return request<any, any>({
    url: '/api/v1/users/changePassword',
    method: 'put',
    data,
  })
}

/**
 * 修改角色状态
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/updateRoleStatus
 * 
 * 请求头: put /api/v1/roles/{roleId}/status
 */
export function putApiV1RolesByroleidStatus(params: { roleId: number, status: number }) {
  return request<any, any>({
    url: `/api/v1/roles/${params.roleId}/status`,
    method: 'put',
    params,
  })
}

/**
 * 分配菜单(包括按钮权限)给角色
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/assignMenusToRole
 * 
 * 请求头: put /api/v1/roles/{roleId}/menus
 */
export function putApiV1RolesByroleidMenus(params: { roleId: number }, data: number[]) {
  return request<any, any>({
    url: `/api/v1/roles/${params.roleId}/menus`,
    method: 'put',
    data,
    params,
  })
}

/**
 * 修改角色
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/updateRole
 * 
 * 请求头: put /api/v1/roles/{id}
 */
export function putApiV1RolesByid(data: RoleForm) {
  return request<any, any>({
    url: `/api/v1/roles/${params.id}`,
    method: 'put',
    data,
  })
}

/**
 * 修改菜单
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/updateMenu
 * 
 * 请求头: put /api/v1/menus/{id}
 */
export function putApiV1MenusByid(data: MenuForm) {
  return request<any, any>({
    url: `/api/v1/menus/${params.id}`,
    method: 'put',
    data,
  })
}

/**
 * 删除菜单
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/deleteMenu
 * 
 * 请求头: delete /api/v1/menus/{id}
 */
export function deleteApiV1MenusByid(params: { id: number }) {
  return request<any, any>({
    url: `/api/v1/menus/${params.id}`,
    method: 'delete',
    params,
  })
}

/**
 * 修改字典
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/updateDict
 * 
 * 请求头: put /api/v1/dict/{id}
 */
export function putApiV1DictByid(params: { id: number }, data: DictForm) {
  return request<any, any>({
    url: `/api/v1/dict/${params.id}`,
    method: 'put',
    data,
    params,
  })
}

/**
 * 修改字典类型
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/updateDictType
 * 
 * 请求头: put /api/v1/dict/types/{id}
 */
export function putApiV1DictTypesByid(params: { id: number }, data: DictTypeForm) {
  return request<any, any>({
    url: `/api/v1/dict/types/${params.id}`,
    method: 'put',
    data,
    params,
  })
}

/**
 * 修改部门
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/updateDept
 * 
 * 请求头: put /api/v1/dept/{deptId}
 */
export function putApiV1DeptBydeptid(params: { deptId: number }, data: DeptForm) {
  return request<any, any>({
    url: `/api/v1/dept/${params.deptId}`,
    method: 'put',
    data,
    params,
  })
}

/**
 * 新增用户
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/saveUser
 * 
 * 请求头: post /api/v1/users
 */
export function postApiV1Users(data: UserForm) {
  return request<any, any>({
    url: '/api/v1/users',
    method: 'post',
    data,
  })
}

/**
 * 导入用户
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/importUsers
 * 
 * 请求头: post /api/v1/users/import
 */
export function postApiV1UsersImport(params: { deptId: number }) {
  return request<any, any>({
    url: '/api/v1/users/import',
    method: 'post',
    params,
  })
}

/**
 * 新增角色
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/addRole
 * 
 * 请求头: post /api/v1/roles
 */
export function postApiV1Roles(data: RoleForm) {
  return request<any, any>({
    url: '/api/v1/roles',
    method: 'post',
    data,
  })
}

/**
 * 菜单列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/listMenus
 * 
 * 请求头: get /api/v1/menus
 */
export function getApiV1Menus(params: { keywords?: string, status?: string }) {
  return request<any, any>({
    url: '/api/v1/menus',
    method: 'get',
    params,
  })
}

/**
 * 新增菜单
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/addMenu
 * 
 * 请求头: post /api/v1/menus
 */
export function postApiV1Menus(data: MenuForm) {
  return request<any, any>({
    url: '/api/v1/menus',
    method: 'post',
    data,
  })
}

/**
 * 新增字典
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/saveDict
 * 
 * 请求头: post /api/v1/dict
 */
export function postApiV1Dict(data: DictForm) {
  return request<any, any>({
    url: '/api/v1/dict',
    method: 'post',
    data,
  })
}

/**
 * 新增字典类型
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/saveDictType
 * 
 * 请求头: post /api/v1/dict/types
 */
export function postApiV1DictTypes(data: DictTypeForm) {
  return request<any, any>({
    url: '/api/v1/dict/types',
    method: 'post',
    data,
  })
}

/**
 * 获取部门列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/listDepartments
 * 
 * 请求头: get /api/v1/dept
 */
export function getApiV1Dept(params: { keywords?: string, status?: string }) {
  return request<any, any>({
    url: '/api/v1/dept',
    method: 'get',
    params,
  })
}

/**
 * 新增部门
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/saveDept
 * 
 * 请求头: post /api/v1/dept
 */
export function postApiV1Dept(data: DeptForm) {
  return request<any, any>({
    url: '/api/v1/dept',
    method: 'post',
    data,
  })
}

/**
 * 修改用户状态
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/updateUserStatus
 * 
 * 请求头: patch /api/v1/users/{userId}/status
 */
export function patchApiV1UsersByuseridStatus(params: { userId: string, status: number }) {
  return request<any, any>({
    url: `/api/v1/users/${params.userId}/status`,
    method: 'patch',
    params,
  })
}

/**
 * 修改用户密码
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/updatePassword
 * 
 * 请求头: patch /api/v1/users/{userId}/password
 */
export function patchApiV1UsersByuseridPassword(params: { userId: string, password: string }) {
  return request<any, any>({
    url: `/api/v1/users/${params.userId}/password`,
    method: 'patch',
    params,
  })
}

/**
 * 修改菜单显示状态
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/updateMenuVisible
 * 
 * 请求头: patch /api/v1/menus/{menuId}
 */
export function patchApiV1MenusBymenuid(params: { menuId: number, visible: number }) {
  return request<any, any>({
    url: `/api/v1/menus/${params.menuId}`,
    method: 'patch',
    params,
  })
}

/**
 * 用户表单数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/getUserForm
 * 
 * 请求头: get /api/v1/users/{userId}/form
 */
export function getApiV1UsersByuseridForm(params: { userId: string }) {
  return request<any, UserForm>({
    url: `/api/v1/users/${params.userId}/form`,
    method: 'get',
    params,
  })
}

/**
 * 用户导入模板下载
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/downloadTemplate
 * 
 * 请求头: get /api/v1/users/template
 */
export function getApiV1UsersTemplate() {
  return request<any, any>({
    url: '/api/v1/users/template',
    method: 'get',
  })
}

/**
 * 用户分页列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/listPagedUsers
 * 
 * 请求头: get /api/v1/users/page
 */
export function getApiV1UsersPage(params: { keywords?: string, status?: string, deptId?: string, startTime?: string, endTime?: string, pageNum?: string, pageSize?: string }) {
  return request<any, IPageUserPageVO>({
    url: '/api/v1/users/page',
    method: 'get',
    params,
  })
}

/**
 * 获取当前登录用户信息
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/getCurrentUserInfo
 * 
 * 请求头: get /api/v1/users/me
 */
export function getApiV1UsersMe() {
  return request<any, UserInfoVO>({
    url: '/api/v1/users/me',
    method: 'get',
  })
}

/**
 * 获取小程序邀请码
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/getWxaCodeUnLimit
 * 
 * 请求头: get /api/v1/users/getWxaCodeUnLimit
 */
export function getApiV1UsersGetwxacodeunlimit(params: { page?: string, qRCodeUseFor: string }) {
  return request<any, any>({
    url: '/api/v1/users/getWxaCodeUnLimit',
    method: 'get',
    params,
  })
}

/**
 * 导出用户
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/exportUsers
 * 
 * 请求头: get /api/v1/users/export
 */
export function getApiV1UsersExport(params: { keywords?: string, status?: string, deptId?: string, startTime?: string, endTime?: string, pageNum?: string, pageSize?: string }) {
  return request<any, any>({
    url: '/api/v1/users/export',
    method: 'get',
    params,
  })
}

/**
 * 获取角色的菜单ID集合
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/getRoleMenuIds
 * 
 * 请求头: get /api/v1/roles/{roleId}/menuIds
 */
export function getApiV1RolesByroleidMenuids(params: { roleId: number }) {
  return request<any, any>({
    url: `/api/v1/roles/${params.roleId}/menuIds`,
    method: 'get',
    params,
  })
}

/**
 * 角色表单数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/getRoleForm
 * 
 * 请求头: get /api/v1/roles/{roleId}/form
 */
export function getApiV1RolesByroleidForm(params: { roleId: number }) {
  return request<any, RoleForm>({
    url: `/api/v1/roles/${params.roleId}/form`,
    method: 'get',
    params,
  })
}

/**
 * 角色分页列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/getRolePage
 * 
 * 请求头: get /api/v1/roles/page
 */
export function getApiV1RolesPage(params: { keywords?: string, pageNum?: string, pageSize?: string }) {
  return request<any, PageRolePageVO>({
    url: '/api/v1/roles/page',
    method: 'get',
    params,
  })
}

/**
 * 角色下拉列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/listRoleOptions
 * 
 * 请求头: get /api/v1/roles/options
 */
export function getApiV1RolesOptions() {
  return request<any, any>({
    url: '/api/v1/roles/options',
    method: 'get',
  })
}

/**
 * 菜单表单数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/getMenuForm
 * 
 * 请求头: get /api/v1/menus/{id}/form
 */
export function getApiV1MenusByidForm(params: { id: number }) {
  return request<any, MenuForm>({
    url: `/api/v1/menus/${params.id}/form`,
    method: 'get',
    params,
  })
}

/**
 * 路由列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/listRoutes
 * 
 * 请求头: get /api/v1/menus/routes
 */
export function getApiV1MenusRoutes() {
  return request<any, any>({
    url: '/api/v1/menus/routes',
    method: 'get',
  })
}

/**
 * 菜单下拉列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/04.菜单接口/listMenuOptions
 * 
 * 请求头: get /api/v1/menus/options
 */
export function getApiV1MenusOptions() {
  return request<any, any>({
    url: '/api/v1/menus/options',
    method: 'get',
  })
}

/**
 * 字典下拉列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/listDictOptions
 * 
 * 请求头: get /api/v1/dict/{typeCode}/options
 */
export function getApiV1DictBytypecodeOptions(params: { typeCode: string }) {
  return request<any, any>({
    url: `/api/v1/dict/${params.typeCode}/options`,
    method: 'get',
    params,
  })
}

/**
 * 字典数据表单数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/getDictForm
 * 
 * 请求头: get /api/v1/dict/{id}/form
 */
export function getApiV1DictByidForm(params: { id: number }) {
  return request<any, DictForm>({
    url: `/api/v1/dict/${params.id}/form`,
    method: 'get',
    params,
  })
}

/**
 * 字典类型表单数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/getDictTypeForm
 * 
 * 请求头: get /api/v1/dict/types/{id}/form
 */
export function getApiV1DictTypesByidForm(params: { id: number }) {
  return request<any, DictTypeForm>({
    url: `/api/v1/dict/types/${params.id}/form`,
    method: 'get',
    params,
  })
}

/**
 * 字典类型分页列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/getDictTypePage
 * 
 * 请求头: get /api/v1/dict/types/page
 */
export function getApiV1DictTypesPage(params: { keywords?: string, pageNum?: string, pageSize?: string }) {
  return request<any, PageDictTypePageVO>({
    url: '/api/v1/dict/types/page',
    method: 'get',
    params,
  })
}

/**
 * 字典分页列表
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/getDictPage
 * 
 * 请求头: get /api/v1/dict/page
 */
export function getApiV1DictPage(params: { keywords?: string, typeCode?: string, pageNum?: string, pageSize?: string }) {
  return request<any, PageDictPageVO>({
    url: '/api/v1/dict/page',
    method: 'get',
    params,
  })
}

/**
 * 获取首页数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/homeData
 * 
 * 请求头: get /api/v1/dict/homeData
 */
export function getApiV1DictHomedata() {
  return request<any, HomeDataDto>({
    url: '/api/v1/dict/homeData',
    method: 'get',
  })
}

/**
 * 获取部门表单数据
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/getDeptForm
 * 
 * 请求头: get /api/v1/dept/{deptId}/form
 */
export function getApiV1DeptBydeptidForm(params: { deptId: number }) {
  return request<any, DeptForm>({
    url: `/api/v1/dept/${params.deptId}/form`,
    method: 'get',
    params,
  })
}

/**
 * 获取部门下拉选项
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/listDeptOptions
 * 
 * 请求头: get /api/v1/dept/options
 */
export function getApiV1DeptOptions() {
  return request<any, any>({
    url: '/api/v1/dept/options',
    method: 'get',
  })
}

/**
 * undefined
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/old
 * 
 * 请求头: get /api/v1/dept/old
 */
export function getApiV1DeptOld() {
  return request<any, any>({
    url: '/api/v1/dept/old',
    method: 'get',
  })
}

/**
 * 删除用户
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/02.用户接口/deleteUsers
 * 
 * 请求头: delete /api/v1/users/{ids}
 */
export function deleteApiV1UsersByids(params: { ids: string }) {
  return request<any, any>({
    url: `/api/v1/users/${params.ids}`,
    method: 'delete',
    params,
  })
}

/**
 * 删除角色
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/03.角色接口/deleteRoles
 * 
 * 请求头: delete /api/v1/roles/{ids}
 */
export function deleteApiV1RolesByids(params: { ids: string }) {
  return request<any, any>({
    url: `/api/v1/roles/${params.ids}`,
    method: 'delete',
    params,
  })
}

/**
 * 删除字典
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/deleteDict
 * 
 * 请求头: delete /api/v1/dict/{ids}
 */
export function deleteApiV1DictByids(params: { ids: string }) {
  return request<any, any>({
    url: `/api/v1/dict/${params.ids}`,
    method: 'delete',
    params,
  })
}

/**
 * 删除字典类型
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/06.字典接口/deleteDictTypes
 * 
 * 请求头: delete /api/v1/dict/types/{ids}
 */
export function deleteApiV1DictTypesByids(params: { ids: string }) {
  return request<any, any>({
    url: `/api/v1/dict/types/${params.ids}`,
    method: 'delete',
    params,
  })
}

/**
 * 删除部门
 *
 * 接口文档: https://tenvia.cn/prod-api/doc.html#/系统端/05.部门接口/deleteDepartments
 * 
 * 请求头: delete /api/v1/dept/{ids}
 */
export function deleteApiV1DeptByids(params: { ids: string }) {
  return request<any, any>({
    url: `/api/v1/dept/${params.ids}`,
    method: 'delete',
    params,
  })
}

