// Generated by Node.js script
// !!!!! DO NOT EDIT !!!!!

import type { IObject } from './commonTypes'

export interface ResultObject {
  code: string
  data: IObject
  msg: string
}

export interface Result {
  code: string
  data: IObject
  msg: string
}

export interface SurveyResponseFrom {
  answer: string
}

export interface CourseVO {
  id: string
  name: string
}

export interface KsCustForm {
  /**
   * 常住地
   */
  addres: string
  addresList: string[]
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 生日
   */
  birthday: string
  /**
   * 渠道，OnLine-线上小程序，OffLine-线下后台
   */
  channel: string
  childNum: number
  courseId: string
  courseList: CourseVO[]
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   * 注册时间
   */
  createTime: string
  custId: string
  deleted: number
  /**
   * 是否展示全部名称 0 脱敏显示   1 显示全称
   */
  displayFullName: number
  /**
   * 分销商
   */
  distributorsId: string
  /**
   * 是否可以下载性格测试文档 0 否  1 是
   */
  downloadFile: number
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 性别
   */
  gender: string
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 用户id
   */
  id: string
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 是否可以获取积分 0 不能获取积分   1 可以获取积分
   */
  integralGain: number
  /**
   * 自身邀请码
   */
  invitationCode: string
  invitationCust: string
  /**
   * 邀请他人的邀请码
   */
  invitationCustCode: string
  /**
   * 邀请时间
   */
  invitationTime: string
  /**
   * 是否白名单(0否 1是)
   */
  isWhitelist: number
  /**
   * 用户等级
   */
  level: number
  /**
   * 用户备注
   */
  mark: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * wechat openID
   */
  openId: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 积分
   */
  points: number
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 真实姓名
   */
  realName: string
  registerFrom: string
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 账号
   */
  username: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
}

export interface KsCustQueryDto {
  parentId: string
}

export interface KsCustVO {
  /**
   * 常住地
   */
  addres: string
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 用户余额
   */
  balance: number
  /**
   * 生日
   */
  birthday: string
  childNum: number
  courseId: string
  /**
   * 希望学习的课程
   */
  courses: string
  /**
   * 注册时间
   */
  createTime: string
  createUser: string
  createUserName: string
  deleted: number
  /**
   * 黑名单  0 否  1  是
   */
  disallowLogin: number
  /**
   * 是否展示全部名称 0 脱敏显示   1 显示全称
   */
  displayFullName: number
  /**
   * 分销商
   */
  distributorsId: string
  /**
   * 亲子账户人数
   */
  familyMemberCount: number
  /**
   * 性别
   */
  gender: string
  /**
   * 用户剩余金币
   */
  goldBalance: number
  /**
   * 爱好
   */
  hobbies: string
  /**
   * 用户id
   */
  id: string
  /**
   * 用户剩余积分
   */
  integralBalance: number
  /**
   * 是否可以获取积分 0 不能获取积分   1 可以获取积分
   */
  integralGain: number
  /**
   * 用户等级
   */
  level: number
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 用户备注
   */
  mark: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * wechat openID
   */
  openId: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 手机号码
   */
  phone: string
  /**
   * 颜色
   */
  preferenceColor: string
  /**
   * 真实姓名
   */
  realName: string
  registerFrom: string
  /**
   * 1为正常，0为禁止
   */
  status: boolean
  /**
   * 最后一次登录时间
   */
  updateTime: string
  /**
   * 账号
   */
  username: string
  /**
   * 微信用户json信息
   */
  wxProfile: string
}

export interface ResultListKsCustVO {
  code: string
  data: KsCustVO[]
  msg: string
}

export interface OpenIdQueryDto {
  code: string
  /**
   * 邀请码
   */
  invitationCode: string
  openId: string
  /**
   * 用户来源取自字典小程序码用途
   */
  type: string
}

export interface CouponListQuery {
  courseClassId: string
  courseId: string
  date: string
  orderAmount: number
  userId: string
}

export interface WxPayReqParam {
  goodsName: string
  orderId: string
  orderNumber: string
  totalPrice: string
}

export interface WxPayRefundReqParam {
  refundMoney: string
  totalMoney: string
  transactionId: string
}

export interface AccountReqParam {
  /**
   * 订单ID
   */
  orderId: string
}

export interface InstitutionPaymentInfoVO {
  /**
   * 收款账号
   */
  accountNumber: string
  /**
   * 支付宝收款二维码base64
   */
  aliPaymentQrCode: string
  /**
   * 收款银行
   */
  bankName: string
  /**
   * 收款账户名
   */
  beneficiaryName: string
  /**
   * 收款二维码base64
   */
  paymentQrCode: string
  /**
   * 收款方式，具体枚举查看字典paymentType，wechat-微信收款码，alipay-支付宝收款码，bank-银行转账
   */
  paymentType: string
}

export interface ResultInstitutionPaymentInfoVO {
  code: string
  data: InstitutionPaymentInfoVO
  msg: string
}

export interface UserPointsDetailQuery {
  /**
   * 结束时间
   */
  createTimeEnd: string
  /**
   * 开始时间
   */
  createTimeStart: string
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 积分类型
   */
  type: number
  /**
   * 会员id
   */
  userId: string
  year: string
}

export interface IPageUserPointsDetail {
  current: number
  pages: number
  records: UserPointsDetail[]
  size: number
  total: number
}

export interface ResultIPageUserPointsDetail {
  code: string
  data: IPageUserPointsDetail
  msg: string
}

export interface UserPointsDetail {
  /**
   * 消费金额
   */
  amount: number
  availablePoints: number
  consumeRatio: number
  courseName: string
  /**
   * 创建时间
   */
  createTime: string
  createUser: string
  delFlag: number
  expiresFlag: number
  expiresTime: string
  id: number
  invitationCustId: string
  orderId: string
  /**
   * 描述信息
   */
  pointDesc: string
  /**
   * 积分数量
   */
  points: number
  /**
   * 1, 注册获取积分 2, 消费获取积分 3, 积分兑换  4, 首次评价获取积分 5, 首次消费邀请人获取积分 6, 退款扣除积分
   */
  type: number
  updateTime: string
  updateUser: string
  /**
   * 用户id
   */
  userId: string
  /**
   * 用户名称
   */
  userName: string
}

export interface DataUserPointsDetail {
  list: UserPointsDetail[]
  total: number
}

export interface PageResultUserPointsDetail {
  code: string
  data: DataUserPointsDetail
  msg: string
}

export interface WechatSysMessageForm {
  /**
   * 消息类型 取自字典表messageTemplate
   */
  msgType: string
}

export interface SOAPayReqParam {
  orderId: string
  payMode: string
}

export interface ResultSOAPayDto {
  code: string
  data: SOAPayDto
  msg: string
}

export interface SOAPayDto {
  /**
   * 拉起地址
   */
  counterUrl: string
  /**
   * 支付金额，单位分
   */
  fee: number
  /**
   * 是否支付完成
   */
  payment: boolean
}

export interface FeedbackForm {
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人ID
   */
  createUserName: string
  /**
   * 意见反馈
   */
  feedbackContent: string
  /**
   * 主键
   */
  id: number
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeCode: string
  /**
   * 类型(course:课程;teacher:教师)
   */
  typeName: string
  /**
   * 更新时间
   */
  updateTime: string
}

export interface CourseEvaluationForm {
  /**
   * 审核状态  0  未审核  1 已审核
   */
  auditStatus: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 课时id/订单id
   */
  courseHoursId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 主键
   */
  id: number
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 总评分
   */
  totalScore: number
  /**
   * 更新时间
   */
  updateTime: string
}

export interface StudentCourseOperationForm {
  /**
   * 约课明细ID
   */
  detailId: string
  /**
   * 学生id
   */
  studentId: string
}

export interface CourseBookingForm {
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课时id列表
   */
  scheduleId: number
  /**
   * 学生id
   */
  studentId: string
}

export interface OrderCourseBindForm {
  /**
   * 主键
   */
  id: string
  /**
   * 学生id
   */
  studentId: string
}

export interface CourseItem {
  /**
   * 购买数量
   */
  count: number
  /**
   * 课程ID
   */
  courseId: string
  /**
   * 机构ID
   */
  institutionId: string
  /**
   * 讲师ID
   */
  teacherId: string
}

export interface PreCalculatePriceForm {
  /**
   * 优惠券ID列表
   */
  couponIds: string[]
  /**
   * 课程列表
   */
  courseList: CourseItem[]
}

export interface OrderCreateForm {
  /**
   * 优惠券ID列表
   */
  couponIds: string[]
  /**
   * 课程列表
   */
  courseList: CourseItem[]
  /**
   * 是否试听订单，0-否，1-是
   */
  isTrial: number
  /**
   * 价格id，创建订单时提交
   */
  priceId: string
}

export interface BasePageQuery {
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
}

export interface ConsumptionRecordsDetailDto {
  courseCount: number
  courseName: string
}

export interface ConsumptionRecordsDto {
  id: string
  list: ConsumptionRecordsDetailDto[]
  orderTime: string
  payAmount: number
}

export interface DataConsumptionRecordsDto {
  list: ConsumptionRecordsDto[]
  total: number
}

export interface PageResultConsumptionRecordsDto {
  code: string
  data: DataConsumptionRecordsDto
  msg: string
}

export interface OrderRefundForm {
  /**
   * 订单详情ID
   */
  detailId: string
  /**
   * 订单ID
   */
  orderId: string
  /**
   * 退款原因
   */
  reason: string
  /**
   * 退款金额
   */
  refundAmount: number
}

export interface TeacherInfoQuery {
  /**
   * 国家地区ID，上传最小一级的id
   */
  countryAreaId: string
  /**
   * 关键词，支持姓名和简介
   */
  keys: string
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
  /**
   * 讲师标签
   */
  tags: string[]
}

export interface DataTeacherInfoVO {
  list: TeacherInfoVO[]
  total: number
}

export interface PageResultTeacherInfoVO {
  code: string
  data: DataTeacherInfoVO
  msg: string
}

export interface TeacherInfoVO {
  /**
   * 年龄
   */
  age: number
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人
   */
  createUserName: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 英文名
   */
  englishName: string
  /**
   * 讲师评分
   */
  evaluation: number
  /**
   * 性别
   */
  gender: string
  goodFields: string[]
  /**
   * 擅长学科
   */
  goodSubject: string
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 首页标语
   */
  homeSlogan: string
  /**
   * 讲师id
   */
  id: string
  /**
   * 所属机构id
   */
  institutionId: number
  /**
   * 机构级别
   */
  institutionLevel: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 列表标语
   */
  listSlogan: string
  /**
   * 所在地
   */
  location: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 国籍
   */
  nationality: string
  /**
   * 首页推荐所用的关键词
   */
  recommendation: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 讲师标签
   */
  tag: string
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 所授专业
   */
  teachingMajor: string
  /**
   * 讲师titleCode
   */
  titleCode: string
  /**
   * 讲师titleName
   */
  titleName: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 更新人
   */
  updateUser: string
  /**
   * 更新人
   */
  updateUserName: string
  /**
   * 讲师的用户id，可用于登陆后台系统
   */
  userId: string
}

export interface ExcellentTeacherQuery {
  /**
   * 备注信息
   */
  addressLike: string
  /**
   * 国家地区ID，上传最小一级的id
   */
  countryAreaId: string
  /**
   * 页码
   */
  pageNum: number
  /**
   * 每页记录数
   */
  pageSize: number
}

export interface BaseQueryDto {
  ids: string[]
}

export interface CityEntity {
  cityCode: string
  cityLat: number
  cityLevel: number
  cityLng: number
  cityMergeName: string
  cityName: string
  cityPinyin: string
  cityShortName: string
  cityState: number
  id: string
  parentId: string
  treePath: string
}

export interface ResultKsCustForm {
  code: string
  data: KsCustForm
  msg: string
}

export interface ResultBoolean {
  code: string
  data: boolean
  msg: string
}

export interface InvitationCustVo {
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 是否消费  true 消费  false 没有消费
   */
  consumption: boolean
  /**
   * 注册时间
   */
  createTime: string
  /**
   * 用户id
   */
  id: string
  /**
   * 用户昵称
   */
  nickname: string
  /**
   * 积分
   */
  point: number
  /**
   * 真实姓名
   */
  realName: string
  /**
   * 用户昵称
   */
  username: string
}

export interface ResultListInvitationCustVo {
  code: string
  data: InvitationCustVo[]
  msg: string
}

export interface CouponForm {
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  deptId: number
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 主键
   */
  id: number
  idPathList: string[]
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 发放数量
   */
  number: number
  /**
   * 领取方式(1人工发放 2系统赠送)
   */
  receiveType: number
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 修改人ID
   */
  updateBy: number
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 使用时间天数
   */
  useRestrictedNum: number
  /**
   * 使用时间(1固定时间 2当日起几天 3次日起几天)
   */
  useRestrictedType: number
  /**
   * 使用范围(1通用 2指定课程可用 3指定课程不可用)
   */
  useScope: number
  /**
   * 使用门槛(0无 其他数值为门槛金额)
   */
  useThreshold: number
  /**
   * 使用范围不为通用详情
   */
  userScopeDetail: string
}

export interface ResultCouponForm {
  code: string
  data: CouponForm
  msg: string
}

export interface DataWechatUserCouponDTO {
  list: WechatUserCouponDTO[]
  total: number
}

export interface PageResultWechatUserCouponDTO {
  code: string
  data: DataWechatUserCouponDTO
  msg: string
}

export interface WechatUserCouponDTO {
  businessNames: string
  couponId: number
  couponName: string
  couponPic: string
  couponThumbnail: string
  createTime: string
  createUser: string
  deductionAmount: number
  delFlag: number
  id: number
  limitUsageEndTime: string
  limitUsageStartTime: string
  /**
   * 订单id
   */
  orderId: string
  receiveType: number
  remark: string
  status: number
  type: number
  updateTime: string
  updateUser: string
  useScope: number
  useStatus: number
  userId: string
  userName: string
}

export interface CouponPageVO {
  /**
   * 满足优惠金额
   */
  amountMet: number
  /**
   * 选中课程、课程分类id
   */
  businessIds: string
  /**
   * 选中课程、课程分类名称
   */
  businessNames: string
  /**
   * 优惠券图片
   */
  couponPic: string
  /**
   * 优惠券缩略图
   */
  couponThumbnail: string
  /**
   * 可用课程
   */
  courseId: string
  /**
   * 创建人ID
   */
  createBy: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 抵扣金额/折扣/补偿劵额
   */
  deductionAmount: number
  deptId: number
  /**
   * 可用用户级别
   */
  embershipLevelId: string
  /**
   * 主键
   */
  id: number
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  isDeleted: number
  /**
   * 系统发放时间
   */
  issueStartTime: string
  /**
   * 限制使用结束时间
   */
  limitUsageEndTime: string
  /**
   * 限制使用开始时间
   */
  limitUsageStartTime: string
  /**
   * 优惠劵名称
   */
  name: string
  /**
   * 使用规则
   */
  remark: string
  /**
   * 奖励方式(1邀请奖励 2新人福利 3生日 4考试奖励)
   */
  rewardType: string
  /**
   * 状态(1:正常;0:禁用)
   */
  status: number
  /**
   * 优惠劵类型(1满减 2折扣 3体验)
   */
  type: number
  /**
   * 修改人ID
   */
  updateBy: number
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 使用限制类型(1:限制使用时间;0:限制使用天数)
   */
  useRestrictedType: number
}

export interface DataCouponPageVO {
  list: CouponPageVO[]
  total: number
}

export interface PageResultCouponPageVO {
  code: string
  data: DataCouponPageVO
  msg: string
}

export interface DataSysMessage {
  list: SysMessage[]
  total: number
}

export interface PageResultSysMessage {
  code: string
  data: DataSysMessage
  msg: string
}

export interface SysMessage {
  /**
   * 业务数据主键
   */
  businessId: number
  createTime: string
  /**
   * 发送人ID
   */
  createUser: string
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  id: number
  /**
   * 消息内容
   */
  msgContent: string
  /**
   * 消息标题
   */
  msgTitle: string
  /**
   * 消息类型 取自字典表messageTemplate
   */
  msgType: string
  /**
   * 阅读状态  0 未读  1 已读
   */
  readStatus: number
  /**
   * 消息接收人ID
   */
  receivePerson: string
}

export interface DataMemberRuleVO {
  list: MemberRuleVO[]
  total: number
}

export interface MemberRuleVO {
  /**
   * 消费加分比例
   */
  consumeRatio: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 是否删除(0否 1是)
   */
  delFlag: number
  /**
   * 会员折扣
   */
  discount: number
  /**
   * 积分有效时长(天)
   */
  duration: number
  /**
   * 权益规则
   */
  equityRules: string
  /**
   * 积分兑换比例
   */
  exchangeRatio: number
  /**
   * 会员等级规则ID
   */
  id: number
  /**
   * 积分获取
   */
  integralGain: string
  /**
   * 权益说明
   */
  interestsStatement: string
  /**
   * 邀请加分比例
   */
  invitedRatio: number
  /**
   * 能否查看课程价格，0不可以，1可以
   */
  isShowCoursePrice: number
  /**
   * 能否查看讲师详情，0不可以，1可以
   */
  isShowTeacherDetail: number
  /**
   * 会员等级规则ID
   */
  level: number
  /**
   * 会员等级名称
   */
  levelName: string
  /**
   * 会员等级规则ID
   */
  levelRule: number
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 可查看的课程数量，-1表示不限制
   */
  viewableCourseCount: number
  /**
   * 可查看的讲师列表数量，-1表示不限制
   */
  viewableTeacherCount: number
  /**
   * 可查看的讲师详情的数量，-1表示不限制
   */
  viewableTeacherDetailCount: number
}

export interface PageResultMemberRuleVO {
  code: string
  data: DataMemberRuleVO
  msg: string
}

export interface ResultListServedCustomerForm {
  code: string
  data: ServedCustomerForm[]
  msg: string
}

export interface ServedCustomerForm {
  /**
   * 服务过的客户中文名
   */
  chineseName: string
  /**
   * 服务过的客户英文名
   */
  englishName: string
  /**
   * id
   */
  id: number
  /**
   * logo地址
   */
  logoUrl: string
}

export interface DataSchoolForm {
  list: SchoolForm[]
  total: number
}

export interface PageResultSchoolForm {
  code: string
  data: DataSchoolForm
  msg: string
}

export interface SchoolForm {
  /**
   * 学校中文名
   */
  chineseName: string
  /**
   * 学校英文名
   */
  englishName: string
  /**
   * id
   */
  id: number
  /**
   * logo地址
   */
  logoUrl: string
}

export interface ResultRichTextForm {
  code: string
  data: RichTextForm
  msg: string
}

export interface RichTextForm {
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 主键
   */
  id: number
  /**
   * 是否展示
   */
  isDisplay: number
  /**
   * 图片url
   */
  mainPicture: string
  /**
   * 标题
   */
  title: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 修改人ID
   */
  updateUser: string
}

export interface DataRichTextSimplePageVO {
  list: RichTextSimplePageVO[]
  total: number
}

export interface PageResultRichTextSimplePageVO {
  code: string
  data: DataRichTextSimplePageVO
  msg: string
}

export interface RichTextSimplePageVO {
  /**
   * 主键
   */
  id: number
  /**
   * 图片url
   */
  mainPicture: string
}

export interface ResultCourseEvaluationForm {
  code: string
  data: CourseEvaluationForm
  msg: string
}

export interface CourseEvaluationPageVO {
  /**
   * 审核状态  0  未审核  1 审核通过  2 审核拒绝
   */
  auditStatus: number
  /**
   * 用户头像
   */
  avatar: string
  /**
   * 课程含金量
   */
  courseContent: number
  /**
   * 评价描述
   */
  courseDescription: string
  /**
   * 课时id
   */
  courseHoursId: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程id
   */
  courseName: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 创建人名称
   */
  createUserName: string
  /**
   * 难易程度
   */
  difficultyDegree: number
  /**
   * 主键
   */
  id: number
  /**
   * 互动情况
   */
  interaction: number
  /**
   * 专业程度
   */
  professionalLevel: number
  /**
   * 评价回复
   */
  replies: EvaluationReply[]
  /**
   * 需求匹配度
   */
  requirementMatching: number
  /**
   * 评分
   */
  score: number
  /**
   * 显示顺序
   */
  sort: number
  /**
   * 教师id
   */
  teacherId: string
  /**
   * 教师名称
   */
  teacherName: string
  /**
   * 教学效果
   */
  teachingEffect: number
  /**
   * 教学水平
   */
  teachingLevel: number
  /**
   * 教学方法
   */
  teachingMethods: number
  /**
   * 总评分
   */
  totalScore: number
  /**
   * 更新时间
   */
  updateTime: string
}

export interface DataCourseEvaluationPageVO {
  list: CourseEvaluationPageVO[]
  total: number
}

export interface EvaluationReply {
  createTime: string
  createUser: string
  createUserName: string
  evaluationId: number
  id: number
  replyMsg: string
  updateTime: string
}

export interface PageResultCourseEvaluationPageVO {
  code: string
  data: DataCourseEvaluationPageVO
  msg: string
}

export interface ResultListStudentBookingForm {
  code: string
  data: StudentBookingForm[]
  msg: string
}

export interface StudentBookingForm {
  /**
   * 背景颜色
   */
  background: string
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 录入方式 manual 手动录入 select 选择已有课程 selectorder 选择订单课程
   */
  editType: string
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 主键
   */
  id: number
  /**
   * 机构id
   */
  institutionId: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 上课地点
   */
  location: string
  /**
   * 备注
   */
  remark: string
  /**
   * 选择课程id
   */
  selectOrderCourseID: string
  /**
   * 课程id对应的课程名称
   */
  selectedCourseName: string
  /**
   * 机构id对应的机构名称
   */
  selectedInstitutionName: string
  /**
   * 讲师id对应的姓名
   */
  selectedTeacherName: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 学生id
   */
  studentId: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师姓名
   */
  teacherName: string
}

export interface ResultListStudentScheduleMouthCountVO {
  code: string
  data: StudentScheduleMouthCountVO[]
  msg: string
}

export interface StudentScheduleMouthCountVO {
  /**
   * 对应日期的次数
   */
  count: number
  /**
   * 日期（格式：YYYY-MM-DD）
   */
  date: string
}

export interface DataStudentOrderCoursePageVO {
  list: StudentOrderCoursePageVO[]
  total: number
}

export interface PageResultStudentOrderCoursePageVO {
  code: string
  data: DataStudentOrderCoursePageVO
  msg: string
}

export interface StudentCourseDetailSlotVO {
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 开始时间
   */
  startTime: number
}

export interface StudentOrderCoursePageVO {
  /**
   * 已预约数量
   */
  appointmentCount: number
  /**
   * 已上数量
   */
  attendedCount: number
  /**
   * 课时数量
   */
  courseCount: number
  /**
   * 课程id
   */
  courseId: string
  /**
   * 课程名称
   */
  courseName: string
  /**
   * 课程封面
   */
  coursePicture: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 主键
   */
  id: string
  lastCourse: StudentCourseDetailSlotVO
  /**
   * 学习状态
   */
  learnStatus: string
  /**
   * 订单表id
   */
  orderId: string
  /**
   * 下单时间
   */
  orderTime: string
  /**
   * 课程数量
   */
  productCount: number
  /**
   * 产品id
   */
  productId: number
  /**
   * 讲师id
   */
  studentId: string
  /**
   * 讲师姓名
   */
  studentName: string
  /**
   * 适合年龄结束值
   */
  suitAgeEnd: number
  /**
   * 适合年龄起始值
   */
  suitAgeStart: number
  /**
   * 授课方式编码
   */
  teachWayCode: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师姓名
   */
  teacherName: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 用户id
   */
  userId: string
  /**
   * 是否评价  1 是  0 否
   */
  whetherEvaluate: number
}

export interface CourseAvailVO {
  /**
   * 预约状态，INIT-未预约，BOOKED-已预约
   */
  bookingStatus: string
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 结束时间
   */
  endTime: number
  /**
   * 约课明细编号
   */
  scheduleId: number
  /**
   * 开始时间
   */
  startTime: number
}

export interface ResultListCourseAvailVO {
  code: string
  data: CourseAvailVO[]
  msg: string
}

export interface ResultListStudentCourseDetailVO {
  code: string
  data: StudentCourseDetailVO[]
  msg: string
}

export interface StudentCourseDetailVO {
  /**
   * 约课状态，参考字典courseBookingStatus
   */
  bookingStatus: string
  /**
   * 约课明细id
   */
  detailId: string
  /**
   * 结束时间
   */
  endTime: number
  evaluationId: string
  /**
   * 课时id
   */
  scheduleId: string
  /**
   * 开始时间
   */
  startTime: number
  /**
   * 教师授课状态，参考字典teachingStatus
   */
  teachingStatus: string
}

export interface OrderDetail {
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  courseHoursCount: number
  courseId: string
  courseName: string
  createTime: string
  id: string
  /**
   * 课程分类全路径
   */
  idPath: string
  /**
   * 主图
   */
  mainPicture: string
  orderId: string
  productAmount: number
  productCount: number
  productId: number
  productName: string
  productPrice: number
  teacherId: string
  updateTime: string
  /**
   * 是否评价  1 是  0 否
   */
  whetherEvaluate: number
}

export interface OrderForm {
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  coupons: UserCoupon[]
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人ID
   */
  createUser: string
  createUserName: string
  /**
   * 逻辑删除标识(1:已删除;0:未删除)
   */
  deleted: number
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 首次支付时间
   */
  firstPayTime: string
  /**
   * 主键
   */
  id: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 备注
   */
  mark: string
  /**
   * 订单金额
   */
  orderAmount: number
  orderDetails: OrderDetail[]
  orderNumber: string
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 支付金额
   */
  payAmount: number
  /**
   * 支付方式(1:微信支付;2:已支付；已完成)
   */
  payWay: number
  refundAmount: number
  /**
   * 状态(1:待支付;2:已支付；已完成)
   */
  status: number
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 修改人ID
   */
  updateUser: string
  /**
   * 订单表id
   */
  userId: string
  /**
   * 用户父级id，没有为父级自身id
   */
  userParentId: string
}

export interface ResultOrderForm {
  code: string
  data: OrderForm
  msg: string
}

export interface UserCoupon {
  couponId: number
  couponName: string
  couponPic: string
  couponThumbnail: string
  createTime: string
  createUser: string
  delFlag: number
  id: number
  limitUsageEndTime: string
  limitUsageStartTime: string
  /**
   * 订单id
   */
  orderId: string
  status: number
  updateTime: string
  updateUser: string
  useStatus: number
  userId: string
  userName: string
}

export interface DataWechatOrderDto {
  list: WechatOrderDto[]
  total: number
}

export interface PageResultWechatOrderDto {
  code: string
  data: DataWechatOrderDto
  msg: string
}

export interface WechatOrderDto {
  /**
   * 1 预订单  2 订单
   */
  bookingOrder: number
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 组织id显示培训机构，或者总公司id
   */
  deptId: string
  /**
   * 优惠金额
   */
  discountAmount: number
  /**
   * 主键
   */
  id: string
  /**
   * 是否试听订单，0-否，1-是
   */
  isTrial: number
  /**
   * 订单金额
   */
  orderAmount: number
  orderDetails: OrderDetail[]
  orderNumber: string
  /**
   * 支付时间
   */
  orderTime: string
  /**
   * 支付金额
   */
  payAmount: number
  refundAmount: number
  /**
   * 状态(1:待支付;2:已完成；3.待退款 4已取消)
   */
  status: number
  /**
   * 订单表id
   */
  userId: string
  /**
   * 是否评价完  1 是  0 否
   */
  whetherEvaluate: number
}

export interface OrderCourseDTO {
  id: string
  /**
   * 主图
   */
  mainPicture: string
  /**
   * 课程名称
   */
  name: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 是否评价  1 是  0 否
   */
  whetherEvaluate: number
}

export interface ResultListOrderCourseDTO {
  code: string
  data: OrderCourseDTO[]
  msg: string
}

export interface ProofMaterialsForm {
  /**
   * 学历证明列表
   */
  degreeCertificates: string[]
  /**
   * 身份证正反面列表
   */
  idCards: string[]
  /**
   * 社会保障卡，驾照或护照列表
   */
  socialProofMaterials: string[]
}

export interface ResultTeacherInfoDto {
  code: string
  data: TeacherInfoDto
  msg: string
}

export interface TeacherEducationBackgroundForm {
  /**
   * 所在国家
   */
  country: string
  /**
   * 学历
   */
  degree: string
  /**
   * 专业名称
   */
  major: string
  /**
   * 学校名称
   */
  schoolName: string
  /**
   * 学习结束时间
   */
  studyEndDate: string
  /**
   * 学习开始时间
   */
  studyStartDate: string
}

export interface TeacherExperienceForm {
  /**
   * 获得成就奖项
   */
  achievements: string
  /**
   * 在职结束日期
   */
  endDay: string
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 职务名称
   */
  jobTitle: string
  /**
   * 在职开始日期
   */
  startDay: string
  /**
   * 教学内容
   */
  teachingContent: string
}

export interface TeacherInfoDto {
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 生日，格式为yyyy-MM-dd
   */
  birthday: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 展示名称
   */
  displayName: string
  /**
   * 教育背景列表
   */
  educationBackgroundList: TeacherEducationBackgroundForm[]
  /**
   * 英文名
   */
  englishName: string
  evaluation: number
  /**
   * 教育履历
   */
  experience: string
  /**
   * 教育履历
   */
  experienceList: TeacherExperienceForm[]
  /**
   * 性别
   */
  gender: string
  /**
   * 擅长领域
   */
  goodFields: string[]
  /**
   * 擅长科目
   */
  goodSubject: string
  /**
   * 毕业院校
   */
  graduationSchool: string
  /**
   * 最高学历
   */
  highestDegree: string
  /**
   * 首页标语
   */
  homeSlogan: string
  id: string
  /**
   * 所属机构id
   */
  institutionId: number
  introduction: TeacherIntroductionForm
  /**
   * 是否展示对应手机端优秀讲师板块，0否，1是
   */
  isShowExcellent: number
  isShowTeacherDetail: number
  /**
   * 列表标语
   */
  listSlogan: string
  /**
   * 所在地
   */
  location: string
  /**
   * 所学专业
   */
  major: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 讲师姓名
   */
  name: string
  /**
   * 国籍
   */
  nationality: string
  proofMaterials: ProofMaterialsForm
  /**
   * 宣传语
   */
  slogan: string
  /**
   * 排序号，数字小的级别高
   */
  sortNumber: number
  /**
   * 讲师标签
   */
  tag: string
  /**
   * 教学年限，教龄
   */
  teachingExperience: number
  /**
   * 所授专业
   */
  teachingMajor: string
  titleCode: string
  /**
   * 讲师试听id
   */
  trialLessonId: string
}

export interface TeacherIntroductionForm {
  /**
   * 详细介绍
   */
  detailedIntroduction: string
  /**
   * 视频介绍地址
   */
  videoIntroductionUrl: string
}

export interface DataTeacherCourseVO {
  list: TeacherCourseVO[]
  total: number
}

export interface PageResultTeacherCourseVO {
  code: string
  data: DataTeacherCourseVO
  msg: string
}

export interface TeacherCourseVO {
  /**
   * 主键id
   */
  id: string
  /**
   * 课程图片url
   */
  mainPicture: string
  /**
   * 课程名称
   */
  name: string
}

export interface CourseForm {
  /**
   * 在学术能力板块的排序号
   */
  academicAbilitySort: number
  /**
   * 详细地址
   */
  address: string
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 审核原因
   */
  auditReason: string
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 开课人数
   */
  classCount: number
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  commissionRate: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 在综合素质板块的排序号
   */
  comprehensiveQualitySort: number
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 创建时间
   */
  createTime: string
  createUser: string
  createUserName: string
  /**
   * 逻辑删除标识(0:未删除;1:已删除)
   */
  deleted: number
  /**
   * 部门ID
   */
  deptId: number
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 含金量值
   */
  goldContent: number
  id: string
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 机构id
   */
  institutionId: number
  /**
   * 机构名称
   */
  institutionName: string
  /**
   * 在国际课程板块的排序号
   */
  internationalCourseSort: number
  /**
   * 是否属于学术能力(0:否,1:是)
   */
  isAcademicAbility: number
  /**
   * 是否属于综合素质(0:否,1:是)
   */
  isComprehensiveQuality: number
  /**
   * 是否属于国际课程(0:否,1:是)
   */
  isInternationalCourse: number
  /**
   * 是否在学术能力板块展示(0:否,1:是)
   */
  isShowAcademicAbility: number
  /**
   * 是否在综合素质板块展示(0:否,1:是)
   */
  isShowComprehensiveQuality: number
  /**
   * 是否在国际课程板块展示(0:否,1:是)
   */
  isShowInternationalCourse: number
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  /**
   * 是否在世界名校板块展示(0:否,1:是)
   */
  isShowWorldFamousSchool: number
  /**
   * 是否属于世界名校(0:否,1:是)
   */
  isWorldFamousSchool: number
  /**
   * 纬度
   */
  latitude: string
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 经度
   */
  longitude: string
  mainPicture: string
  /**
   * 管理人员，多个用，隔开
   */
  managerPerson: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 课班数量
   */
  minClassCount: number
  /**
   * 课程名称
   */
  name: string
  /**
   * 新单佣金比例，具体的小数，非%，前端展示需要自行转换
   */
  newCommissionRate: number
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 课程售价
   */
  price: number
  publicityPictureUrls: string[]
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 上架状态((1:已上架;0:待上架))
   */
  shelvesStatus: number
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 单节课时长
   */
  singleClassDuration: number
  sortNumber: number
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 审核状态((1:已审核;0:待审核))
   */
  status: number
  /**
   * 学习人数
   */
  studentsNumber: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 时区编码
   */
  timeZoneCode: string
  /**
   * 时区编码名称
   */
  timeZoneName: string
  /**
   * 部门Fullid
   */
  treePath: string
  trialLessonId: string
  /**
   * 更新时间
   */
  updateTime: string
  updateUser: string
  updateUserName: string
  /**
   * 在世界名校板块的排序号
   */
  worldFamousSchoolSort: number
}

export interface ResultCourseForm {
  code: string
  data: CourseForm
  msg: string
}

export interface CourseDetailVO {
  /**
   * 详细地址
   */
  address: string
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 年龄范围编码
   */
  ageRangeCode: string
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 截止购买时间
   */
  buyTime: string
  /**
   * 最大人数
   */
  classCount: number
  /**
   * 课时数量
   */
  classHourseNumber: number
  /**
   * 综合评价
   */
  comprehensiveEvaluation: number
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 课程分类id
   */
  courseClassificationId: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  /**
   * 课程介绍
   */
  courseDescription: string
  /**
   * 课程特色
   */
  courseFeatures: string
  /**
   * 日期包细节
   */
  datePackageDetail: string
  /**
   * 结课时间
   */
  endTime: string
  /**
   * 含金量值
   */
  goldContent: number
  /**
   * 课程分类id
   */
  idPath: string
  /**
   * 小程序是否展示价格，0否，1是
   */
  isShowPrice: number
  /**
   * 主图url
   */
  mainPicture: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 最少开课人数，即开班人数
   */
  minClassCount: number
  /**
   * 课程名称
   */
  name: string
  /**
   * 其他说明
   */
  otherInstructions: string
  /**
   * 课程售价
   */
  price: number
  /**
   * 计费方式
   */
  priceMethod: string
  /**
   * 轮播图url列表
   */
  publicityPictureUrls: string[]
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  /**
   * 单节课时长
   */
  singleClassDuration: number
  /**
   * 推荐顺序
   */
  sortNumber: number
  /**
   * 特色标签
   */
  specialLabel: string
  /**
   * 开课时间
   */
  startTime: string
  /**
   * 已学人数
   */
  studentsNumber: number
  /**
   * 适用年龄范围结束时间
   */
  suitAgeEnd: number
  /**
   * 适用年龄范围开始时间
   */
  suitAgeStart: number
  /**
   * 授课语言
   */
  teachLanguageCode: string
  /**
   * 授课方式
   */
  teachWayCode: string
  /**
   * 讲师列表
   */
  teachers: CourseTeacherVO[]
  /**
   * 教学特点
   */
  teachingCharacteristics: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  /**
   * 试听id
   */
  trialLessonId: string
}

export interface CourseTeacherVO {
  /**
   * 详细地址
   */
  address: string
  /**
   * 国家地区全称
   */
  addressMargeName: string
  /**
   * 讲师头像
   */
  avatarUrl: string
  /**
   * 国家地区
   */
  countryAreas: string[]
  /**
   * 机构id
   */
  institutionId: number
  isShowTeacherDetail: number
  /**
   * 试听链接
   */
  listenLink: string
  /**
   * 备注信息
   */
  mark: string
  /**
   * 课程售价
   */
  price: number
  /**
   * 讲师id
   */
  teacherId: string
  /**
   * 讲师名称
   */
  teacherName: string
  /**
   * 试听id
   */
  trialLessonId: string
}

export interface ResultCourseDetailVO {
  code: string
  data: CourseDetailVO
  msg: string
}

export interface CourseQueryPageVO {
  ageRangeCode: string
  /**
   * 适用条件
   */
  applicableConditions: string
  /**
   * 购买数量
   */
  buyCount: string
  /**
   * 截止购买时间
   */
  buyTime: string
  classCount: number
  classHourseNumber: number
  comprehensiveEvaluation: number
  courseClassificationId: string
  /**
   * 课程分类名称
   */
  courseClassificationName: string
  courseDescription: string
  courseFeatures: string
  /**
   * 结课时间
   */
  endTime: string
  goldContent: number
  id: string
  isShowPrice: number
  /**
   * 主图
   */
  mainPicture: string
  mark: string
  minClassCount: number
  name: string
  otherInstructions: string
  price: number
  /**
   * 轮播宣传图
   */
  publicityPictureUrls: string[]
  /**
   * 购买须知
   */
  purchaseNotice: string
  /**
   * 是否可以插班 1 是 0 否
   */
  shiftChange: number
  singleClassDuration: number
  sortNumber: number
  specialLabel: string
  startTime: string
  studentsNumber: number
  suitAgeEnd: number
  suitAgeStart: number
  teachLanguageCode: string
  teachWayCode: string
  teachingCharacteristics: string
  /**
   * 教课方式Code
   */
  teachingMethodsCode: string
  /**
   * 教课方式
   */
  teachingMethodsName: string
  trialLessonId: string
}

export interface DataCourseQueryPageVO {
  list: CourseQueryPageVO[]
  total: number
}

export interface PageResultCourseQueryPageVO {
  code: string
  data: DataCourseQueryPageVO
  msg: string
}

export interface ResultListString {
  code: string
  data: string[]
  msg: string
}

export interface CountryAreaPageVO {
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人
   */
  createUser: string
  /**
   * 创建人姓名
   */
  createUserName: string
  /**
   * id
   */
  id: string
  /**
   * id全路径
   */
  idPath: string
  /**
   * 是否在小程序展示(0-不展示，1-展示)
   */
  isShowMiniapp: number
  /**
   * 级别1,2,3,4
   */
  level: number
  /**
   * 名称
   */
  name: string
  /**
   * 英文名称
   */
  nameEn: string
  /**
   * 父级id
   */
  parentId: string
  /**
   * 编辑时间
   */
  updateTime: string
  /**
   * 编辑人
   */
  updateUser: string
  /**
   * 编辑人姓名
   */
  updateUserName: string
}

export interface ResultListCountryAreaPageVO {
  code: string
  data: CountryAreaPageVO[]
  msg: string
}

export interface ResultListTreeNodeObject {
  code: string
  data: TreeNodeObject[]
  msg: string
}

export interface TreeNodeObject {
  biz: IObject
  children: IObject[]
  id: string
  name: string
  param: IObject
  parent: boolean
  parentId: string
}

export interface IPageCityEntity {
  current: number
  pages: number
  records: CityEntity[]
  size: number
  total: number
}

export interface AgreementForm {
  /**
   * 内容
   */
  contentData: string
  /**
   * 创建时间
   */
  createTime: string
  /**
   * 创建人ID
   */
  createUser: string
  /**
   * 主键
   */
  id: string
  /**
   * 是否展示
   */
  isDisplay: number
  /**
   * 标题
   */
  title: string
  /**
   * 更新时间
   */
  updateTime: string
  /**
   * 修改人ID
   */
  updateUser: string
}

export interface ResultAgreementForm {
  code: string
  data: AgreementForm
  msg: string
}

